/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DetectedNewsletterListResponse,
  DetectedNewsletterResponse,
  HTTPValidationError,
  ListNewslettersApiNewslettersGetParams
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List detected newsletters with pagination and optional sender filter.
 * @summary List Newsletters
 */
export type listNewslettersApiNewslettersGetResponse200 = {
  data: DetectedNewsletterListResponse
  status: 200
}

export type listNewslettersApiNewslettersGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listNewslettersApiNewslettersGetResponseSuccess = (listNewslettersApiNewslettersGetResponse200) & {
  headers: Headers;
};
export type listNewslettersApiNewslettersGetResponseError = (listNewslettersApiNewslettersGetResponse422) & {
  headers: Headers;
};

export type listNewslettersApiNewslettersGetResponse = (listNewslettersApiNewslettersGetResponseSuccess | listNewslettersApiNewslettersGetResponseError)

export const getListNewslettersApiNewslettersGetUrl = (params?: ListNewslettersApiNewslettersGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/newsletters?${stringifiedParams}` : `/api/newsletters`
}

export const listNewslettersApiNewslettersGet = async (params?: ListNewslettersApiNewslettersGetParams, options?: RequestInit): Promise<listNewslettersApiNewslettersGetResponse> => {

  return customInstance<listNewslettersApiNewslettersGetResponse>(getListNewslettersApiNewslettersGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListNewslettersApiNewslettersGetQueryKey = (params?: ListNewslettersApiNewslettersGetParams,) => {
    return [
    `/api/newsletters`, ...(params ? [params] : [])
    ] as const;
    }


export const getListNewslettersApiNewslettersGetQueryOptions = <TData = Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError = HTTPValidationError>(params?: ListNewslettersApiNewslettersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNewslettersApiNewslettersGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>> = ({ signal }) => listNewslettersApiNewslettersGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListNewslettersApiNewslettersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>>
export type ListNewslettersApiNewslettersGetQueryError = HTTPValidationError


export function useListNewslettersApiNewslettersGet<TData = Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError = HTTPValidationError>(
 params: undefined |  ListNewslettersApiNewslettersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>,
          TError,
          Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNewslettersApiNewslettersGet<TData = Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError = HTTPValidationError>(
 params?: ListNewslettersApiNewslettersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>,
          TError,
          Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNewslettersApiNewslettersGet<TData = Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError = HTTPValidationError>(
 params?: ListNewslettersApiNewslettersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Newsletters
 */

export function useListNewslettersApiNewslettersGet<TData = Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError = HTTPValidationError>(
 params?: ListNewslettersApiNewslettersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNewslettersApiNewslettersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListNewslettersApiNewslettersGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get a single detected newsletter with full details.
 * @summary Get Newsletter
 */
export type getNewsletterApiNewslettersNewsletterIdGetResponse200 = {
  data: DetectedNewsletterResponse
  status: 200
}

export type getNewsletterApiNewslettersNewsletterIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getNewsletterApiNewslettersNewsletterIdGetResponseSuccess = (getNewsletterApiNewslettersNewsletterIdGetResponse200) & {
  headers: Headers;
};
export type getNewsletterApiNewslettersNewsletterIdGetResponseError = (getNewsletterApiNewslettersNewsletterIdGetResponse422) & {
  headers: Headers;
};

export type getNewsletterApiNewslettersNewsletterIdGetResponse = (getNewsletterApiNewslettersNewsletterIdGetResponseSuccess | getNewsletterApiNewslettersNewsletterIdGetResponseError)

export const getGetNewsletterApiNewslettersNewsletterIdGetUrl = (newsletterId: string,) => {




  return `/api/newsletters/${newsletterId}`
}

export const getNewsletterApiNewslettersNewsletterIdGet = async (newsletterId: string, options?: RequestInit): Promise<getNewsletterApiNewslettersNewsletterIdGetResponse> => {

  return customInstance<getNewsletterApiNewslettersNewsletterIdGetResponse>(getGetNewsletterApiNewslettersNewsletterIdGetUrl(newsletterId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetNewsletterApiNewslettersNewsletterIdGetQueryKey = (newsletterId: string,) => {
    return [
    `/api/newsletters/${newsletterId}`
    ] as const;
    }


export const getGetNewsletterApiNewslettersNewsletterIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError = HTTPValidationError>(newsletterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNewsletterApiNewslettersNewsletterIdGetQueryKey(newsletterId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>> = ({ signal }) => getNewsletterApiNewslettersNewsletterIdGet(newsletterId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(newsletterId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNewsletterApiNewslettersNewsletterIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>>
export type GetNewsletterApiNewslettersNewsletterIdGetQueryError = HTTPValidationError


export function useGetNewsletterApiNewslettersNewsletterIdGet<TData = Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError = HTTPValidationError>(
 newsletterId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>,
          TError,
          Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNewsletterApiNewslettersNewsletterIdGet<TData = Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError = HTTPValidationError>(
 newsletterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>,
          TError,
          Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNewsletterApiNewslettersNewsletterIdGet<TData = Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError = HTTPValidationError>(
 newsletterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Newsletter
 */

export function useGetNewsletterApiNewslettersNewsletterIdGet<TData = Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError = HTTPValidationError>(
 newsletterId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNewsletterApiNewslettersNewsletterIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNewsletterApiNewslettersNewsletterIdGetQueryOptions(newsletterId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete a detected newsletter record.
 * @summary Delete Newsletter
 */
export type deleteNewsletterApiNewslettersNewsletterIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteNewsletterApiNewslettersNewsletterIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteNewsletterApiNewslettersNewsletterIdDeleteResponseSuccess = (deleteNewsletterApiNewslettersNewsletterIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteNewsletterApiNewslettersNewsletterIdDeleteResponseError = (deleteNewsletterApiNewslettersNewsletterIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteNewsletterApiNewslettersNewsletterIdDeleteResponse = (deleteNewsletterApiNewslettersNewsletterIdDeleteResponseSuccess | deleteNewsletterApiNewslettersNewsletterIdDeleteResponseError)

export const getDeleteNewsletterApiNewslettersNewsletterIdDeleteUrl = (newsletterId: string,) => {




  return `/api/newsletters/${newsletterId}`
}

export const deleteNewsletterApiNewslettersNewsletterIdDelete = async (newsletterId: string, options?: RequestInit): Promise<deleteNewsletterApiNewslettersNewsletterIdDeleteResponse> => {

  return customInstance<deleteNewsletterApiNewslettersNewsletterIdDeleteResponse>(getDeleteNewsletterApiNewslettersNewsletterIdDeleteUrl(newsletterId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteNewsletterApiNewslettersNewsletterIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNewsletterApiNewslettersNewsletterIdDelete>>, TError,{newsletterId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteNewsletterApiNewslettersNewsletterIdDelete>>, TError,{newsletterId: string}, TContext> => {

const mutationKey = ['deleteNewsletterApiNewslettersNewsletterIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNewsletterApiNewslettersNewsletterIdDelete>>, {newsletterId: string}> = (props) => {
          const {newsletterId} = props ?? {};

          return  deleteNewsletterApiNewslettersNewsletterIdDelete(newsletterId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteNewsletterApiNewslettersNewsletterIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNewsletterApiNewslettersNewsletterIdDelete>>>

    export type DeleteNewsletterApiNewslettersNewsletterIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Newsletter
 */
export const useDeleteNewsletterApiNewslettersNewsletterIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNewsletterApiNewslettersNewsletterIdDelete>>, TError,{newsletterId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNewsletterApiNewslettersNewsletterIdDelete>>,
        TError,
        {newsletterId: string},
        TContext
      > => {
      return useMutation(getDeleteNewsletterApiNewslettersNewsletterIdDeleteMutationOptions(options), queryClient);
    }
