/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppliedLabelListResponse,
  HTTPValidationError,
  LabelSummaryListResponse,
  ListAppliedLabelsApiLabelsGetParams
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List applied labels with pagination and optional label filter.
 * @summary List Applied Labels
 */
export type listAppliedLabelsApiLabelsGetResponse200 = {
  data: AppliedLabelListResponse
  status: 200
}

export type listAppliedLabelsApiLabelsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listAppliedLabelsApiLabelsGetResponseSuccess = (listAppliedLabelsApiLabelsGetResponse200) & {
  headers: Headers;
};
export type listAppliedLabelsApiLabelsGetResponseError = (listAppliedLabelsApiLabelsGetResponse422) & {
  headers: Headers;
};

export type listAppliedLabelsApiLabelsGetResponse = (listAppliedLabelsApiLabelsGetResponseSuccess | listAppliedLabelsApiLabelsGetResponseError)

export const getListAppliedLabelsApiLabelsGetUrl = (params?: ListAppliedLabelsApiLabelsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/labels?${stringifiedParams}` : `/api/labels`
}

export const listAppliedLabelsApiLabelsGet = async (params?: ListAppliedLabelsApiLabelsGetParams, options?: RequestInit): Promise<listAppliedLabelsApiLabelsGetResponse> => {

  return customInstance<listAppliedLabelsApiLabelsGetResponse>(getListAppliedLabelsApiLabelsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAppliedLabelsApiLabelsGetQueryKey = (params?: ListAppliedLabelsApiLabelsGetParams,) => {
    return [
    `/api/labels`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAppliedLabelsApiLabelsGetQueryOptions = <TData = Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError = HTTPValidationError>(params?: ListAppliedLabelsApiLabelsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAppliedLabelsApiLabelsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>> = ({ signal }) => listAppliedLabelsApiLabelsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAppliedLabelsApiLabelsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>>
export type ListAppliedLabelsApiLabelsGetQueryError = HTTPValidationError


export function useListAppliedLabelsApiLabelsGet<TData = Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListAppliedLabelsApiLabelsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>,
          TError,
          Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAppliedLabelsApiLabelsGet<TData = Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError = HTTPValidationError>(
 params?: ListAppliedLabelsApiLabelsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>,
          TError,
          Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAppliedLabelsApiLabelsGet<TData = Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError = HTTPValidationError>(
 params?: ListAppliedLabelsApiLabelsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Applied Labels
 */

export function useListAppliedLabelsApiLabelsGet<TData = Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError = HTTPValidationError>(
 params?: ListAppliedLabelsApiLabelsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAppliedLabelsApiLabelsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAppliedLabelsApiLabelsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get a summary of unique labels with usage counts.
 * @summary Get Label Summary
 */
export type getLabelSummaryApiLabelsSummaryGetResponse200 = {
  data: LabelSummaryListResponse
  status: 200
}

export type getLabelSummaryApiLabelsSummaryGetResponseSuccess = (getLabelSummaryApiLabelsSummaryGetResponse200) & {
  headers: Headers;
};
;

export type getLabelSummaryApiLabelsSummaryGetResponse = (getLabelSummaryApiLabelsSummaryGetResponseSuccess)

export const getGetLabelSummaryApiLabelsSummaryGetUrl = () => {




  return `/api/labels/summary`
}

export const getLabelSummaryApiLabelsSummaryGet = async ( options?: RequestInit): Promise<getLabelSummaryApiLabelsSummaryGetResponse> => {

  return customInstance<getLabelSummaryApiLabelsSummaryGetResponse>(getGetLabelSummaryApiLabelsSummaryGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLabelSummaryApiLabelsSummaryGetQueryKey = () => {
    return [
    `/api/labels/summary`
    ] as const;
    }


export const getGetLabelSummaryApiLabelsSummaryGetQueryOptions = <TData = Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLabelSummaryApiLabelsSummaryGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>> = ({ signal }) => getLabelSummaryApiLabelsSummaryGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLabelSummaryApiLabelsSummaryGetQueryResult = NonNullable<Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>>
export type GetLabelSummaryApiLabelsSummaryGetQueryError = unknown


export function useGetLabelSummaryApiLabelsSummaryGet<TData = Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabelSummaryApiLabelsSummaryGet<TData = Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLabelSummaryApiLabelsSummaryGet<TData = Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Label Summary
 */

export function useGetLabelSummaryApiLabelsSummaryGet<TData = Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLabelSummaryApiLabelsSummaryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLabelSummaryApiLabelsSummaryGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Delete an applied label record.
 * @summary Delete Applied Label
 */
export type deleteAppliedLabelApiLabelsLabelIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteAppliedLabelApiLabelsLabelIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteAppliedLabelApiLabelsLabelIdDeleteResponseSuccess = (deleteAppliedLabelApiLabelsLabelIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteAppliedLabelApiLabelsLabelIdDeleteResponseError = (deleteAppliedLabelApiLabelsLabelIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteAppliedLabelApiLabelsLabelIdDeleteResponse = (deleteAppliedLabelApiLabelsLabelIdDeleteResponseSuccess | deleteAppliedLabelApiLabelsLabelIdDeleteResponseError)

export const getDeleteAppliedLabelApiLabelsLabelIdDeleteUrl = (labelId: string,) => {




  return `/api/labels/${labelId}`
}

export const deleteAppliedLabelApiLabelsLabelIdDelete = async (labelId: string, options?: RequestInit): Promise<deleteAppliedLabelApiLabelsLabelIdDeleteResponse> => {

  return customInstance<deleteAppliedLabelApiLabelsLabelIdDeleteResponse>(getDeleteAppliedLabelApiLabelsLabelIdDeleteUrl(labelId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAppliedLabelApiLabelsLabelIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAppliedLabelApiLabelsLabelIdDelete>>, TError,{labelId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAppliedLabelApiLabelsLabelIdDelete>>, TError,{labelId: string}, TContext> => {

const mutationKey = ['deleteAppliedLabelApiLabelsLabelIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAppliedLabelApiLabelsLabelIdDelete>>, {labelId: string}> = (props) => {
          const {labelId} = props ?? {};

          return  deleteAppliedLabelApiLabelsLabelIdDelete(labelId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAppliedLabelApiLabelsLabelIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAppliedLabelApiLabelsLabelIdDelete>>>

    export type DeleteAppliedLabelApiLabelsLabelIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Applied Label
 */
export const useDeleteAppliedLabelApiLabelsLabelIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAppliedLabelApiLabelsLabelIdDelete>>, TError,{labelId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAppliedLabelApiLabelsLabelIdDelete>>,
        TError,
        {labelId: string},
        TContext
      > => {
      return useMutation(getDeleteAppliedLabelApiLabelsLabelIdDeleteMutationOptions(options), queryClient);
    }
