/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EmailSummaryListResponse,
  EmailSummaryResponse,
  HTTPValidationError,
  ListSummariesApiSummariesGetParams
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List email summaries with pagination and optional filters.
 * @summary List Summaries
 */
export type listSummariesApiSummariesGetResponse200 = {
  data: EmailSummaryListResponse
  status: 200
}

export type listSummariesApiSummariesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listSummariesApiSummariesGetResponseSuccess = (listSummariesApiSummariesGetResponse200) & {
  headers: Headers;
};
export type listSummariesApiSummariesGetResponseError = (listSummariesApiSummariesGetResponse422) & {
  headers: Headers;
};

export type listSummariesApiSummariesGetResponse = (listSummariesApiSummariesGetResponseSuccess | listSummariesApiSummariesGetResponseError)

export const getListSummariesApiSummariesGetUrl = (params?: ListSummariesApiSummariesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/summaries?${stringifiedParams}` : `/api/summaries`
}

export const listSummariesApiSummariesGet = async (params?: ListSummariesApiSummariesGetParams, options?: RequestInit): Promise<listSummariesApiSummariesGetResponse> => {

  return customInstance<listSummariesApiSummariesGetResponse>(getListSummariesApiSummariesGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSummariesApiSummariesGetQueryKey = (params?: ListSummariesApiSummariesGetParams,) => {
    return [
    `/api/summaries`, ...(params ? [params] : [])
    ] as const;
    }


export const getListSummariesApiSummariesGetQueryOptions = <TData = Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError = HTTPValidationError>(params?: ListSummariesApiSummariesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSummariesApiSummariesGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSummariesApiSummariesGet>>> = ({ signal }) => listSummariesApiSummariesGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSummariesApiSummariesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSummariesApiSummariesGet>>>
export type ListSummariesApiSummariesGetQueryError = HTTPValidationError


export function useListSummariesApiSummariesGet<TData = Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError = HTTPValidationError>(
 params: undefined |  ListSummariesApiSummariesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSummariesApiSummariesGet>>,
          TError,
          Awaited<ReturnType<typeof listSummariesApiSummariesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSummariesApiSummariesGet<TData = Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError = HTTPValidationError>(
 params?: ListSummariesApiSummariesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSummariesApiSummariesGet>>,
          TError,
          Awaited<ReturnType<typeof listSummariesApiSummariesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSummariesApiSummariesGet<TData = Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError = HTTPValidationError>(
 params?: ListSummariesApiSummariesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Summaries
 */

export function useListSummariesApiSummariesGet<TData = Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError = HTTPValidationError>(
 params?: ListSummariesApiSummariesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSummariesApiSummariesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSummariesApiSummariesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get a single email summary with full details.
 * @summary Get Summary
 */
export type getSummaryApiSummariesSummaryIdGetResponse200 = {
  data: EmailSummaryResponse
  status: 200
}

export type getSummaryApiSummariesSummaryIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getSummaryApiSummariesSummaryIdGetResponseSuccess = (getSummaryApiSummariesSummaryIdGetResponse200) & {
  headers: Headers;
};
export type getSummaryApiSummariesSummaryIdGetResponseError = (getSummaryApiSummariesSummaryIdGetResponse422) & {
  headers: Headers;
};

export type getSummaryApiSummariesSummaryIdGetResponse = (getSummaryApiSummariesSummaryIdGetResponseSuccess | getSummaryApiSummariesSummaryIdGetResponseError)

export const getGetSummaryApiSummariesSummaryIdGetUrl = (summaryId: string,) => {




  return `/api/summaries/${summaryId}`
}

export const getSummaryApiSummariesSummaryIdGet = async (summaryId: string, options?: RequestInit): Promise<getSummaryApiSummariesSummaryIdGetResponse> => {

  return customInstance<getSummaryApiSummariesSummaryIdGetResponse>(getGetSummaryApiSummariesSummaryIdGetUrl(summaryId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSummaryApiSummariesSummaryIdGetQueryKey = (summaryId: string,) => {
    return [
    `/api/summaries/${summaryId}`
    ] as const;
    }


export const getGetSummaryApiSummariesSummaryIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError = HTTPValidationError>(summaryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSummaryApiSummariesSummaryIdGetQueryKey(summaryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>> = ({ signal }) => getSummaryApiSummariesSummaryIdGet(summaryId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(summaryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSummaryApiSummariesSummaryIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>>
export type GetSummaryApiSummariesSummaryIdGetQueryError = HTTPValidationError


export function useGetSummaryApiSummariesSummaryIdGet<TData = Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError = HTTPValidationError>(
 summaryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSummaryApiSummariesSummaryIdGet<TData = Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError = HTTPValidationError>(
 summaryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSummaryApiSummariesSummaryIdGet<TData = Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError = HTTPValidationError>(
 summaryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Summary
 */

export function useGetSummaryApiSummariesSummaryIdGet<TData = Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError = HTTPValidationError>(
 summaryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummaryApiSummariesSummaryIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSummaryApiSummariesSummaryIdGetQueryOptions(summaryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Delete a single email summary.
 * @summary Delete Summary
 */
export type deleteSummaryApiSummariesSummaryIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteSummaryApiSummariesSummaryIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteSummaryApiSummariesSummaryIdDeleteResponseSuccess = (deleteSummaryApiSummariesSummaryIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteSummaryApiSummariesSummaryIdDeleteResponseError = (deleteSummaryApiSummariesSummaryIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteSummaryApiSummariesSummaryIdDeleteResponse = (deleteSummaryApiSummariesSummaryIdDeleteResponseSuccess | deleteSummaryApiSummariesSummaryIdDeleteResponseError)

export const getDeleteSummaryApiSummariesSummaryIdDeleteUrl = (summaryId: string,) => {




  return `/api/summaries/${summaryId}`
}

export const deleteSummaryApiSummariesSummaryIdDelete = async (summaryId: string, options?: RequestInit): Promise<deleteSummaryApiSummariesSummaryIdDeleteResponse> => {

  return customInstance<deleteSummaryApiSummariesSummaryIdDeleteResponse>(getDeleteSummaryApiSummariesSummaryIdDeleteUrl(summaryId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSummaryApiSummariesSummaryIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSummaryApiSummariesSummaryIdDelete>>, TError,{summaryId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSummaryApiSummariesSummaryIdDelete>>, TError,{summaryId: string}, TContext> => {

const mutationKey = ['deleteSummaryApiSummariesSummaryIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSummaryApiSummariesSummaryIdDelete>>, {summaryId: string}> = (props) => {
          const {summaryId} = props ?? {};

          return  deleteSummaryApiSummariesSummaryIdDelete(summaryId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSummaryApiSummariesSummaryIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSummaryApiSummariesSummaryIdDelete>>>

    export type DeleteSummaryApiSummariesSummaryIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Summary
 */
export const useDeleteSummaryApiSummariesSummaryIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSummaryApiSummariesSummaryIdDelete>>, TError,{summaryId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSummaryApiSummariesSummaryIdDelete>>,
        TError,
        {summaryId: string},
        TContext
      > => {
      return useMutation(getDeleteSummaryApiSummariesSummaryIdDeleteMutationOptions(options), queryClient);
    }
