/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AIProviderCreate,
  AIProviderResponse,
  AIProviderTestResult,
  AIProviderUpdate,
  AppSchemasAiProviderPauseUpdate,
  HTTPValidationError,
  PluginInfo
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List all AI providers for the current user.
 * @summary List Providers
 */
export type listProvidersApiAiProvidersGetResponse200 = {
  data: AIProviderResponse[]
  status: 200
}

export type listProvidersApiAiProvidersGetResponseSuccess = (listProvidersApiAiProvidersGetResponse200) & {
  headers: Headers;
};
;

export type listProvidersApiAiProvidersGetResponse = (listProvidersApiAiProvidersGetResponseSuccess)

export const getListProvidersApiAiProvidersGetUrl = () => {




  return `/api/ai-providers`
}

export const listProvidersApiAiProvidersGet = async ( options?: RequestInit): Promise<listProvidersApiAiProvidersGetResponse> => {

  return customInstance<listProvidersApiAiProvidersGetResponse>(getListProvidersApiAiProvidersGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProvidersApiAiProvidersGetQueryKey = () => {
    return [
    `/api/ai-providers`
    ] as const;
    }


export const getListProvidersApiAiProvidersGetQueryOptions = <TData = Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProvidersApiAiProvidersGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>> = ({ signal }) => listProvidersApiAiProvidersGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProvidersApiAiProvidersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>>
export type ListProvidersApiAiProvidersGetQueryError = unknown


export function useListProvidersApiAiProvidersGet<TData = Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>,
          TError,
          Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProvidersApiAiProvidersGet<TData = Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>,
          TError,
          Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProvidersApiAiProvidersGet<TData = Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Providers
 */

export function useListProvidersApiAiProvidersGet<TData = Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProvidersApiAiProvidersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProvidersApiAiProvidersGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new AI provider with encrypted API key.

When the user creates their first provider, all pipeline plugins
are auto-assigned to it so the pipeline works out of the box.
 * @summary Create Provider
 */
export type createProviderApiAiProvidersPostResponse201 = {
  data: AIProviderResponse
  status: 201
}

export type createProviderApiAiProvidersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createProviderApiAiProvidersPostResponseSuccess = (createProviderApiAiProvidersPostResponse201) & {
  headers: Headers;
};
export type createProviderApiAiProvidersPostResponseError = (createProviderApiAiProvidersPostResponse422) & {
  headers: Headers;
};

export type createProviderApiAiProvidersPostResponse = (createProviderApiAiProvidersPostResponseSuccess | createProviderApiAiProvidersPostResponseError)

export const getCreateProviderApiAiProvidersPostUrl = () => {




  return `/api/ai-providers`
}

export const createProviderApiAiProvidersPost = async (aIProviderCreate: AIProviderCreate, options?: RequestInit): Promise<createProviderApiAiProvidersPostResponse> => {

  return customInstance<createProviderApiAiProvidersPostResponse>(getCreateProviderApiAiProvidersPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      aIProviderCreate,)
  }
);}




export const getCreateProviderApiAiProvidersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProviderApiAiProvidersPost>>, TError,{data: AIProviderCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProviderApiAiProvidersPost>>, TError,{data: AIProviderCreate}, TContext> => {

const mutationKey = ['createProviderApiAiProvidersPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProviderApiAiProvidersPost>>, {data: AIProviderCreate}> = (props) => {
          const {data} = props ?? {};

          return  createProviderApiAiProvidersPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProviderApiAiProvidersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProviderApiAiProvidersPost>>>
    export type CreateProviderApiAiProvidersPostMutationBody = AIProviderCreate
    export type CreateProviderApiAiProvidersPostMutationError = HTTPValidationError

    /**
 * @summary Create Provider
 */
export const useCreateProviderApiAiProvidersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProviderApiAiProvidersPost>>, TError,{data: AIProviderCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProviderApiAiProvidersPost>>,
        TError,
        {data: AIProviderCreate},
        TContext
      > => {
      return useMutation(getCreateProviderApiAiProvidersPostMutationOptions(options), queryClient);
    }
    /**
 * List all available plugins, sorted by user-defined order if set.
 * @summary List Plugins
 */
export type listPluginsApiAiProvidersPluginsGetResponse200 = {
  data: PluginInfo[]
  status: 200
}

export type listPluginsApiAiProvidersPluginsGetResponseSuccess = (listPluginsApiAiProvidersPluginsGetResponse200) & {
  headers: Headers;
};
;

export type listPluginsApiAiProvidersPluginsGetResponse = (listPluginsApiAiProvidersPluginsGetResponseSuccess)

export const getListPluginsApiAiProvidersPluginsGetUrl = () => {




  return `/api/ai-providers/plugins`
}

export const listPluginsApiAiProvidersPluginsGet = async ( options?: RequestInit): Promise<listPluginsApiAiProvidersPluginsGetResponse> => {

  return customInstance<listPluginsApiAiProvidersPluginsGetResponse>(getListPluginsApiAiProvidersPluginsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPluginsApiAiProvidersPluginsGetQueryKey = () => {
    return [
    `/api/ai-providers/plugins`
    ] as const;
    }


export const getListPluginsApiAiProvidersPluginsGetQueryOptions = <TData = Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPluginsApiAiProvidersPluginsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>> = ({ signal }) => listPluginsApiAiProvidersPluginsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPluginsApiAiProvidersPluginsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>>
export type ListPluginsApiAiProvidersPluginsGetQueryError = unknown


export function useListPluginsApiAiProvidersPluginsGet<TData = Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>,
          TError,
          Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPluginsApiAiProvidersPluginsGet<TData = Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>,
          TError,
          Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPluginsApiAiProvidersPluginsGet<TData = Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Plugins
 */

export function useListPluginsApiAiProvidersPluginsGet<TData = Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPluginsApiAiProvidersPluginsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPluginsApiAiProvidersPluginsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get a single AI provider (API key excluded).
 * @summary Get Provider
 */
export type getProviderApiAiProvidersProviderIdGetResponse200 = {
  data: AIProviderResponse
  status: 200
}

export type getProviderApiAiProvidersProviderIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getProviderApiAiProvidersProviderIdGetResponseSuccess = (getProviderApiAiProvidersProviderIdGetResponse200) & {
  headers: Headers;
};
export type getProviderApiAiProvidersProviderIdGetResponseError = (getProviderApiAiProvidersProviderIdGetResponse422) & {
  headers: Headers;
};

export type getProviderApiAiProvidersProviderIdGetResponse = (getProviderApiAiProvidersProviderIdGetResponseSuccess | getProviderApiAiProvidersProviderIdGetResponseError)

export const getGetProviderApiAiProvidersProviderIdGetUrl = (providerId: string,) => {




  return `/api/ai-providers/${providerId}`
}

export const getProviderApiAiProvidersProviderIdGet = async (providerId: string, options?: RequestInit): Promise<getProviderApiAiProvidersProviderIdGetResponse> => {

  return customInstance<getProviderApiAiProvidersProviderIdGetResponse>(getGetProviderApiAiProvidersProviderIdGetUrl(providerId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProviderApiAiProvidersProviderIdGetQueryKey = (providerId: string,) => {
    return [
    `/api/ai-providers/${providerId}`
    ] as const;
    }


export const getGetProviderApiAiProvidersProviderIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError = HTTPValidationError>(providerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProviderApiAiProvidersProviderIdGetQueryKey(providerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>> = ({ signal }) => getProviderApiAiProvidersProviderIdGet(providerId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(providerId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProviderApiAiProvidersProviderIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>>
export type GetProviderApiAiProvidersProviderIdGetQueryError = HTTPValidationError


export function useGetProviderApiAiProvidersProviderIdGet<TData = Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError = HTTPValidationError>(
 providerId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProviderApiAiProvidersProviderIdGet<TData = Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError = HTTPValidationError>(
 providerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>,
          TError,
          Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProviderApiAiProvidersProviderIdGet<TData = Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError = HTTPValidationError>(
 providerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Provider
 */

export function useGetProviderApiAiProvidersProviderIdGet<TData = Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError = HTTPValidationError>(
 providerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProviderApiAiProvidersProviderIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProviderApiAiProvidersProviderIdGetQueryOptions(providerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update an AI provider. Only provided fields are updated.
 * @summary Update Provider
 */
export type updateProviderApiAiProvidersProviderIdPutResponse200 = {
  data: AIProviderResponse
  status: 200
}

export type updateProviderApiAiProvidersProviderIdPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateProviderApiAiProvidersProviderIdPutResponseSuccess = (updateProviderApiAiProvidersProviderIdPutResponse200) & {
  headers: Headers;
};
export type updateProviderApiAiProvidersProviderIdPutResponseError = (updateProviderApiAiProvidersProviderIdPutResponse422) & {
  headers: Headers;
};

export type updateProviderApiAiProvidersProviderIdPutResponse = (updateProviderApiAiProvidersProviderIdPutResponseSuccess | updateProviderApiAiProvidersProviderIdPutResponseError)

export const getUpdateProviderApiAiProvidersProviderIdPutUrl = (providerId: string,) => {




  return `/api/ai-providers/${providerId}`
}

export const updateProviderApiAiProvidersProviderIdPut = async (providerId: string,
    aIProviderUpdate: AIProviderUpdate, options?: RequestInit): Promise<updateProviderApiAiProvidersProviderIdPutResponse> => {

  return customInstance<updateProviderApiAiProvidersProviderIdPutResponse>(getUpdateProviderApiAiProvidersProviderIdPutUrl(providerId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      aIProviderUpdate,)
  }
);}




export const getUpdateProviderApiAiProvidersProviderIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProviderApiAiProvidersProviderIdPut>>, TError,{providerId: string;data: AIProviderUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProviderApiAiProvidersProviderIdPut>>, TError,{providerId: string;data: AIProviderUpdate}, TContext> => {

const mutationKey = ['updateProviderApiAiProvidersProviderIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProviderApiAiProvidersProviderIdPut>>, {providerId: string;data: AIProviderUpdate}> = (props) => {
          const {providerId,data} = props ?? {};

          return  updateProviderApiAiProvidersProviderIdPut(providerId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProviderApiAiProvidersProviderIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateProviderApiAiProvidersProviderIdPut>>>
    export type UpdateProviderApiAiProvidersProviderIdPutMutationBody = AIProviderUpdate
    export type UpdateProviderApiAiProvidersProviderIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Provider
 */
export const useUpdateProviderApiAiProvidersProviderIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProviderApiAiProvidersProviderIdPut>>, TError,{providerId: string;data: AIProviderUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProviderApiAiProvidersProviderIdPut>>,
        TError,
        {providerId: string;data: AIProviderUpdate},
        TContext
      > => {
      return useMutation(getUpdateProviderApiAiProvidersProviderIdPutMutationOptions(options), queryClient);
    }
    /**
 * Delete an AI provider.
 * @summary Delete Provider
 */
export type deleteProviderApiAiProvidersProviderIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteProviderApiAiProvidersProviderIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteProviderApiAiProvidersProviderIdDeleteResponseSuccess = (deleteProviderApiAiProvidersProviderIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteProviderApiAiProvidersProviderIdDeleteResponseError = (deleteProviderApiAiProvidersProviderIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteProviderApiAiProvidersProviderIdDeleteResponse = (deleteProviderApiAiProvidersProviderIdDeleteResponseSuccess | deleteProviderApiAiProvidersProviderIdDeleteResponseError)

export const getDeleteProviderApiAiProvidersProviderIdDeleteUrl = (providerId: string,) => {




  return `/api/ai-providers/${providerId}`
}

export const deleteProviderApiAiProvidersProviderIdDelete = async (providerId: string, options?: RequestInit): Promise<deleteProviderApiAiProvidersProviderIdDeleteResponse> => {

  return customInstance<deleteProviderApiAiProvidersProviderIdDeleteResponse>(getDeleteProviderApiAiProvidersProviderIdDeleteUrl(providerId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteProviderApiAiProvidersProviderIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProviderApiAiProvidersProviderIdDelete>>, TError,{providerId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProviderApiAiProvidersProviderIdDelete>>, TError,{providerId: string}, TContext> => {

const mutationKey = ['deleteProviderApiAiProvidersProviderIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProviderApiAiProvidersProviderIdDelete>>, {providerId: string}> = (props) => {
          const {providerId} = props ?? {};

          return  deleteProviderApiAiProvidersProviderIdDelete(providerId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProviderApiAiProvidersProviderIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProviderApiAiProvidersProviderIdDelete>>>

    export type DeleteProviderApiAiProvidersProviderIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Provider
 */
export const useDeleteProviderApiAiProvidersProviderIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProviderApiAiProvidersProviderIdDelete>>, TError,{providerId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProviderApiAiProvidersProviderIdDelete>>,
        TError,
        {providerId: string},
        TContext
      > => {
      return useMutation(getDeleteProviderApiAiProvidersProviderIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Test connectivity to an AI provider.
 * @summary Test Provider
 */
export type testProviderApiAiProvidersProviderIdTestPostResponse200 = {
  data: AIProviderTestResult
  status: 200
}

export type testProviderApiAiProvidersProviderIdTestPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type testProviderApiAiProvidersProviderIdTestPostResponseSuccess = (testProviderApiAiProvidersProviderIdTestPostResponse200) & {
  headers: Headers;
};
export type testProviderApiAiProvidersProviderIdTestPostResponseError = (testProviderApiAiProvidersProviderIdTestPostResponse422) & {
  headers: Headers;
};

export type testProviderApiAiProvidersProviderIdTestPostResponse = (testProviderApiAiProvidersProviderIdTestPostResponseSuccess | testProviderApiAiProvidersProviderIdTestPostResponseError)

export const getTestProviderApiAiProvidersProviderIdTestPostUrl = (providerId: string,) => {




  return `/api/ai-providers/${providerId}/test`
}

export const testProviderApiAiProvidersProviderIdTestPost = async (providerId: string, options?: RequestInit): Promise<testProviderApiAiProvidersProviderIdTestPostResponse> => {

  return customInstance<testProviderApiAiProvidersProviderIdTestPostResponse>(getTestProviderApiAiProvidersProviderIdTestPostUrl(providerId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getTestProviderApiAiProvidersProviderIdTestPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testProviderApiAiProvidersProviderIdTestPost>>, TError,{providerId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof testProviderApiAiProvidersProviderIdTestPost>>, TError,{providerId: string}, TContext> => {

const mutationKey = ['testProviderApiAiProvidersProviderIdTestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testProviderApiAiProvidersProviderIdTestPost>>, {providerId: string}> = (props) => {
          const {providerId} = props ?? {};

          return  testProviderApiAiProvidersProviderIdTestPost(providerId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestProviderApiAiProvidersProviderIdTestPostMutationResult = NonNullable<Awaited<ReturnType<typeof testProviderApiAiProvidersProviderIdTestPost>>>

    export type TestProviderApiAiProvidersProviderIdTestPostMutationError = HTTPValidationError

    /**
 * @summary Test Provider
 */
export const useTestProviderApiAiProvidersProviderIdTestPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testProviderApiAiProvidersProviderIdTestPost>>, TError,{providerId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testProviderApiAiProvidersProviderIdTestPost>>,
        TError,
        {providerId: string},
        TContext
      > => {
      return useMutation(getTestProviderApiAiProvidersProviderIdTestPostMutationOptions(options), queryClient);
    }
    /**
 * Reset an AI provider's health status (clear circuit breaker).

Re-enables a provider that was paused due to consecutive errors.
Use this after fixing the underlying issue (e.g. renewed API key,
restored network connectivity).
 * @summary Reset Provider Health
 */
export type resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponse200 = {
  data: AIProviderResponse
  status: 200
}

export type resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponseSuccess = (resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponse200) & {
  headers: Headers;
};
export type resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponseError = (resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponse422) & {
  headers: Headers;
};

export type resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponse = (resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponseSuccess | resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponseError)

export const getResetProviderHealthApiAiProvidersProviderIdResetHealthPostUrl = (providerId: string,) => {




  return `/api/ai-providers/${providerId}/reset-health`
}

export const resetProviderHealthApiAiProvidersProviderIdResetHealthPost = async (providerId: string, options?: RequestInit): Promise<resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponse> => {

  return customInstance<resetProviderHealthApiAiProvidersProviderIdResetHealthPostResponse>(getResetProviderHealthApiAiProvidersProviderIdResetHealthPostUrl(providerId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getResetProviderHealthApiAiProvidersProviderIdResetHealthPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetProviderHealthApiAiProvidersProviderIdResetHealthPost>>, TError,{providerId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resetProviderHealthApiAiProvidersProviderIdResetHealthPost>>, TError,{providerId: string}, TContext> => {

const mutationKey = ['resetProviderHealthApiAiProvidersProviderIdResetHealthPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetProviderHealthApiAiProvidersProviderIdResetHealthPost>>, {providerId: string}> = (props) => {
          const {providerId} = props ?? {};

          return  resetProviderHealthApiAiProvidersProviderIdResetHealthPost(providerId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResetProviderHealthApiAiProvidersProviderIdResetHealthPostMutationResult = NonNullable<Awaited<ReturnType<typeof resetProviderHealthApiAiProvidersProviderIdResetHealthPost>>>

    export type ResetProviderHealthApiAiProvidersProviderIdResetHealthPostMutationError = HTTPValidationError

    /**
 * @summary Reset Provider Health
 */
export const useResetProviderHealthApiAiProvidersProviderIdResetHealthPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetProviderHealthApiAiProvidersProviderIdResetHealthPost>>, TError,{providerId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetProviderHealthApiAiProvidersProviderIdResetHealthPost>>,
        TError,
        {providerId: string},
        TContext
      > => {
      return useMutation(getResetProviderHealthApiAiProvidersProviderIdResetHealthPostMutationOptions(options), queryClient);
    }
    /**
 * Update the pause state of an AI provider.

When ``paused`` is true the provider is paused — the scheduler will
skip it until it is unpaused.  When ``paused`` is false the pause
flag, error counters and the error history are cleared and the
scheduler is triggered immediately.
 * @summary Update Pause State
 */
export type updatePauseStateApiAiProvidersProviderIdPausePatchResponse200 = {
  data: AIProviderResponse
  status: 200
}

export type updatePauseStateApiAiProvidersProviderIdPausePatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updatePauseStateApiAiProvidersProviderIdPausePatchResponseSuccess = (updatePauseStateApiAiProvidersProviderIdPausePatchResponse200) & {
  headers: Headers;
};
export type updatePauseStateApiAiProvidersProviderIdPausePatchResponseError = (updatePauseStateApiAiProvidersProviderIdPausePatchResponse422) & {
  headers: Headers;
};

export type updatePauseStateApiAiProvidersProviderIdPausePatchResponse = (updatePauseStateApiAiProvidersProviderIdPausePatchResponseSuccess | updatePauseStateApiAiProvidersProviderIdPausePatchResponseError)

export const getUpdatePauseStateApiAiProvidersProviderIdPausePatchUrl = (providerId: string,) => {




  return `/api/ai-providers/${providerId}/pause`
}

export const updatePauseStateApiAiProvidersProviderIdPausePatch = async (providerId: string,
    appSchemasAiProviderPauseUpdate: AppSchemasAiProviderPauseUpdate, options?: RequestInit): Promise<updatePauseStateApiAiProvidersProviderIdPausePatchResponse> => {

  return customInstance<updatePauseStateApiAiProvidersProviderIdPausePatchResponse>(getUpdatePauseStateApiAiProvidersProviderIdPausePatchUrl(providerId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      appSchemasAiProviderPauseUpdate,)
  }
);}




export const getUpdatePauseStateApiAiProvidersProviderIdPausePatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePauseStateApiAiProvidersProviderIdPausePatch>>, TError,{providerId: string;data: AppSchemasAiProviderPauseUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePauseStateApiAiProvidersProviderIdPausePatch>>, TError,{providerId: string;data: AppSchemasAiProviderPauseUpdate}, TContext> => {

const mutationKey = ['updatePauseStateApiAiProvidersProviderIdPausePatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePauseStateApiAiProvidersProviderIdPausePatch>>, {providerId: string;data: AppSchemasAiProviderPauseUpdate}> = (props) => {
          const {providerId,data} = props ?? {};

          return  updatePauseStateApiAiProvidersProviderIdPausePatch(providerId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePauseStateApiAiProvidersProviderIdPausePatchMutationResult = NonNullable<Awaited<ReturnType<typeof updatePauseStateApiAiProvidersProviderIdPausePatch>>>
    export type UpdatePauseStateApiAiProvidersProviderIdPausePatchMutationBody = AppSchemasAiProviderPauseUpdate
    export type UpdatePauseStateApiAiProvidersProviderIdPausePatchMutationError = HTTPValidationError

    /**
 * @summary Update Pause State
 */
export const useUpdatePauseStateApiAiProvidersProviderIdPausePatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePauseStateApiAiProvidersProviderIdPausePatch>>, TError,{providerId: string;data: AppSchemasAiProviderPauseUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePauseStateApiAiProvidersProviderIdPausePatch>>,
        TError,
        {providerId: string;data: AppSchemasAiProviderPauseUpdate},
        TContext
      > => {
      return useMutation(getUpdatePauseStateApiAiProvidersProviderIdPausePatchMutationOptions(options), queryClient);
    }
