/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result of testing an LLM connection.
 */
export interface AIProviderTestResult {
  success: boolean;
  message: string;
  model: string;
}
