/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for creating an AI provider.
 */
export interface AIProviderCreate {
  /** Display name for this provider */
  name?: string | null;
  /** Provider type: 'openai' or 'ollama' */
  provider_type: string;
  /** API key (write-only, OpenAI only) */
  api_key?: string | null;
  /**
     * Provider API base URL
     * @maxLength 500
     */
  base_url: string;
  /**
     * Model identifier (e.g. 'gpt-4o', 'llama3.1')
     * @maxLength 100
     */
  model_name: string;
  /**
     * @minimum 64
     * @maximum 32768
     */
  max_tokens?: number;
  /**
     * @minimum 0
     * @maximum 2
     */
  temperature?: number;
  /** Per-provider LLM timeout in seconds (overrides global default) */
  timeout_seconds?: number | null;
}
