/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for an AI provider (API key never returned).
 */
export interface AIProviderResponse {
  id: string;
  name: string | null;
  provider_type: string;
  base_url: string;
  model_name: string;
  is_default: boolean;
  max_tokens: number;
  temperature: number;
  timeout_seconds: number | null;
  consecutive_errors: number;
  last_error: string | null;
  last_error_at: string | null;
  last_success_at: string | null;
  is_paused: boolean;
  manually_paused: boolean;
  paused_reason: string | null;
  paused_at: string | null;
  created_at: string;
  updated_at: string;
}
