/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ApprovalMode } from './approvalMode';

/**
 * Per-function approval mode update (all fields optional for true partial updates).
 */
export interface ApprovalModesUpdate {
  spam?: ApprovalMode | null;
  labeling?: ApprovalMode | null;
  smart_folder?: ApprovalMode | null;
  newsletter?: ApprovalMode | null;
  auto_reply?: ApprovalMode | null;
  coupon?: ApprovalMode | null;
  calendar?: ApprovalMode | null;
  summary?: ApprovalMode | null;
  rules?: ApprovalMode | null;
  contacts?: ApprovalMode | null;
  notifications?: ApprovalMode | null;
}
