/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Approval mode for AI function plugins.
 */
export type ApprovalMode = typeof ApprovalMode[keyof typeof ApprovalMode];


export const ApprovalMode = {
  auto: 'auto',
  approval: 'approval',
  disabled: 'disabled',
} as const;
