/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * User-edited actions to override the AI-proposed actions.
 */
export type ApprovalEditRequestEditedActions = { [key: string]: unknown };
