/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ApprovalResponseEditedActions } from './approvalResponseEditedActions';
import type { ApprovalResponseProposedAction } from './approvalResponseProposedAction';

/**
 * Response schema for an approval queue entry.
 */
export interface ApprovalResponse {
  id: string;
  mail_account_id: string;
  function_type: string;
  mail_uid: string;
  mail_subject: string;
  mail_from: string;
  proposed_action: ApprovalResponseProposedAction;
  edited_actions?: ApprovalResponseEditedActions;
  ai_reasoning: string;
  status: string;
  created_at: string;
  resolved_at: string | null;
  expires_at: string;
}
