/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ApprovalResponse } from './approvalResponse';

/**
 * Paginated list of approvals.
 */
export interface ApprovalListResponse {
  items: ApprovalResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
