/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for updating the pause state.
 */
export interface AppSchemasMailAccountPauseUpdate {
  /** Whether the account should be paused */
  paused: boolean;
  /**
     * Reason for pausing
     * @maxLength 200
     */
  pause_reason?: string;
}
