/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for assigning an email address to a contact.
 */
export interface AssignEmailRequest {
  /**
     * Email address to assign
     * @maxLength 320
     */
  email_address: string;
}
