/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response after assigning an email to a contact.
 */
export interface AssignEmailResponse {
  contact_id: string;
  email_address: string;
  /** Whether CardDAV write-back was triggered */
  writeback_triggered: boolean;
}
