/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { AutoReplyRecordResponse } from './autoReplyRecordResponse';

/**
 * Paginated list of auto-reply records.
 */
export interface AutoReplyRecordListResponse {
  items: AutoReplyRecordResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
