/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for an auto-reply record.
 */
export interface AutoReplyRecordResponse {
  id: string;
  mail_account_id: string;
  mail_uid: string;
  mail_subject?: string | null;
  mail_from?: string | null;
  draft_body: string;
  tone?: string | null;
  reasoning?: string | null;
  created_at: string;
  updated_at: string;
}
