/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for a blocklist entry.
 */
export interface BlocklistEntryResponse {
  id: string;
  entry_type: string;
  value: string;
  source: string;
  source_mail_uid: string | null;
  created_at: string;
}
