/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request for bulk approve/reject of approvals.
 */
export interface BulkApprovalRequest {
  /**
     * @minItems 1
     * @maxItems 100
     */
  ids: string[];
  /** 'approve' or 'reject' */
  action: string;
}
