/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Additional info like discovered URLs
 */
export type CalDAVTestResponseDetails = { [key: string]: unknown } | null;
