/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for CalDAV configuration (credentials hidden).
 */
export interface CalDAVConfigResponse {
  id: string;
  caldav_url: string;
  default_calendar: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
