/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { CalDAVTestResponseDetails } from './calDAVTestResponseDetails';

/**
 * Result of a CalDAV connectivity test.
 */
export interface CalDAVTestResponse {
  success: boolean;
  message: string;
  calendars?: string[];
  /** Additional info like discovered URLs */
  details?: CalDAVTestResponseDetails;
}
