/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to test CalDAV connectivity.

Accepts credentials directly so the connection can be tested
before saving configuration. All fields are optional — when
omitted the stored config is used instead.
 */
export interface CalDAVTestRequest {
  caldav_url?: string | null;
  username?: string | null;
  password?: string | null;
  /**
     * Calendar to validate (optional)
     * @maxLength 255
     */
  default_calendar?: string;
}
