/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Create or update CalDAV configuration.
 */
export interface CalDAVConfigUpdate {
  /** @maxLength 500 */
  caldav_url: string;
  /** @maxLength 200 */
  username: string;
  /** @maxLength 500 */
  password: string;
  /** @maxLength 255 */
  default_calendar: string;
}
