/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for a calendar event record.
 */
export interface CalendarEventResponse {
  id: string;
  mail_account_id: string;
  mail_uid: string;
  mail_subject?: string | null;
  mail_from?: string | null;
  title: string;
  start?: string | null;
  end?: string | null;
  location?: string | null;
  description?: string | null;
  is_all_day: boolean;
  caldav_synced: boolean;
  caldav_error?: string | null;
  created_at: string;
  updated_at: string;
}
