/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { CalendarEventResponse } from './calendarEventResponse';

/**
 * Paginated list of calendar events.
 */
export interface CalendarEventListResponse {
  items: CalendarEventResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
