/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Update schema for editing a calendar event.
 */
export interface CalendarEventUpdate {
  title?: string | null;
  start?: string | null;
  end?: string | null;
  location?: string | null;
  description?: string | null;
  is_all_day?: boolean | null;
}
