/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for CardDAV configuration (credentials never returned).
 */
export interface CardDAVConfigResponse {
  id: string;
  carddav_url: string;
  address_book: string;
  sync_interval: number;
  last_sync_at: string | null;
  is_active: boolean;
}
