/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { CardDAVTestResultDetails } from './cardDAVTestResultDetails';

/**
 * Result of testing a CardDAV connection.
 */
export interface CardDAVTestResult {
  success: boolean;
  message: string;
  /** Additional info like discovered address books */
  details?: CardDAVTestResultDetails;
}
