/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for creating/updating CardDAV configuration.
 */
export interface CardDAVConfigCreate {
  /**
     * CardDAV server URL (HTTPS only)
     * @maxLength 500
     */
  carddav_url: string;
  /** @maxLength 255 */
  username: string;
  /**
     * CardDAV password (write-only)
     * @maxLength 500
     */
  password: string;
  /**
     * Address book name/path
     * @maxLength 255
     */
  address_book: string;
  /**
     * Sync interval in minutes
     * @minimum 5
     * @maximum 1440
     */
  sync_interval?: number;
}
