/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for testing a CardDAV connection.
 */
export interface CardDAVTestRequest {
  /** @maxLength 500 */
  carddav_url: string;
  /** @maxLength 255 */
  username: string;
  /** @maxLength 500 */
  password: string;
  /**
     * Address book name/path to validate (optional)
     * @maxLength 255
     */
  address_book?: string;
}
