/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Additional info like discovered address books
 */
export type CardDAVTestResultDetails = { [key: string]: unknown } | null;
