/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { FieldOperator } from './fieldOperator';

/**
 * A single field comparison rule within a condition group.
 */
export interface ConditionRule {
  /** Mail field to evaluate. Supported: from, to, cc, subject, body, has_attachment, attachment_name, date, size, header:<name>, contact_name, contact_org, is_reply, is_forwarded */
  field: string;
  op: FieldOperator;
  /** Comparison value. Not required for is_empty / is_not_empty. */
  value?: unknown;
}
