/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ConditionOperator } from './conditionOperator';
import type { ConditionRule } from './conditionRule';

/**
 * Nested AND/OR condition group.

Contains either leaf-level ``ConditionRule`` items or nested ``ConditionGroup``
items (but not both at the same time in a single list entry -- the discriminator
is the presence of the ``operator`` key).
 */
export interface ConditionGroup {
  operator: ConditionOperator;
  /**
     * @minItems 1
     * @maxItems 20
     */
  rules: (ConditionRule | ConditionGroup)[];
}
