/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to extract contact info from emails by a sender.
 */
export interface ContactExtractRequest {
  /**
     * Sender email address to extract contact info from
     * @maxLength 320
     */
  sender_email: string;
}
