/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for a cached contact.
 */
export interface ContactResponse {
  id: string;
  display_name: string;
  first_name: string | null;
  last_name: string | null;
  emails: string[];
  phones: string[] | null;
  organization: string | null;
  title: string | null;
  photo_url: string | null;
  synced_at: string;
  created_at: string;
}
