/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to manually create a local contact.
 */
export interface ContactCreateRequest {
  /**
     * @minLength 1
     * @maxLength 255
     */
  display_name: string;
  first_name?: string | null;
  last_name?: string | null;
  emails?: string[];
  phones?: string[] | null;
  organization?: string | null;
  title?: string | null;
}
