/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for a contact assignment record.
 */
export interface ContactAssignmentResponse {
  id: string;
  mail_account_id: string;
  mail_uid: string;
  mail_subject?: string | null;
  mail_from?: string | null;
  contact_id?: string | null;
  contact_name: string;
  confidence: number;
  reasoning?: string | null;
  is_new_contact_suggestion: boolean;
  created_at: string;
}
