/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ContactAssignmentResponse } from './contactAssignmentResponse';

/**
 * Paginated response for listing mails associated with a contact.
 */
export interface ContactMailsResponse {
  items: ContactAssignmentResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
