/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Estimated cost for a re-processing run.
 */
export interface CostEstimate {
  estimated_mails: number;
  estimated_llm_calls: number;
  estimated_tokens: number;
  scope_description: string;
}
