/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Update schema for marking a coupon as used/unused.
 */
export interface CouponUpdate {
  is_used: boolean;
}
