/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Confirmation of a manually triggered cron job.
 */
export interface CronTriggerResponse {
  status: string;
  job_id: string;
}
