/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { CronJobInfo } from './cronJobInfo';

/**
 * List of all cron jobs with their current status.
 */
export interface CronJobsResponse {
  jobs: CronJobInfo[];
  /** Current cron interval in minutes (from CRON_INTERVAL_MINUTES env var) */
  interval_minutes: number;
}
