/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status information for a single ARQ cron job.
 */
export interface CronJobInfo {
  /** Internal cron function name */
  name: string;
  /** Human-readable name */
  display_name: string;
  /** What this cron job does */
  description: string;
  /** Human-readable schedule description */
  schedule: string;
  /** ISO timestamp of last successful run */
  last_run?: string | null;
  /** Whether this cron is currently executing */
  is_running?: boolean;
}
