/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * A mail account with a recent error.
 */
export interface DashboardErrorItem {
  account_id: string;
  account_name: string;
  error: string;
  error_at?: string | null;
  consecutive_errors?: number;
  is_active?: boolean;
}
