/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export type DeleteImapFolderApiMailAccountsAccountIdFoldersFolderPathDeleteParams = {
/**
 * Move all emails to INBOX before deleting the folder
 */
move_to_inbox?: boolean;
};
