/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { DetectedNewsletterResponse } from './detectedNewsletterResponse';

/**
 * Paginated list of detected newsletters.
 */
export interface DetectedNewsletterListResponse {
  items: DetectedNewsletterResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
