/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for an email summary.
 */
export interface EmailSummaryResponse {
  id: string;
  mail_account_id: string;
  mail_uid: string;
  mail_subject?: string | null;
  mail_from?: string | null;
  mail_date?: string | null;
  summary: string;
  key_points: string[];
  urgency: string;
  action_required: boolean;
  action_description: string | null;
  notified: boolean;
  created_at: string;
}
