/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { EmailSummaryResponse } from './emailSummaryResponse';

/**
 * Paginated list of email summaries.
 */
export interface EmailSummaryListResponse {
  items: EmailSummaryResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
