/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Classification of processing errors on tracked emails.
 */
export type ErrorType = typeof ErrorType[keyof typeof ErrorType];


export const ErrorType = {
  provider_imap: 'provider_imap',
  provider_ai: 'provider_ai',
  mail: 'mail',
  timeout: 'timeout',
} as const;
