/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for an extracted coupon.
 */
export interface ExtractedCouponResponse {
  id: string;
  mail_account_id: string;
  mail_uid: string;
  sender_email?: string | null;
  mail_subject?: string | null;
  code?: string | null;
  description?: string | null;
  store?: string | null;
  expires_at?: string | null;
  valid_from?: string | null;
  is_used: boolean;
  created_at: string;
  updated_at: string;
}
