/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for an extracted OTP code.
 */
export interface ExtractedOtpCodeResponse {
  id: string;
  mail_account_id: string;
  mail_uid: string;
  sender_email?: string | null;
  mail_subject?: string | null;
  code: string;
  description?: string | null;
  service?: string | null;
  code_type: string;
  url?: string | null;
  expires_at?: string | null;
  is_expired: boolean;
  created_at: string;
  updated_at: string;
}
