/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedOtpCodeResponse } from './extractedOtpCodeResponse';

/**
 * Paginated list of extracted OTP codes.
 */
export interface ExtractedOtpCodeListResponse {
  items: ExtractedOtpCodeResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
