/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedCouponResponse } from './extractedCouponResponse';

/**
 * Paginated list of extracted coupons.
 */
export interface ExtractedCouponListResponse {
  items: ExtractedCouponResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
