/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Confirmation of a failed-mail retry or resolve action.
 */
export interface FailedMailActionResponse {
  status: string;
  tracked_email_id: string;
}
