/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for renaming an IMAP folder.
 */
export interface FolderRenameRequest {
  /**
     * @minLength 1
     * @maxLength 500
     */
  old_name: string;
  /**
     * @minLength 1
     * @maxLength 500
     */
  new_name: string;
}
