/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Confirmation of IMAP folder rename.
 */
export interface FolderRenamedResponse {
  status: string;
  old_name: string;
  new_name: string;
}
