/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { FolderSummary } from './folderSummary';

/**
 * List of unique folders with counts.
 */
export interface FolderSummaryListResponse {
  items: FolderSummary[];
  total: number;
}
