/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export type GetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet200 = { [key: string]: unknown };
