/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export type GetJobQueueStatusApiDashboardJobsGetParams = {
/**
 * @minimum 1
 */
queue_page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
queue_per_page?: number;
};
