/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { FolderInfo } from './folderInfo';

/**
 * IMAP folder listing with hierarchy separator and excluded folders.
 */
export interface ImapFolderListResponse {
  folders: FolderInfo[] | string[];
  separator: string;
  excluded_folders?: string[];
}
