/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * An ARQ job currently being processed.
 */
export interface InProgressJob {
  job_id: string;
  function: string;
  mail_uid?: string | null;
  account_id?: string | null;
  phase?: string | null;
  current_plugin?: string | null;
  current_plugin_display?: string | null;
  plugin_index?: number | null;
  plugins_total?: number | null;
}
