/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Confirmation that a job was enqueued.
 */
export interface JobEnqueuedResponse {
  status: string;
  job_id?: string | null;
}
