/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { InProgressJob } from './inProgressJob';
import type { QueuedJob } from './queuedJob';

/**
 * ARQ job queue depth, in-progress job details, and DB-based completion metrics.
 */
export interface JobQueueStatusResponse {
  /** Mails waiting to be processed (DB status 'queued') */
  queued?: number;
  /** Total jobs in the ARQ queue (all types, for debugging) */
  queued_total?: number;
  /** Mail jobs currently being processed (IMAP fetch, AI pipeline, etc.) */
  in_progress?: number;
  /** System/cron jobs currently in progress (polling, scheduling, etc.) */
  in_progress_system?: number;
  in_progress_jobs?: InProgressJob[];
  queued_jobs?: QueuedJob[];
  queue_page?: number;
  queue_pages?: number;
  /** Transient Valkey result count (TTL-based, for debugging) */
  results_stored?: number;
  /** Total completed mails from DB (persistent) */
  completed_total?: number;
  /** Mails completed in the last 24 hours */
  completed_today?: number;
  /** Mails completed in the last hour */
  completed_last_hour?: number;
  /** Total failed mails from DB (persistent) */
  failed_total?: number;
  error?: string | null;
}
