/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { LabelSummary } from './labelSummary';

/**
 * List of unique labels with counts.
 */
export interface LabelSummaryListResponse {
  items: LabelSummary[];
  total: number;
}
