/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export type ListFoldersApiMailAccountsAccountIdFoldersGetParams = {
/**
 * Include message counts per folder
 */
counts?: boolean;
};
