/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ListNewslettersApiNewslettersGetSort } from './listNewslettersApiNewslettersGetSort';

export type ListNewslettersApiNewslettersGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
sender?: string | null;
/**
 * Sort order
 */
sort?: ListNewslettersApiNewslettersGetSort;
};
