/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export type ListAssignedFoldersApiFoldersGetSort = typeof ListAssignedFoldersApiFoldersGetSort[keyof typeof ListAssignedFoldersApiFoldersGetSort];


export const ListAssignedFoldersApiFoldersGetSort = {
  newest: 'newest',
  oldest: 'oldest',
  folder: 'folder',
} as const;
