/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorType } from './errorType';
import type { TrackedEmailStatus } from './trackedEmailStatus';

export type ListQueueApiQueueGetParams = {
/**
 * Filter by processing status
 */
status?: TrackedEmailStatus | null;
/**
 * Filter by mail account
 */
account_id?: string | null;
/**
 * Filter by error type
 */
error_type?: ErrorType | null;
/**
 * Search by subject or sender
 */
q?: string | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
};
