/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ApprovalStatus } from './approvalStatus';
import type { ListApprovalsApiApprovalsGetSort } from './listApprovalsApiApprovalsGetSort';

export type ListApprovalsApiApprovalsGetParams = {
/**
 * Filter by status
 */
status?: ApprovalStatus | null;
/**
 * Filter by plugin type
 */
function_type?: string | null;
/**
 * Search by subject or sender
 */
search?: string | null;
/**
 * Sort order
 */
sort?: ListApprovalsApiApprovalsGetSort;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
per_page?: number;
};
