/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ListCalendarEventsApiCalendarEventsGetSort } from './listCalendarEventsApiCalendarEventsGetSort';

export type ListCalendarEventsApiCalendarEventsGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
search?: string | null;
/**
 * Sort order
 */
sort?: ListCalendarEventsApiCalendarEventsGetSort;
};
