/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ListAppliedLabelsApiLabelsGetSort } from './listAppliedLabelsApiLabelsGetSort';

export type ListAppliedLabelsApiLabelsGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
label?: string | null;
/**
 * Sort order
 */
sort?: ListAppliedLabelsApiLabelsGetSort;
};
