/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export type ListOtpCodesApiOtpCodesGetSort = typeof ListOtpCodesApiOtpCodesGetSort[keyof typeof ListOtpCodesApiOtpCodesGetSort];


export const ListOtpCodesApiOtpCodesGetSort = {
  newest: 'newest',
  oldest: 'oldest',
  service: 'service',
  expiry: 'expiry',
} as const;
