/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ListCouponsApiCouponsGetSort } from './listCouponsApiCouponsGetSort';

export type ListCouponsApiCouponsGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
store?: string | null;
active_only?: boolean;
/**
 * Sort order
 */
sort?: ListCouponsApiCouponsGetSort;
};
