/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export type ListRulesApiRulesGetParams = {
/**
 * Filter by account
 */
mail_account_id?: string | null;
/**
 * Filter by active status
 */
is_active?: boolean | null;
};
