/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for creating a mail account.
 */
export interface MailAccountCreate {
  /**
     * Display name (e.g. 'Work', 'Private')
     * @maxLength 100
     */
  name: string;
  /**
     * Email address for this account
     * @maxLength 320
     */
  email_address: string;
  /** @maxLength 255 */
  imap_host: string;
  /**
     * @minimum 1
     * @maximum 65535
     */
  imap_port?: number;
  imap_use_ssl?: boolean;
  /**
     * IMAP username
     * @maxLength 255
     */
  username: string;
  /**
     * IMAP password (write-only)
     * @maxLength 500
     */
  password: string;
  polling_enabled?: boolean;
  /**
     * @minimum 1
     * @maximum 60
     */
  polling_interval_minutes?: number;
  idle_enabled?: boolean;
  /** If true, index existing emails from all folders on first sync. Otherwise only new incoming mail is processed. */
  scan_existing_emails?: boolean;
  /** IMAP folders to skip during analysis */
  excluded_folders?: string[] | null;
}
