/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for updating a mail account.
 */
export interface MailAccountUpdate {
  name?: string | null;
  email_address?: string | null;
  imap_host?: string | null;
  imap_port?: number | null;
  imap_use_ssl?: boolean | null;
  username?: string | null;
  password?: string | null;
  polling_enabled?: boolean | null;
  polling_interval_minutes?: number | null;
  idle_enabled?: boolean | null;
  scan_existing_emails?: boolean | null;
  excluded_folders?: string[] | null;
}
