/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { MissingSummaryItem } from './missingSummaryItem';

/**
 * Paginated list of completed mails that lack an email summary.
 */
export interface MissingSummaryListResponse {
  items: MissingSummaryItem[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
