/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { NLRuleResponseActionsItem } from './nLRuleResponseActionsItem';
import type { NLRuleResponseConditions } from './nLRuleResponseConditions';

/**
 * AI-generated structured rule from natural language (not auto-saved).
 */
export interface NLRuleResponse {
  name: string;
  description?: string | null;
  conditions: NLRuleResponseConditions;
  actions: NLRuleResponseActionsItem[];
  stop_processing?: boolean;
  /** Explanation of the AI's interpretation. */
  ai_reasoning?: string | null;
}
