/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request for natural-language to structured rule translation.
 */
export interface NLRuleRequest {
  /**
     * Natural language rule description.
     * @minLength 5
     * @maxLength 2000
     */
  description: string;
  /** Optional account scope for context. */
  mail_account_id?: string | null;
}
