/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result of a test notification.
 */
export interface NotificationTestResponse {
  success: boolean;
  message: string;
}
