/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationConfigUpdateTemplates } from './notificationConfigUpdateTemplates';
import type { NotifyOnConfig } from './notifyOnConfig';

/**
 * Update schema for notification configuration.
 */
export interface NotificationConfigUpdate {
  apprise_urls?: string[] | null;
  templates?: NotificationConfigUpdateTemplates;
  notify_on?: NotifyOnConfig;
}
