/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to add a new Apprise URL.
 */
export interface NotificationUrlAdd {
  /**
     * @minLength 1
     * @maxLength 1000
     */
  url: string;
}
