/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationConfigResponseNotifyOn } from './notificationConfigResponseNotifyOn';
import type { NotificationConfigResponseTemplates } from './notificationConfigResponseTemplates';

/**
 * Response schema for notification configuration.
 */
export interface NotificationConfigResponse {
  id: string;
  apprise_urls: string[];
  templates: NotificationConfigResponseTemplates;
  notify_on: NotificationConfigResponseNotifyOn;
  updated_at: string;
}
