/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to preview a rendered notification template.
 */
export interface NotificationPreviewRequest {
  /** @maxLength 10000 */
  template: string;
  /** @maxLength 100 */
  event_type: string;
}
