/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to send a test notification.
 */
export interface NotificationTestRequest {
  /** @maxLength 500 */
  message?: string;
}
