/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Rendered notification template preview.
 */
export interface NotificationPreviewResponse {
  rendered: string;
  errors?: string[];
}
