/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export type PauseAccountApiMailAccountsAccountIdPausePostParams = {
/**
 * Reason for pausing
 * @maxLength 200
 */
reason?: string;
};
