/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Input for testing the AI processing pipeline with sample email data.
 */
export interface PipelineTestRequest {
  /**
     * Sender email address
     * @maxLength 320
     */
  sender?: string;
  /**
     * Sender display name
     * @maxLength 200
     */
  sender_name?: string;
  /**
     * Recipient email address
     * @maxLength 320
     */
  recipient?: string;
  /**
     * Email subject
     * @maxLength 998
     */
  subject?: string;
  /**
     * Email body (plain text)
     * @maxLength 50000
     */
  body?: string;
  /** Email date (ISO format). Defaults to current time. */
  date?: string;
  /** Whether the email has attachments */
  has_attachments?: boolean;
  /** Whether this is a reply */
  is_reply?: boolean;
  /** Whether this is a forwarded email */
  is_forwarded?: boolean;
}
