/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Summary of a single plugin's execution result.
 */
export interface PluginResultEntry {
  status: string;
  display_name: string;
  summary?: string | null;
  details?: Record<string, unknown> | null;
}
