/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata about an available AI function plugin.
 */
export interface PluginInfo {
  name: string;
  display_name: string;
  description: string;
  execution_order: number;
  default_prompt_template: string;
  icon?: string;
  has_view_page?: boolean;
  view_route?: string | null;
  has_config_page?: boolean;
  config_route?: string | null;
  approval_key?: string;
  supports_approval?: boolean;
  runs_in_pipeline?: boolean;
}
