/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response with the rendered prompt and any validation errors.
 */
export interface PromptPreviewResponse {
  rendered_system: string;
  rendered_user: string | null;
  errors: string[];
}
