/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for previewing a rendered prompt with sample data.
 */
export interface PromptPreviewRequest {
  /**
     * @minLength 1
     * @maxLength 50000
     */
  system_prompt: string;
  user_prompt?: string | null;
}
