/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for a prompt template.
 */
export interface PromptResponse {
  id?: string | null;
  function_type: string;
  system_prompt: string;
  user_prompt: string | null;
  is_custom: boolean;
  created_at?: string | null;
  updated_at?: string | null;
}
