/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * A job waiting in the ARQ queue.
 */
export interface QueuedJob {
  job_id: string;
  function: string;
  mail_uid?: string | null;
  account_id?: string | null;
}
