/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single label or folder change action.
 */
export interface RecentActionItem {
  id: string;
  /** Either 'label_change' or 'folder_change' */
  type: string;
  mail_account_id: string;
  detail: string;
  created_at?: string | null;
}
