/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { RecentActionItem } from './recentActionItem';

/**
 * Paginated list of recent AI actions (label + folder changes).
 */
export interface RecentActionsResponse {
  items: RecentActionItem[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
