/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response after removing an email from a contact.
 */
export interface RemoveEmailResponse {
  contact_id: string;
  email_address: string;
  /** Whether CardDAV write-back was triggered */
  writeback_triggered: boolean;
}
