/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * A single rule ID + new priority for bulk reorder.
 */
export interface ReorderItem {
  id: string;
  /** @minimum 0 */
  priority: number;
}
