/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ReorderItem } from './reorderItem';

/**
 * Bulk reorder request.
 */
export interface ReorderRequest {
  /**
     * @minItems 1
     * @maxItems 200
     */
  rules: ReorderItem[];
}
