/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for manually triggering a re-processing job.
 */
export interface ReprocessingTriggerRequest {
  mail_account_id: string;
  /** 'labeling', 'smart_folder', or 'both' */
  job_type: string;
  date_from?: string | null;
  date_to?: string | null;
  folders?: string[] | null;
  max_mails?: number | null;
}
