/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for triggering a reprocess run.
 */
export interface ReprocessRequest {
  /** Account whose mails to reprocess */
  mail_account_id: string;
  /**
     * Reprocess completed mails from the last N days
     * @minimum 1
     * @maximum 365
     */
  scope_days?: number;
  /** Maximum number of mails to reprocess (oldest first within scope) */
  max_mails?: number | null;
}
