/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ReprocessingJobResponse } from './reprocessingJobResponse';

/**
 * Paginated list of re-processing jobs.
 */
export interface ReprocessingJobListResponse {
  items: ReprocessingJobResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
