/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response schema for re-processing cron configuration.
 */
export interface ReprocessingConfigResponse {
  id?: string | null;
  is_enabled: boolean;
  cron_schedule: string;
  scope_days: number;
  max_mails_per_run: number;
  reprocess_labeling: boolean;
  reprocess_smart_folder: boolean;
  created_at?: string | null;
  updated_at?: string | null;
}
