/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ReprocessingJobResponseScope } from './reprocessingJobResponseScope';

/**
 * Response schema for a re-processing job.
 */
export interface ReprocessingJobResponse {
  id: string;
  mail_account_id: string;
  job_type: string;
  trigger: string;
  scope: ReprocessingJobResponseScope;
  status: string;
  total_mails: number | null;
  processed_mails: number;
  changed_mails: number;
  token_usage: number;
  started_at: string | null;
  completed_at: string | null;
  error: string | null;
  created_at: string;
  updated_at: string;
}
