/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result of a reprocess trigger.
 */
export interface ReprocessResponse {
  /** Number of mails set back to pending */
  reset_count: number;
}
