/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request schema for updating re-processing cron configuration.
 */
export interface ReprocessingConfigUpdate {
  is_enabled?: boolean | null;
  cron_schedule?: string | null;
  scope_days?: number | null;
  max_mails_per_run?: number | null;
  reprocess_labeling?: boolean | null;
  reprocess_smart_folder?: boolean | null;
}
