/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { RuleResponse } from './ruleResponse';

/**
 * Paginated list of rules.
 */
export interface RuleListResponse {
  items: RuleResponse[];
  total: number;
  page?: number;
  per_page?: number;
  pages?: number;
}
