/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ConditionGroup } from './conditionGroup';
import type { RuleAction } from './ruleAction';

/**
 * Request body for creating a new rule.
 */
export interface RuleCreate {
  /** Scope to a specific account. null = all accounts. */
  mail_account_id?: string | null;
  /**
     * @minLength 1
     * @maxLength 200
     */
  name: string;
  description?: string | null;
  /**
     * Lower number = evaluated first
     * @minimum 0
     */
  priority: number;
  is_active?: boolean;
  conditions: ConditionGroup;
  /** @minItems 1 */
  actions: RuleAction[];
  stop_processing?: boolean;
}
