/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { RuleResponseActionsItem } from './ruleResponseActionsItem';
import type { RuleResponseConditions } from './ruleResponseConditions';

/**
 * Response schema for a rule.
 */
export interface RuleResponse {
  id: string;
  user_id: string;
  mail_account_id: string | null;
  name: string;
  description: string | null;
  priority: number;
  is_active: boolean;
  conditions: RuleResponseConditions;
  actions: RuleResponseActionsItem[];
  stop_processing: boolean;
  match_count: number;
  last_matched_at: string | null;
  created_at: string;
  updated_at: string;
}
