/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ApprovalModesUpdate } from './approvalModesUpdate';
import type { SettingsUpdatePluginProviderMap } from './settingsUpdatePluginProviderMap';

/**
 * Update schema for user settings (partial update).
 */
export interface SettingsUpdate {
  timezone?: string | null;
  language?: string | null;
  default_polling_interval_minutes?: number | null;
  draft_expiry_hours?: number | null;
  /** Max mails in PROCESSING status simultaneously (1-20) */
  max_concurrent_processing?: number | null;
  /** Global LLM timeout in seconds (10-600). Per-provider overrides take precedence. */
  ai_timeout_seconds?: number | null;
  approval_modes?: ApprovalModesUpdate | null;
  plugin_order?: string[] | null;
  plugin_provider_map?: SettingsUpdatePluginProviderMap;
}
