/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { ApprovalModes } from './approvalModes';
import type { SettingsResponsePluginProviderMap } from './settingsResponsePluginProviderMap';

/**
 * Response schema for user settings.
 */
export interface SettingsResponse {
  id: string;
  timezone: string;
  language: string;
  default_polling_interval_minutes: number;
  draft_expiry_hours: number;
  max_concurrent_processing: number;
  ai_timeout_seconds: number;
  approval_modes: ApprovalModes;
  plugin_order?: string[] | null;
  plugin_provider_map?: SettingsResponsePluginProviderMap;
  updated_at: string;
}
