/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-account result of a smart folder reset operation.
 */
export interface SmartFolderResetAccountResult {
  account_id: string;
  account_name: string;
  moved_to_inbox?: number | null;
  imap_folder_deleted?: boolean | null;
  error?: string | null;
}
