/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Summary of a reprocess-in-place operation.
 */
export interface SmartFolderReprocessResponse {
  folder: string;
  requeued_emails: number;
}
