/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { SmartFolderResetAccountResult } from './smartFolderResetAccountResult';

/**
 * Summary of a full smart folder reset operation.
 */
export interface SmartFolderResetResponse {
  folder: string;
  accounts: SmartFolderResetAccountResult[];
  deleted_assigned_folders: number;
  deleted_folder_change_logs: number;
  reset_tracked_emails: number;
}
