/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to report a mail as spam.
 */
export interface SpamReportRequest {
  /**
     * IMAP UID of the mail to report
     * @maxLength 100
     */
  mail_id: string;
  /** Mail account the message belongs to */
  mail_account_id: string;
  /**
     * Sender email address
     * @maxLength 320
     */
  sender_email: string;
  /** Email subject for pattern extraction */
  subject?: string | null;
}
