/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result of reporting something as spam.
 */
export interface SpamReportResult {
  /** Number of new blocklist entries created */
  blocked_entries_created: number;
  /** Whether the mail was moved to spam folder */
  mail_moved: boolean;
  message: string;
}
