/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to report a contact as spam (block all their emails).
 */
export interface SpamReportContactRequest {
  /** Contact to block */
  contact_id: string;
}
