/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Filter rules for summary notification forwarding.
 */
export interface SummaryFilterRules {
  labels?: string[] | null;
  folders?: string[] | null;
  from_contacts_only?: boolean;
  /** @pattern ^(low|medium|high|critical)$ */
  min_urgency?: string;
  action_required_only?: boolean;
  exclude_spam?: boolean;
}
