/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata about an available template variable.
 */
export interface TemplateVariable {
  name: string;
  var_type: string;
  description: string;
  example: string;
}
