/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { TestRuleResultActionsThatWouldExecuteItem } from './testRuleResultActionsThatWouldExecuteItem';

/**
 * Result of testing a rule against sample mail data.
 */
export interface TestRuleResult {
  matched: boolean;
  actions_that_would_execute: TestRuleResultActionsThatWouldExecuteItem[];
  /** Human-readable trace of condition evaluation. */
  evaluation_details?: string | null;
}
