/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { CompletionReason } from './completionReason';
import type { ErrorType } from './errorType';
import type { PluginResultEntry } from './pluginResultEntry';
import type { TrackedEmailStatus } from './trackedEmailStatus';

/**
 * Response schema for a single tracked email in the processing queue.
 */
export interface TrackedEmailResponse {
  id: string;
  mail_uid: string;
  subject?: string | null;
  sender?: string | null;
  received_at?: string | null;
  status: TrackedEmailStatus;
  error_type?: ErrorType | null;
  last_error?: string | null;
  plugins_completed?: string[] | null;
  plugins_failed?: string[] | null;
  plugins_skipped?: string[] | null;
  plugin_results?: Record<string, PluginResultEntry> | null;
  completion_reason?: CompletionReason | null;
  current_folder: string;
  mail_account_id: string;
  retry_count: number;
  created_at: string;
  updated_at: string;
}
