/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import type { TrackedEmailResponse } from './trackedEmailResponse';

/**
 * Paginated list of tracked emails.
 */
export interface TrackedEmailListResponse {
  items: TrackedEmailResponse[];
  total: number;
  page: number;
  per_page: number;
  pages: number;
}
