/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * Processing status for a tracked email.
 */
export type TrackedEmailStatus = typeof TrackedEmailStatus[keyof typeof TrackedEmailStatus];


export const TrackedEmailStatus = {
  queued: 'queued',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;
