/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

/**
 * A unique sender address not yet matched to a contact.
 */
export interface UnmatchedSenderResponse {
  email_address: string;
  /** Number of mails from this sender */
  mail_count: number;
}
