/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}
