/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DefaultTemplateResponse,
  HTTPValidationError,
  NotificationConfigResponse,
  NotificationConfigUpdate,
  NotificationPreviewRequest,
  NotificationPreviewResponse,
  NotificationTestRequest,
  NotificationTestResponse,
  NotificationUrlAdd,
  TemplateVariable
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get the notification configuration for the current user.

Returns default empty config if none exists.
Apprise URLs are masked for security (they may contain tokens/passwords).
 * @summary Get Config
 */
export type getConfigApiNotificationsConfigGetResponse200 = {
  data: NotificationConfigResponse
  status: 200
}

export type getConfigApiNotificationsConfigGetResponseSuccess = (getConfigApiNotificationsConfigGetResponse200) & {
  headers: Headers;
};
;

export type getConfigApiNotificationsConfigGetResponse = (getConfigApiNotificationsConfigGetResponseSuccess)

export const getGetConfigApiNotificationsConfigGetUrl = () => {




  return `/api/notifications/config`
}

export const getConfigApiNotificationsConfigGet = async ( options?: RequestInit): Promise<getConfigApiNotificationsConfigGetResponse> => {

  return customInstance<getConfigApiNotificationsConfigGetResponse>(getGetConfigApiNotificationsConfigGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConfigApiNotificationsConfigGetQueryKey = () => {
    return [
    `/api/notifications/config`
    ] as const;
    }


export const getGetConfigApiNotificationsConfigGetQueryOptions = <TData = Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConfigApiNotificationsConfigGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>> = ({ signal }) => getConfigApiNotificationsConfigGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConfigApiNotificationsConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>>
export type GetConfigApiNotificationsConfigGetQueryError = unknown


export function useGetConfigApiNotificationsConfigGet<TData = Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>,
          TError,
          Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigApiNotificationsConfigGet<TData = Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>,
          TError,
          Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigApiNotificationsConfigGet<TData = Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Config
 */

export function useGetConfigApiNotificationsConfigGet<TData = Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiNotificationsConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConfigApiNotificationsConfigGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update notification configuration (templates and notify_on only).

Apprise URLs are managed via dedicated add/remove endpoints.
 * @summary Update Config
 */
export type updateConfigApiNotificationsConfigPutResponse200 = {
  data: NotificationConfigResponse
  status: 200
}

export type updateConfigApiNotificationsConfigPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateConfigApiNotificationsConfigPutResponseSuccess = (updateConfigApiNotificationsConfigPutResponse200) & {
  headers: Headers;
};
export type updateConfigApiNotificationsConfigPutResponseError = (updateConfigApiNotificationsConfigPutResponse422) & {
  headers: Headers;
};

export type updateConfigApiNotificationsConfigPutResponse = (updateConfigApiNotificationsConfigPutResponseSuccess | updateConfigApiNotificationsConfigPutResponseError)

export const getUpdateConfigApiNotificationsConfigPutUrl = () => {




  return `/api/notifications/config`
}

export const updateConfigApiNotificationsConfigPut = async (notificationConfigUpdate: NotificationConfigUpdate, options?: RequestInit): Promise<updateConfigApiNotificationsConfigPutResponse> => {

  return customInstance<updateConfigApiNotificationsConfigPutResponse>(getUpdateConfigApiNotificationsConfigPutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      notificationConfigUpdate,)
  }
);}




export const getUpdateConfigApiNotificationsConfigPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConfigApiNotificationsConfigPut>>, TError,{data: NotificationConfigUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateConfigApiNotificationsConfigPut>>, TError,{data: NotificationConfigUpdate}, TContext> => {

const mutationKey = ['updateConfigApiNotificationsConfigPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateConfigApiNotificationsConfigPut>>, {data: NotificationConfigUpdate}> = (props) => {
          const {data} = props ?? {};

          return  updateConfigApiNotificationsConfigPut(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateConfigApiNotificationsConfigPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateConfigApiNotificationsConfigPut>>>
    export type UpdateConfigApiNotificationsConfigPutMutationBody = NotificationConfigUpdate
    export type UpdateConfigApiNotificationsConfigPutMutationError = HTTPValidationError

    /**
 * @summary Update Config
 */
export const useUpdateConfigApiNotificationsConfigPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConfigApiNotificationsConfigPut>>, TError,{data: NotificationConfigUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateConfigApiNotificationsConfigPut>>,
        TError,
        {data: NotificationConfigUpdate},
        TContext
      > => {
      return useMutation(getUpdateConfigApiNotificationsConfigPutMutationOptions(options), queryClient);
    }
    /**
 * Add a new Apprise URL to the notification configuration.
 * @summary Add Url
 */
export type addUrlApiNotificationsConfigUrlsPostResponse200 = {
  data: NotificationConfigResponse
  status: 200
}

export type addUrlApiNotificationsConfigUrlsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type addUrlApiNotificationsConfigUrlsPostResponseSuccess = (addUrlApiNotificationsConfigUrlsPostResponse200) & {
  headers: Headers;
};
export type addUrlApiNotificationsConfigUrlsPostResponseError = (addUrlApiNotificationsConfigUrlsPostResponse422) & {
  headers: Headers;
};

export type addUrlApiNotificationsConfigUrlsPostResponse = (addUrlApiNotificationsConfigUrlsPostResponseSuccess | addUrlApiNotificationsConfigUrlsPostResponseError)

export const getAddUrlApiNotificationsConfigUrlsPostUrl = () => {




  return `/api/notifications/config/urls`
}

export const addUrlApiNotificationsConfigUrlsPost = async (notificationUrlAdd: NotificationUrlAdd, options?: RequestInit): Promise<addUrlApiNotificationsConfigUrlsPostResponse> => {

  return customInstance<addUrlApiNotificationsConfigUrlsPostResponse>(getAddUrlApiNotificationsConfigUrlsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      notificationUrlAdd,)
  }
);}




export const getAddUrlApiNotificationsConfigUrlsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addUrlApiNotificationsConfigUrlsPost>>, TError,{data: NotificationUrlAdd}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addUrlApiNotificationsConfigUrlsPost>>, TError,{data: NotificationUrlAdd}, TContext> => {

const mutationKey = ['addUrlApiNotificationsConfigUrlsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addUrlApiNotificationsConfigUrlsPost>>, {data: NotificationUrlAdd}> = (props) => {
          const {data} = props ?? {};

          return  addUrlApiNotificationsConfigUrlsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddUrlApiNotificationsConfigUrlsPostMutationResult = NonNullable<Awaited<ReturnType<typeof addUrlApiNotificationsConfigUrlsPost>>>
    export type AddUrlApiNotificationsConfigUrlsPostMutationBody = NotificationUrlAdd
    export type AddUrlApiNotificationsConfigUrlsPostMutationError = HTTPValidationError

    /**
 * @summary Add Url
 */
export const useAddUrlApiNotificationsConfigUrlsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addUrlApiNotificationsConfigUrlsPost>>, TError,{data: NotificationUrlAdd}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addUrlApiNotificationsConfigUrlsPost>>,
        TError,
        {data: NotificationUrlAdd},
        TContext
      > => {
      return useMutation(getAddUrlApiNotificationsConfigUrlsPostMutationOptions(options), queryClient);
    }
    /**
 * Remove an Apprise URL by index.
 * @summary Remove Url
 */
export type removeUrlApiNotificationsConfigUrlsIndexDeleteResponse200 = {
  data: NotificationConfigResponse
  status: 200
}

export type removeUrlApiNotificationsConfigUrlsIndexDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type removeUrlApiNotificationsConfigUrlsIndexDeleteResponseSuccess = (removeUrlApiNotificationsConfigUrlsIndexDeleteResponse200) & {
  headers: Headers;
};
export type removeUrlApiNotificationsConfigUrlsIndexDeleteResponseError = (removeUrlApiNotificationsConfigUrlsIndexDeleteResponse422) & {
  headers: Headers;
};

export type removeUrlApiNotificationsConfigUrlsIndexDeleteResponse = (removeUrlApiNotificationsConfigUrlsIndexDeleteResponseSuccess | removeUrlApiNotificationsConfigUrlsIndexDeleteResponseError)

export const getRemoveUrlApiNotificationsConfigUrlsIndexDeleteUrl = (index: number,) => {




  return `/api/notifications/config/urls/${index}`
}

export const removeUrlApiNotificationsConfigUrlsIndexDelete = async (index: number, options?: RequestInit): Promise<removeUrlApiNotificationsConfigUrlsIndexDeleteResponse> => {

  return customInstance<removeUrlApiNotificationsConfigUrlsIndexDeleteResponse>(getRemoveUrlApiNotificationsConfigUrlsIndexDeleteUrl(index),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getRemoveUrlApiNotificationsConfigUrlsIndexDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUrlApiNotificationsConfigUrlsIndexDelete>>, TError,{index: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeUrlApiNotificationsConfigUrlsIndexDelete>>, TError,{index: number}, TContext> => {

const mutationKey = ['removeUrlApiNotificationsConfigUrlsIndexDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeUrlApiNotificationsConfigUrlsIndexDelete>>, {index: number}> = (props) => {
          const {index} = props ?? {};

          return  removeUrlApiNotificationsConfigUrlsIndexDelete(index,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveUrlApiNotificationsConfigUrlsIndexDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeUrlApiNotificationsConfigUrlsIndexDelete>>>

    export type RemoveUrlApiNotificationsConfigUrlsIndexDeleteMutationError = HTTPValidationError

    /**
 * @summary Remove Url
 */
export const useRemoveUrlApiNotificationsConfigUrlsIndexDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUrlApiNotificationsConfigUrlsIndexDelete>>, TError,{index: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeUrlApiNotificationsConfigUrlsIndexDelete>>,
        TError,
        {index: number},
        TContext
      > => {
      return useMutation(getRemoveUrlApiNotificationsConfigUrlsIndexDeleteMutationOptions(options), queryClient);
    }
    /**
 * Send a test notification to all configured Apprise URLs.
 * @summary Test Notification
 */
export type testNotificationApiNotificationsTestPostResponse200 = {
  data: NotificationTestResponse
  status: 200
}

export type testNotificationApiNotificationsTestPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type testNotificationApiNotificationsTestPostResponseSuccess = (testNotificationApiNotificationsTestPostResponse200) & {
  headers: Headers;
};
export type testNotificationApiNotificationsTestPostResponseError = (testNotificationApiNotificationsTestPostResponse422) & {
  headers: Headers;
};

export type testNotificationApiNotificationsTestPostResponse = (testNotificationApiNotificationsTestPostResponseSuccess | testNotificationApiNotificationsTestPostResponseError)

export const getTestNotificationApiNotificationsTestPostUrl = () => {




  return `/api/notifications/test`
}

export const testNotificationApiNotificationsTestPost = async (notificationTestRequest: NotificationTestRequest, options?: RequestInit): Promise<testNotificationApiNotificationsTestPostResponse> => {

  return customInstance<testNotificationApiNotificationsTestPostResponse>(getTestNotificationApiNotificationsTestPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      notificationTestRequest,)
  }
);}




export const getTestNotificationApiNotificationsTestPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testNotificationApiNotificationsTestPost>>, TError,{data: NotificationTestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof testNotificationApiNotificationsTestPost>>, TError,{data: NotificationTestRequest}, TContext> => {

const mutationKey = ['testNotificationApiNotificationsTestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testNotificationApiNotificationsTestPost>>, {data: NotificationTestRequest}> = (props) => {
          const {data} = props ?? {};

          return  testNotificationApiNotificationsTestPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestNotificationApiNotificationsTestPostMutationResult = NonNullable<Awaited<ReturnType<typeof testNotificationApiNotificationsTestPost>>>
    export type TestNotificationApiNotificationsTestPostMutationBody = NotificationTestRequest
    export type TestNotificationApiNotificationsTestPostMutationError = HTTPValidationError

    /**
 * @summary Test Notification
 */
export const useTestNotificationApiNotificationsTestPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testNotificationApiNotificationsTestPost>>, TError,{data: NotificationTestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testNotificationApiNotificationsTestPost>>,
        TError,
        {data: NotificationTestRequest},
        TContext
      > => {
      return useMutation(getTestNotificationApiNotificationsTestPostMutationOptions(options), queryClient);
    }
    /**
 * List all template variables available for notification templates.

Returns the 28 base email variables plus 13 notification-specific variables.
 * @summary List Variables
 */
export type listVariablesApiNotificationsVariablesGetResponse200 = {
  data: TemplateVariable[]
  status: 200
}

export type listVariablesApiNotificationsVariablesGetResponseSuccess = (listVariablesApiNotificationsVariablesGetResponse200) & {
  headers: Headers;
};
;

export type listVariablesApiNotificationsVariablesGetResponse = (listVariablesApiNotificationsVariablesGetResponseSuccess)

export const getListVariablesApiNotificationsVariablesGetUrl = () => {




  return `/api/notifications/variables`
}

export const listVariablesApiNotificationsVariablesGet = async ( options?: RequestInit): Promise<listVariablesApiNotificationsVariablesGetResponse> => {

  return customInstance<listVariablesApiNotificationsVariablesGetResponse>(getListVariablesApiNotificationsVariablesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListVariablesApiNotificationsVariablesGetQueryKey = () => {
    return [
    `/api/notifications/variables`
    ] as const;
    }


export const getListVariablesApiNotificationsVariablesGetQueryOptions = <TData = Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVariablesApiNotificationsVariablesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>> = ({ signal }) => listVariablesApiNotificationsVariablesGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVariablesApiNotificationsVariablesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>>
export type ListVariablesApiNotificationsVariablesGetQueryError = unknown


export function useListVariablesApiNotificationsVariablesGet<TData = Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>,
          TError,
          Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVariablesApiNotificationsVariablesGet<TData = Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>,
          TError,
          Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVariablesApiNotificationsVariablesGet<TData = Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Variables
 */

export function useListVariablesApiNotificationsVariablesGet<TData = Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiNotificationsVariablesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVariablesApiNotificationsVariablesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Return the default on-disk Jinja2 template for a given event type.

Falls back to the generic ``default.j2`` for event types without a
dedicated template file.
 * @summary Get Default Template
 */
export type getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponse200 = {
  data: DefaultTemplateResponse
  status: 200
}

export type getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponseSuccess = (getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponse200) & {
  headers: Headers;
};
export type getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponseError = (getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponse422) & {
  headers: Headers;
};

export type getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponse = (getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponseSuccess | getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponseError)

export const getGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetUrl = (eventType: string,) => {




  return `/api/notifications/templates/default/${eventType}`
}

export const getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet = async (eventType: string, options?: RequestInit): Promise<getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponse> => {

  return customInstance<getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetResponse>(getGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetUrl(eventType),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetQueryKey = (eventType: string,) => {
    return [
    `/api/notifications/templates/default/${eventType}`
    ] as const;
    }


export const getGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetQueryOptions = <TData = Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError = HTTPValidationError>(eventType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetQueryKey(eventType);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>> = ({ signal }) => getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet(eventType, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(eventType), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>>
export type GetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetQueryError = HTTPValidationError


export function useGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet<TData = Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError = HTTPValidationError>(
 eventType: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>,
          TError,
          Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet<TData = Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError = HTTPValidationError>(
 eventType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>,
          TError,
          Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet<TData = Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError = HTTPValidationError>(
 eventType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Default Template
 */

export function useGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet<TData = Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError = HTTPValidationError>(
 eventType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDefaultTemplateApiNotificationsTemplatesDefaultEventTypeGetQueryOptions(eventType,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Preview a rendered notification template with sample data.
 * @summary Preview Notification
 */
export type previewNotificationApiNotificationsPreviewPostResponse200 = {
  data: NotificationPreviewResponse
  status: 200
}

export type previewNotificationApiNotificationsPreviewPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type previewNotificationApiNotificationsPreviewPostResponseSuccess = (previewNotificationApiNotificationsPreviewPostResponse200) & {
  headers: Headers;
};
export type previewNotificationApiNotificationsPreviewPostResponseError = (previewNotificationApiNotificationsPreviewPostResponse422) & {
  headers: Headers;
};

export type previewNotificationApiNotificationsPreviewPostResponse = (previewNotificationApiNotificationsPreviewPostResponseSuccess | previewNotificationApiNotificationsPreviewPostResponseError)

export const getPreviewNotificationApiNotificationsPreviewPostUrl = () => {




  return `/api/notifications/preview`
}

export const previewNotificationApiNotificationsPreviewPost = async (notificationPreviewRequest: NotificationPreviewRequest, options?: RequestInit): Promise<previewNotificationApiNotificationsPreviewPostResponse> => {

  return customInstance<previewNotificationApiNotificationsPreviewPostResponse>(getPreviewNotificationApiNotificationsPreviewPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      notificationPreviewRequest,)
  }
);}




export const getPreviewNotificationApiNotificationsPreviewPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewNotificationApiNotificationsPreviewPost>>, TError,{data: NotificationPreviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof previewNotificationApiNotificationsPreviewPost>>, TError,{data: NotificationPreviewRequest}, TContext> => {

const mutationKey = ['previewNotificationApiNotificationsPreviewPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof previewNotificationApiNotificationsPreviewPost>>, {data: NotificationPreviewRequest}> = (props) => {
          const {data} = props ?? {};

          return  previewNotificationApiNotificationsPreviewPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PreviewNotificationApiNotificationsPreviewPostMutationResult = NonNullable<Awaited<ReturnType<typeof previewNotificationApiNotificationsPreviewPost>>>
    export type PreviewNotificationApiNotificationsPreviewPostMutationBody = NotificationPreviewRequest
    export type PreviewNotificationApiNotificationsPreviewPostMutationError = HTTPValidationError

    /**
 * @summary Preview Notification
 */
export const usePreviewNotificationApiNotificationsPreviewPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewNotificationApiNotificationsPreviewPost>>, TError,{data: NotificationPreviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof previewNotificationApiNotificationsPreviewPost>>,
        TError,
        {data: NotificationPreviewRequest},
        TContext
      > => {
      return useMutation(getPreviewNotificationApiNotificationsPreviewPostMutationOptions(options), queryClient);
    }
