/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CronJobsResponse,
  CronTriggerResponse,
  DashboardErrorsResponse,
  DashboardStatsResponse,
  FailedMailActionResponse,
  FailedMailsResponse,
  GetDashboardErrorsApiDashboardErrorsGetParams,
  GetFailedMailsApiDashboardFailedMailsGetParams,
  GetJobQueueStatusApiDashboardJobsGetParams,
  GetRecentActionsApiDashboardRecentActionsGetParams,
  HTTPValidationError,
  JobQueueStatusResponse,
  RecentActionsResponse
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get dashboard statistics for 24h / 7d / 30d time ranges.

Aggregates: mail processing actions, pending approvals, active accounts,
AI token usage, matched rules.
 * @summary Get Dashboard Stats
 */
export type getDashboardStatsApiDashboardStatsGetResponse200 = {
  data: DashboardStatsResponse
  status: 200
}

export type getDashboardStatsApiDashboardStatsGetResponseSuccess = (getDashboardStatsApiDashboardStatsGetResponse200) & {
  headers: Headers;
};
;

export type getDashboardStatsApiDashboardStatsGetResponse = (getDashboardStatsApiDashboardStatsGetResponseSuccess)

export const getGetDashboardStatsApiDashboardStatsGetUrl = () => {




  return `/api/dashboard/stats`
}

export const getDashboardStatsApiDashboardStatsGet = async ( options?: RequestInit): Promise<getDashboardStatsApiDashboardStatsGetResponse> => {

  return customInstance<getDashboardStatsApiDashboardStatsGetResponse>(getGetDashboardStatsApiDashboardStatsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardStatsApiDashboardStatsGetQueryKey = () => {
    return [
    `/api/dashboard/stats`
    ] as const;
    }


export const getGetDashboardStatsApiDashboardStatsGetQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardStatsApiDashboardStatsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>> = ({ signal }) => getDashboardStatsApiDashboardStatsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardStatsApiDashboardStatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>>
export type GetDashboardStatsApiDashboardStatsGetQueryError = unknown


export function useGetDashboardStatsApiDashboardStatsGet<TData = Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardStatsApiDashboardStatsGet<TData = Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardStatsApiDashboardStatsGet<TData = Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Dashboard Stats
 */

export function useGetDashboardStatsApiDashboardStatsGet<TData = Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiDashboardStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardStatsApiDashboardStatsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get recent AI actions (label + folder changes), paginated.

Uses a SQL UNION with ORDER BY / OFFSET / LIMIT so the database
handles sorting and pagination instead of loading everything into memory.
 * @summary Get Recent Actions
 */
export type getRecentActionsApiDashboardRecentActionsGetResponse200 = {
  data: RecentActionsResponse
  status: 200
}

export type getRecentActionsApiDashboardRecentActionsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getRecentActionsApiDashboardRecentActionsGetResponseSuccess = (getRecentActionsApiDashboardRecentActionsGetResponse200) & {
  headers: Headers;
};
export type getRecentActionsApiDashboardRecentActionsGetResponseError = (getRecentActionsApiDashboardRecentActionsGetResponse422) & {
  headers: Headers;
};

export type getRecentActionsApiDashboardRecentActionsGetResponse = (getRecentActionsApiDashboardRecentActionsGetResponseSuccess | getRecentActionsApiDashboardRecentActionsGetResponseError)

export const getGetRecentActionsApiDashboardRecentActionsGetUrl = (params?: GetRecentActionsApiDashboardRecentActionsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/recent-actions?${stringifiedParams}` : `/api/dashboard/recent-actions`
}

export const getRecentActionsApiDashboardRecentActionsGet = async (params?: GetRecentActionsApiDashboardRecentActionsGetParams, options?: RequestInit): Promise<getRecentActionsApiDashboardRecentActionsGetResponse> => {

  return customInstance<getRecentActionsApiDashboardRecentActionsGetResponse>(getGetRecentActionsApiDashboardRecentActionsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRecentActionsApiDashboardRecentActionsGetQueryKey = (params?: GetRecentActionsApiDashboardRecentActionsGetParams,) => {
    return [
    `/api/dashboard/recent-actions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetRecentActionsApiDashboardRecentActionsGetQueryOptions = <TData = Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError = HTTPValidationError>(params?: GetRecentActionsApiDashboardRecentActionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentActionsApiDashboardRecentActionsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>> = ({ signal }) => getRecentActionsApiDashboardRecentActionsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecentActionsApiDashboardRecentActionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>>
export type GetRecentActionsApiDashboardRecentActionsGetQueryError = HTTPValidationError


export function useGetRecentActionsApiDashboardRecentActionsGet<TData = Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetRecentActionsApiDashboardRecentActionsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>,
          TError,
          Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentActionsApiDashboardRecentActionsGet<TData = Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError = HTTPValidationError>(
 params?: GetRecentActionsApiDashboardRecentActionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>,
          TError,
          Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentActionsApiDashboardRecentActionsGet<TData = Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError = HTTPValidationError>(
 params?: GetRecentActionsApiDashboardRecentActionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Recent Actions
 */

export function useGetRecentActionsApiDashboardRecentActionsGet<TData = Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError = HTTPValidationError>(
 params?: GetRecentActionsApiDashboardRecentActionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentActionsApiDashboardRecentActionsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecentActionsApiDashboardRecentActionsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get recent account errors with timestamps, paginated in SQL.
 * @summary Get Dashboard Errors
 */
export type getDashboardErrorsApiDashboardErrorsGetResponse200 = {
  data: DashboardErrorsResponse
  status: 200
}

export type getDashboardErrorsApiDashboardErrorsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getDashboardErrorsApiDashboardErrorsGetResponseSuccess = (getDashboardErrorsApiDashboardErrorsGetResponse200) & {
  headers: Headers;
};
export type getDashboardErrorsApiDashboardErrorsGetResponseError = (getDashboardErrorsApiDashboardErrorsGetResponse422) & {
  headers: Headers;
};

export type getDashboardErrorsApiDashboardErrorsGetResponse = (getDashboardErrorsApiDashboardErrorsGetResponseSuccess | getDashboardErrorsApiDashboardErrorsGetResponseError)

export const getGetDashboardErrorsApiDashboardErrorsGetUrl = (params?: GetDashboardErrorsApiDashboardErrorsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/errors?${stringifiedParams}` : `/api/dashboard/errors`
}

export const getDashboardErrorsApiDashboardErrorsGet = async (params?: GetDashboardErrorsApiDashboardErrorsGetParams, options?: RequestInit): Promise<getDashboardErrorsApiDashboardErrorsGetResponse> => {

  return customInstance<getDashboardErrorsApiDashboardErrorsGetResponse>(getGetDashboardErrorsApiDashboardErrorsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardErrorsApiDashboardErrorsGetQueryKey = (params?: GetDashboardErrorsApiDashboardErrorsGetParams,) => {
    return [
    `/api/dashboard/errors`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDashboardErrorsApiDashboardErrorsGetQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError = HTTPValidationError>(params?: GetDashboardErrorsApiDashboardErrorsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardErrorsApiDashboardErrorsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>> = ({ signal }) => getDashboardErrorsApiDashboardErrorsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardErrorsApiDashboardErrorsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>>
export type GetDashboardErrorsApiDashboardErrorsGetQueryError = HTTPValidationError


export function useGetDashboardErrorsApiDashboardErrorsGet<TData = Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetDashboardErrorsApiDashboardErrorsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>,
          TError,
          Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardErrorsApiDashboardErrorsGet<TData = Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError = HTTPValidationError>(
 params?: GetDashboardErrorsApiDashboardErrorsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>,
          TError,
          Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardErrorsApiDashboardErrorsGet<TData = Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError = HTTPValidationError>(
 params?: GetDashboardErrorsApiDashboardErrorsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Dashboard Errors
 */

export function useGetDashboardErrorsApiDashboardErrorsGet<TData = Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError = HTTPValidationError>(
 params?: GetDashboardErrorsApiDashboardErrorsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardErrorsApiDashboardErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardErrorsApiDashboardErrorsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get ARQ job queue status from Valkey plus DB-based completion metrics.

Returns queue depth, in-progress jobs with mail UIDs, paginated
queued jobs, transient Valkey result counts, and persistent
DB-based completion/failure counters from ``TrackedEmail``.
 * @summary Get Job Queue Status
 */
export type getJobQueueStatusApiDashboardJobsGetResponse200 = {
  data: JobQueueStatusResponse
  status: 200
}

export type getJobQueueStatusApiDashboardJobsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getJobQueueStatusApiDashboardJobsGetResponseSuccess = (getJobQueueStatusApiDashboardJobsGetResponse200) & {
  headers: Headers;
};
export type getJobQueueStatusApiDashboardJobsGetResponseError = (getJobQueueStatusApiDashboardJobsGetResponse422) & {
  headers: Headers;
};

export type getJobQueueStatusApiDashboardJobsGetResponse = (getJobQueueStatusApiDashboardJobsGetResponseSuccess | getJobQueueStatusApiDashboardJobsGetResponseError)

export const getGetJobQueueStatusApiDashboardJobsGetUrl = (params?: GetJobQueueStatusApiDashboardJobsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/jobs?${stringifiedParams}` : `/api/dashboard/jobs`
}

export const getJobQueueStatusApiDashboardJobsGet = async (params?: GetJobQueueStatusApiDashboardJobsGetParams, options?: RequestInit): Promise<getJobQueueStatusApiDashboardJobsGetResponse> => {

  return customInstance<getJobQueueStatusApiDashboardJobsGetResponse>(getGetJobQueueStatusApiDashboardJobsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetJobQueueStatusApiDashboardJobsGetQueryKey = (params?: GetJobQueueStatusApiDashboardJobsGetParams,) => {
    return [
    `/api/dashboard/jobs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetJobQueueStatusApiDashboardJobsGetQueryOptions = <TData = Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError = HTTPValidationError>(params?: GetJobQueueStatusApiDashboardJobsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobQueueStatusApiDashboardJobsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>> = ({ signal }) => getJobQueueStatusApiDashboardJobsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetJobQueueStatusApiDashboardJobsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>>
export type GetJobQueueStatusApiDashboardJobsGetQueryError = HTTPValidationError


export function useGetJobQueueStatusApiDashboardJobsGet<TData = Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetJobQueueStatusApiDashboardJobsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>,
          TError,
          Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobQueueStatusApiDashboardJobsGet<TData = Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError = HTTPValidationError>(
 params?: GetJobQueueStatusApiDashboardJobsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>,
          TError,
          Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetJobQueueStatusApiDashboardJobsGet<TData = Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError = HTTPValidationError>(
 params?: GetJobQueueStatusApiDashboardJobsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Job Queue Status
 */

export function useGetJobQueueStatusApiDashboardJobsGet<TData = Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError = HTTPValidationError>(
 params?: GetJobQueueStatusApiDashboardJobsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobQueueStatusApiDashboardJobsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetJobQueueStatusApiDashboardJobsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Return status information for all ARQ cron jobs.

Reads ``cron:last_run:<name>`` keys from Valkey to determine
last execution time, and checks in-progress keys for running state.
 * @summary Get Cron Jobs
 */
export type getCronJobsApiDashboardCronsGetResponse200 = {
  data: CronJobsResponse
  status: 200
}

export type getCronJobsApiDashboardCronsGetResponseSuccess = (getCronJobsApiDashboardCronsGetResponse200) & {
  headers: Headers;
};
;

export type getCronJobsApiDashboardCronsGetResponse = (getCronJobsApiDashboardCronsGetResponseSuccess)

export const getGetCronJobsApiDashboardCronsGetUrl = () => {




  return `/api/dashboard/crons`
}

export const getCronJobsApiDashboardCronsGet = async ( options?: RequestInit): Promise<getCronJobsApiDashboardCronsGetResponse> => {

  return customInstance<getCronJobsApiDashboardCronsGetResponse>(getGetCronJobsApiDashboardCronsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCronJobsApiDashboardCronsGetQueryKey = () => {
    return [
    `/api/dashboard/crons`
    ] as const;
    }


export const getGetCronJobsApiDashboardCronsGetQueryOptions = <TData = Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCronJobsApiDashboardCronsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>> = ({ signal }) => getCronJobsApiDashboardCronsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCronJobsApiDashboardCronsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>>
export type GetCronJobsApiDashboardCronsGetQueryError = unknown


export function useGetCronJobsApiDashboardCronsGet<TData = Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>,
          TError,
          Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCronJobsApiDashboardCronsGet<TData = Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>,
          TError,
          Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCronJobsApiDashboardCronsGet<TData = Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Cron Jobs
 */

export function useGetCronJobsApiDashboardCronsGet<TData = Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCronJobsApiDashboardCronsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCronJobsApiDashboardCronsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Manually enqueue a cron job for immediate execution.

Returns the ARQ job object's id on success.
 * @summary Trigger Cron Job
 */
export type triggerCronJobApiDashboardCronsCronNameTriggerPostResponse200 = {
  data: CronTriggerResponse
  status: 200
}

export type triggerCronJobApiDashboardCronsCronNameTriggerPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type triggerCronJobApiDashboardCronsCronNameTriggerPostResponseSuccess = (triggerCronJobApiDashboardCronsCronNameTriggerPostResponse200) & {
  headers: Headers;
};
export type triggerCronJobApiDashboardCronsCronNameTriggerPostResponseError = (triggerCronJobApiDashboardCronsCronNameTriggerPostResponse422) & {
  headers: Headers;
};

export type triggerCronJobApiDashboardCronsCronNameTriggerPostResponse = (triggerCronJobApiDashboardCronsCronNameTriggerPostResponseSuccess | triggerCronJobApiDashboardCronsCronNameTriggerPostResponseError)

export const getTriggerCronJobApiDashboardCronsCronNameTriggerPostUrl = (cronName: string,) => {




  return `/api/dashboard/crons/${cronName}/trigger`
}

export const triggerCronJobApiDashboardCronsCronNameTriggerPost = async (cronName: string, options?: RequestInit): Promise<triggerCronJobApiDashboardCronsCronNameTriggerPostResponse> => {

  return customInstance<triggerCronJobApiDashboardCronsCronNameTriggerPostResponse>(getTriggerCronJobApiDashboardCronsCronNameTriggerPostUrl(cronName),
  {
    ...options,
    method: 'POST'


  }
);}




export const getTriggerCronJobApiDashboardCronsCronNameTriggerPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerCronJobApiDashboardCronsCronNameTriggerPost>>, TError,{cronName: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof triggerCronJobApiDashboardCronsCronNameTriggerPost>>, TError,{cronName: string}, TContext> => {

const mutationKey = ['triggerCronJobApiDashboardCronsCronNameTriggerPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerCronJobApiDashboardCronsCronNameTriggerPost>>, {cronName: string}> = (props) => {
          const {cronName} = props ?? {};

          return  triggerCronJobApiDashboardCronsCronNameTriggerPost(cronName,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerCronJobApiDashboardCronsCronNameTriggerPostMutationResult = NonNullable<Awaited<ReturnType<typeof triggerCronJobApiDashboardCronsCronNameTriggerPost>>>

    export type TriggerCronJobApiDashboardCronsCronNameTriggerPostMutationError = HTTPValidationError

    /**
 * @summary Trigger Cron Job
 */
export const useTriggerCronJobApiDashboardCronsCronNameTriggerPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerCronJobApiDashboardCronsCronNameTriggerPost>>, TError,{cronName: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerCronJobApiDashboardCronsCronNameTriggerPost>>,
        TError,
        {cronName: string},
        TContext
      > => {
      return useMutation(getTriggerCronJobApiDashboardCronsCronNameTriggerPostMutationOptions(options), queryClient);
    }
    /**
 * Get failed mails from tracked_emails, paginated.
 * @summary Get Failed Mails
 */
export type getFailedMailsApiDashboardFailedMailsGetResponse200 = {
  data: FailedMailsResponse
  status: 200
}

export type getFailedMailsApiDashboardFailedMailsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getFailedMailsApiDashboardFailedMailsGetResponseSuccess = (getFailedMailsApiDashboardFailedMailsGetResponse200) & {
  headers: Headers;
};
export type getFailedMailsApiDashboardFailedMailsGetResponseError = (getFailedMailsApiDashboardFailedMailsGetResponse422) & {
  headers: Headers;
};

export type getFailedMailsApiDashboardFailedMailsGetResponse = (getFailedMailsApiDashboardFailedMailsGetResponseSuccess | getFailedMailsApiDashboardFailedMailsGetResponseError)

export const getGetFailedMailsApiDashboardFailedMailsGetUrl = (params?: GetFailedMailsApiDashboardFailedMailsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/failed-mails?${stringifiedParams}` : `/api/dashboard/failed-mails`
}

export const getFailedMailsApiDashboardFailedMailsGet = async (params?: GetFailedMailsApiDashboardFailedMailsGetParams, options?: RequestInit): Promise<getFailedMailsApiDashboardFailedMailsGetResponse> => {

  return customInstance<getFailedMailsApiDashboardFailedMailsGetResponse>(getGetFailedMailsApiDashboardFailedMailsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFailedMailsApiDashboardFailedMailsGetQueryKey = (params?: GetFailedMailsApiDashboardFailedMailsGetParams,) => {
    return [
    `/api/dashboard/failed-mails`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetFailedMailsApiDashboardFailedMailsGetQueryOptions = <TData = Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError = HTTPValidationError>(params?: GetFailedMailsApiDashboardFailedMailsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFailedMailsApiDashboardFailedMailsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>> = ({ signal }) => getFailedMailsApiDashboardFailedMailsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFailedMailsApiDashboardFailedMailsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>>
export type GetFailedMailsApiDashboardFailedMailsGetQueryError = HTTPValidationError


export function useGetFailedMailsApiDashboardFailedMailsGet<TData = Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetFailedMailsApiDashboardFailedMailsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>,
          TError,
          Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFailedMailsApiDashboardFailedMailsGet<TData = Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError = HTTPValidationError>(
 params?: GetFailedMailsApiDashboardFailedMailsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>,
          TError,
          Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFailedMailsApiDashboardFailedMailsGet<TData = Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError = HTTPValidationError>(
 params?: GetFailedMailsApiDashboardFailedMailsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Failed Mails
 */

export function useGetFailedMailsApiDashboardFailedMailsGet<TData = Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError = HTTPValidationError>(
 params?: GetFailedMailsApiDashboardFailedMailsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFailedMailsApiDashboardFailedMailsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFailedMailsApiDashboardFailedMailsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Retry a failed mail: set status back to pending and reset retry_count.
 * @summary Retry Failed Mail
 */
export type retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponse200 = {
  data: FailedMailActionResponse
  status: 200
}

export type retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponseSuccess = (retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponse200) & {
  headers: Headers;
};
export type retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponseError = (retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponse422) & {
  headers: Headers;
};

export type retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponse = (retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponseSuccess | retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponseError)

export const getRetryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostUrl = (trackedEmailId: string,) => {




  return `/api/dashboard/failed-mails/${trackedEmailId}/retry`
}

export const retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost = async (trackedEmailId: string, options?: RequestInit): Promise<retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponse> => {

  return customInstance<retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostResponse>(getRetryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostUrl(trackedEmailId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getRetryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost>>, TError,{trackedEmailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost>>, TError,{trackedEmailId: string}, TContext> => {

const mutationKey = ['retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost>>, {trackedEmailId: string}> = (props) => {
          const {trackedEmailId} = props ?? {};

          return  retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost(trackedEmailId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RetryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostMutationResult = NonNullable<Awaited<ReturnType<typeof retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost>>>

    export type RetryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostMutationError = HTTPValidationError

    /**
 * @summary Retry Failed Mail
 */
export const useRetryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost>>, TError,{trackedEmailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof retryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPost>>,
        TError,
        {trackedEmailId: string},
        TContext
      > => {
      return useMutation(getRetryFailedMailApiDashboardFailedMailsTrackedEmailIdRetryPostMutationOptions(options), queryClient);
    }
    /**
 * Dismiss a failed mail: mark as completed (user considers it handled).
 * @summary Resolve Failed Mail
 */
export type resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponse200 = {
  data: FailedMailActionResponse
  status: 200
}

export type resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponseSuccess = (resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponse200) & {
  headers: Headers;
};
export type resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponseError = (resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponse422) & {
  headers: Headers;
};

export type resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponse = (resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponseSuccess | resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponseError)

export const getResolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostUrl = (trackedEmailId: string,) => {




  return `/api/dashboard/failed-mails/${trackedEmailId}/resolve`
}

export const resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost = async (trackedEmailId: string, options?: RequestInit): Promise<resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponse> => {

  return customInstance<resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostResponse>(getResolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostUrl(trackedEmailId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getResolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost>>, TError,{trackedEmailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost>>, TError,{trackedEmailId: string}, TContext> => {

const mutationKey = ['resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost>>, {trackedEmailId: string}> = (props) => {
          const {trackedEmailId} = props ?? {};

          return  resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost(trackedEmailId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostMutationResult = NonNullable<Awaited<ReturnType<typeof resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost>>>

    export type ResolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostMutationError = HTTPValidationError

    /**
 * @summary Resolve Failed Mail
 */
export const useResolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost>>, TError,{trackedEmailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePost>>,
        TError,
        {trackedEmailId: string},
        TContext
      > => {
      return useMutation(getResolveFailedMailApiDashboardFailedMailsTrackedEmailIdResolvePostMutationOptions(options), queryClient);
    }
