/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  PipelineTestRequest
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Test the AI processing pipeline with sample email data (SSE stream).

Streams progress events as each plugin step is processed:
  - ``step``: a plugin is about to be processed (index, total, name)
  - ``skip``: a plugin was skipped (with reason)
  - ``result``: a plugin finished (full PluginTestResult)
  - ``done``: pipeline completed (summary)
  - ``error``: fatal pipeline error
 * @summary Test Pipeline
 */
export type testPipelineApiPipelineTestPostResponse200 = {
  data: unknown
  status: 200
}

export type testPipelineApiPipelineTestPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type testPipelineApiPipelineTestPostResponseSuccess = (testPipelineApiPipelineTestPostResponse200) & {
  headers: Headers;
};
export type testPipelineApiPipelineTestPostResponseError = (testPipelineApiPipelineTestPostResponse422) & {
  headers: Headers;
};

export type testPipelineApiPipelineTestPostResponse = (testPipelineApiPipelineTestPostResponseSuccess | testPipelineApiPipelineTestPostResponseError)

export const getTestPipelineApiPipelineTestPostUrl = () => {




  return `/api/pipeline/test`
}

export const testPipelineApiPipelineTestPost = async (pipelineTestRequest: PipelineTestRequest, options?: RequestInit): Promise<testPipelineApiPipelineTestPostResponse> => {

  return customInstance<testPipelineApiPipelineTestPostResponse>(getTestPipelineApiPipelineTestPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pipelineTestRequest,)
  }
);}




export const getTestPipelineApiPipelineTestPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testPipelineApiPipelineTestPost>>, TError,{data: PipelineTestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof testPipelineApiPipelineTestPost>>, TError,{data: PipelineTestRequest}, TContext> => {

const mutationKey = ['testPipelineApiPipelineTestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testPipelineApiPipelineTestPost>>, {data: PipelineTestRequest}> = (props) => {
          const {data} = props ?? {};

          return  testPipelineApiPipelineTestPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestPipelineApiPipelineTestPostMutationResult = NonNullable<Awaited<ReturnType<typeof testPipelineApiPipelineTestPost>>>
    export type TestPipelineApiPipelineTestPostMutationBody = PipelineTestRequest
    export type TestPipelineApiPipelineTestPostMutationError = HTTPValidationError

    /**
 * @summary Test Pipeline
 */
export const useTestPipelineApiPipelineTestPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testPipelineApiPipelineTestPost>>, TError,{data: PipelineTestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testPipelineApiPipelineTestPost>>,
        TError,
        {data: PipelineTestRequest},
        TContext
      > => {
      return useMutation(getTestPipelineApiPipelineTestPostMutationOptions(options), queryClient);
    }
