/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignEmailRequest,
  AssignEmailResponse,
  CardDAVConfigCreate,
  CardDAVConfigResponse,
  CardDAVTestRequest,
  CardDAVTestResult,
  ContactAssignmentResponse,
  ContactCreateRequest,
  ContactExtractRequest,
  ContactExtractedData,
  ContactListResponse,
  ContactMailsResponse,
  ContactResponse,
  HTTPValidationError,
  ListAllSendersApiContactsSendersGetParams,
  ListContactMailsApiContactsContactIdMailsGetParams,
  ListContactsApiContactsGetParams,
  RemoveEmailRequest,
  RemoveEmailResponse,
  SenderResponse,
  SyncResult
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get the current user's CardDAV configuration (credentials excluded).

Returns ``None`` (HTTP 200 with ``null`` body) when no config exists.
This is intentional: ``null`` tells the frontend "not configured yet"
and renders the setup form, whereas a 404 would trigger an error state.
 * @summary Get Config
 */
export type getConfigApiContactsConfigGetResponse200 = {
  data: CardDAVConfigResponse | null
  status: 200
}

export type getConfigApiContactsConfigGetResponseSuccess = (getConfigApiContactsConfigGetResponse200) & {
  headers: Headers;
};
;

export type getConfigApiContactsConfigGetResponse = (getConfigApiContactsConfigGetResponseSuccess)

export const getGetConfigApiContactsConfigGetUrl = () => {




  return `/api/contacts/config`
}

export const getConfigApiContactsConfigGet = async ( options?: RequestInit): Promise<getConfigApiContactsConfigGetResponse> => {

  return customInstance<getConfigApiContactsConfigGetResponse>(getGetConfigApiContactsConfigGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConfigApiContactsConfigGetQueryKey = () => {
    return [
    `/api/contacts/config`
    ] as const;
    }


export const getGetConfigApiContactsConfigGetQueryOptions = <TData = Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConfigApiContactsConfigGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>> = ({ signal }) => getConfigApiContactsConfigGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConfigApiContactsConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>>
export type GetConfigApiContactsConfigGetQueryError = unknown


export function useGetConfigApiContactsConfigGet<TData = Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>,
          TError,
          Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigApiContactsConfigGet<TData = Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>,
          TError,
          Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigApiContactsConfigGet<TData = Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Config
 */

export function useGetConfigApiContactsConfigGet<TData = Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiContactsConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConfigApiContactsConfigGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Create or update CardDAV configuration with encrypted credentials.
 * @summary Upsert Config
 */
export type upsertConfigApiContactsConfigPutResponse200 = {
  data: CardDAVConfigResponse
  status: 200
}

export type upsertConfigApiContactsConfigPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type upsertConfigApiContactsConfigPutResponseSuccess = (upsertConfigApiContactsConfigPutResponse200) & {
  headers: Headers;
};
export type upsertConfigApiContactsConfigPutResponseError = (upsertConfigApiContactsConfigPutResponse422) & {
  headers: Headers;
};

export type upsertConfigApiContactsConfigPutResponse = (upsertConfigApiContactsConfigPutResponseSuccess | upsertConfigApiContactsConfigPutResponseError)

export const getUpsertConfigApiContactsConfigPutUrl = () => {




  return `/api/contacts/config`
}

export const upsertConfigApiContactsConfigPut = async (cardDAVConfigCreate: CardDAVConfigCreate, options?: RequestInit): Promise<upsertConfigApiContactsConfigPutResponse> => {

  return customInstance<upsertConfigApiContactsConfigPutResponse>(getUpsertConfigApiContactsConfigPutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      cardDAVConfigCreate,)
  }
);}




export const getUpsertConfigApiContactsConfigPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertConfigApiContactsConfigPut>>, TError,{data: CardDAVConfigCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertConfigApiContactsConfigPut>>, TError,{data: CardDAVConfigCreate}, TContext> => {

const mutationKey = ['upsertConfigApiContactsConfigPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertConfigApiContactsConfigPut>>, {data: CardDAVConfigCreate}> = (props) => {
          const {data} = props ?? {};

          return  upsertConfigApiContactsConfigPut(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpsertConfigApiContactsConfigPutMutationResult = NonNullable<Awaited<ReturnType<typeof upsertConfigApiContactsConfigPut>>>
    export type UpsertConfigApiContactsConfigPutMutationBody = CardDAVConfigCreate
    export type UpsertConfigApiContactsConfigPutMutationError = HTTPValidationError

    /**
 * @summary Upsert Config
 */
export const useUpsertConfigApiContactsConfigPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertConfigApiContactsConfigPut>>, TError,{data: CardDAVConfigCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertConfigApiContactsConfigPut>>,
        TError,
        {data: CardDAVConfigCreate},
        TContext
      > => {
      return useMutation(getUpsertConfigApiContactsConfigPutMutationOptions(options), queryClient);
    }
    /**
 * Test a CardDAV connection before saving configuration.
 * @summary Test Config
 */
export type testConfigApiContactsConfigTestPostResponse200 = {
  data: CardDAVTestResult
  status: 200
}

export type testConfigApiContactsConfigTestPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type testConfigApiContactsConfigTestPostResponseSuccess = (testConfigApiContactsConfigTestPostResponse200) & {
  headers: Headers;
};
export type testConfigApiContactsConfigTestPostResponseError = (testConfigApiContactsConfigTestPostResponse422) & {
  headers: Headers;
};

export type testConfigApiContactsConfigTestPostResponse = (testConfigApiContactsConfigTestPostResponseSuccess | testConfigApiContactsConfigTestPostResponseError)

export const getTestConfigApiContactsConfigTestPostUrl = () => {




  return `/api/contacts/config/test`
}

export const testConfigApiContactsConfigTestPost = async (cardDAVTestRequest: CardDAVTestRequest, options?: RequestInit): Promise<testConfigApiContactsConfigTestPostResponse> => {

  return customInstance<testConfigApiContactsConfigTestPostResponse>(getTestConfigApiContactsConfigTestPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      cardDAVTestRequest,)
  }
);}




export const getTestConfigApiContactsConfigTestPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testConfigApiContactsConfigTestPost>>, TError,{data: CardDAVTestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof testConfigApiContactsConfigTestPost>>, TError,{data: CardDAVTestRequest}, TContext> => {

const mutationKey = ['testConfigApiContactsConfigTestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testConfigApiContactsConfigTestPost>>, {data: CardDAVTestRequest}> = (props) => {
          const {data} = props ?? {};

          return  testConfigApiContactsConfigTestPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestConfigApiContactsConfigTestPostMutationResult = NonNullable<Awaited<ReturnType<typeof testConfigApiContactsConfigTestPost>>>
    export type TestConfigApiContactsConfigTestPostMutationBody = CardDAVTestRequest
    export type TestConfigApiContactsConfigTestPostMutationError = HTTPValidationError

    /**
 * @summary Test Config
 */
export const useTestConfigApiContactsConfigTestPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testConfigApiContactsConfigTestPost>>, TError,{data: CardDAVTestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testConfigApiContactsConfigTestPost>>,
        TError,
        {data: CardDAVTestRequest},
        TContext
      > => {
      return useMutation(getTestConfigApiContactsConfigTestPostMutationOptions(options), queryClient);
    }
    /**
 * Trigger a manual contact sync from CardDAV.

Uses the stored CardDAV configuration. Performs full re-sync
if no sync-token exists, otherwise incremental.
 * @summary Trigger Sync
 */
export type triggerSyncApiContactsSyncPostResponse200 = {
  data: SyncResult
  status: 200
}

export type triggerSyncApiContactsSyncPostResponseSuccess = (triggerSyncApiContactsSyncPostResponse200) & {
  headers: Headers;
};
;

export type triggerSyncApiContactsSyncPostResponse = (triggerSyncApiContactsSyncPostResponseSuccess)

export const getTriggerSyncApiContactsSyncPostUrl = () => {




  return `/api/contacts/sync`
}

export const triggerSyncApiContactsSyncPost = async ( options?: RequestInit): Promise<triggerSyncApiContactsSyncPostResponse> => {

  return customInstance<triggerSyncApiContactsSyncPostResponse>(getTriggerSyncApiContactsSyncPostUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getTriggerSyncApiContactsSyncPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerSyncApiContactsSyncPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof triggerSyncApiContactsSyncPost>>, TError,void, TContext> => {

const mutationKey = ['triggerSyncApiContactsSyncPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerSyncApiContactsSyncPost>>, void> = () => {


          return  triggerSyncApiContactsSyncPost(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerSyncApiContactsSyncPostMutationResult = NonNullable<Awaited<ReturnType<typeof triggerSyncApiContactsSyncPost>>>

    export type TriggerSyncApiContactsSyncPostMutationError = unknown

    /**
 * @summary Trigger Sync
 */
export const useTriggerSyncApiContactsSyncPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerSyncApiContactsSyncPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerSyncApiContactsSyncPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getTriggerSyncApiContactsSyncPostMutationOptions(options), queryClient);
    }
    /**
 * List cached contacts with optional search and pagination.
 * @summary List Contacts
 */
export type listContactsApiContactsGetResponse200 = {
  data: ContactListResponse
  status: 200
}

export type listContactsApiContactsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listContactsApiContactsGetResponseSuccess = (listContactsApiContactsGetResponse200) & {
  headers: Headers;
};
export type listContactsApiContactsGetResponseError = (listContactsApiContactsGetResponse422) & {
  headers: Headers;
};

export type listContactsApiContactsGetResponse = (listContactsApiContactsGetResponseSuccess | listContactsApiContactsGetResponseError)

export const getListContactsApiContactsGetUrl = (params?: ListContactsApiContactsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/contacts?${stringifiedParams}` : `/api/contacts`
}

export const listContactsApiContactsGet = async (params?: ListContactsApiContactsGetParams, options?: RequestInit): Promise<listContactsApiContactsGetResponse> => {

  return customInstance<listContactsApiContactsGetResponse>(getListContactsApiContactsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListContactsApiContactsGetQueryKey = (params?: ListContactsApiContactsGetParams,) => {
    return [
    `/api/contacts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListContactsApiContactsGetQueryOptions = <TData = Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError = HTTPValidationError>(params?: ListContactsApiContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListContactsApiContactsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listContactsApiContactsGet>>> = ({ signal }) => listContactsApiContactsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListContactsApiContactsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listContactsApiContactsGet>>>
export type ListContactsApiContactsGetQueryError = HTTPValidationError


export function useListContactsApiContactsGet<TData = Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListContactsApiContactsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listContactsApiContactsGet>>,
          TError,
          Awaited<ReturnType<typeof listContactsApiContactsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListContactsApiContactsGet<TData = Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError = HTTPValidationError>(
 params?: ListContactsApiContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listContactsApiContactsGet>>,
          TError,
          Awaited<ReturnType<typeof listContactsApiContactsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListContactsApiContactsGet<TData = Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError = HTTPValidationError>(
 params?: ListContactsApiContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Contacts
 */

export function useListContactsApiContactsGet<TData = Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError = HTTPValidationError>(
 params?: ListContactsApiContactsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactsApiContactsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListContactsApiContactsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Create a new local contact (not from CardDAV sync).

Generates a synthetic CardDAV UID for local-only contacts and
auto-assigns the email addresses to the new contact.
If CardDAV is configured, a write-back is attempted.
 * @summary Create Contact
 */
export type createContactApiContactsPostResponse201 = {
  data: ContactResponse
  status: 201
}

export type createContactApiContactsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createContactApiContactsPostResponseSuccess = (createContactApiContactsPostResponse201) & {
  headers: Headers;
};
export type createContactApiContactsPostResponseError = (createContactApiContactsPostResponse422) & {
  headers: Headers;
};

export type createContactApiContactsPostResponse = (createContactApiContactsPostResponseSuccess | createContactApiContactsPostResponseError)

export const getCreateContactApiContactsPostUrl = () => {




  return `/api/contacts`
}

export const createContactApiContactsPost = async (contactCreateRequest: ContactCreateRequest, options?: RequestInit): Promise<createContactApiContactsPostResponse> => {

  return customInstance<createContactApiContactsPostResponse>(getCreateContactApiContactsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactCreateRequest,)
  }
);}




export const getCreateContactApiContactsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContactApiContactsPost>>, TError,{data: ContactCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createContactApiContactsPost>>, TError,{data: ContactCreateRequest}, TContext> => {

const mutationKey = ['createContactApiContactsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContactApiContactsPost>>, {data: ContactCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createContactApiContactsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateContactApiContactsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createContactApiContactsPost>>>
    export type CreateContactApiContactsPostMutationBody = ContactCreateRequest
    export type CreateContactApiContactsPostMutationError = HTTPValidationError

    /**
 * @summary Create Contact
 */
export const useCreateContactApiContactsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContactApiContactsPost>>, TError,{data: ContactCreateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createContactApiContactsPost>>,
        TError,
        {data: ContactCreateRequest},
        TContext
      > => {
      return useMutation(getCreateContactApiContactsPostMutationOptions(options), queryClient);
    }
    /**
 * List unique email addresses: senders from emails AND contact emails.

Returns every unique ``mail_from`` from ``email_summaries`` for this
user, together with the mail count and the contact ID if the sender
is already assigned to a contact.  Additionally includes all email
addresses stored in contacts that have never appeared as a sender
(with ``mail_count=0``), so the matching UI always shows the full
picture.

Use ``matched=false`` to get only unmatched senders,
``matched=true`` for only matched ones, or omit for all.
 * @summary List All Senders
 */
export type listAllSendersApiContactsSendersGetResponse200 = {
  data: SenderResponse[]
  status: 200
}

export type listAllSendersApiContactsSendersGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listAllSendersApiContactsSendersGetResponseSuccess = (listAllSendersApiContactsSendersGetResponse200) & {
  headers: Headers;
};
export type listAllSendersApiContactsSendersGetResponseError = (listAllSendersApiContactsSendersGetResponse422) & {
  headers: Headers;
};

export type listAllSendersApiContactsSendersGetResponse = (listAllSendersApiContactsSendersGetResponseSuccess | listAllSendersApiContactsSendersGetResponseError)

export const getListAllSendersApiContactsSendersGetUrl = (params?: ListAllSendersApiContactsSendersGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/contacts/senders?${stringifiedParams}` : `/api/contacts/senders`
}

export const listAllSendersApiContactsSendersGet = async (params?: ListAllSendersApiContactsSendersGetParams, options?: RequestInit): Promise<listAllSendersApiContactsSendersGetResponse> => {

  return customInstance<listAllSendersApiContactsSendersGetResponse>(getListAllSendersApiContactsSendersGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAllSendersApiContactsSendersGetQueryKey = (params?: ListAllSendersApiContactsSendersGetParams,) => {
    return [
    `/api/contacts/senders`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAllSendersApiContactsSendersGetQueryOptions = <TData = Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError = HTTPValidationError>(params?: ListAllSendersApiContactsSendersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllSendersApiContactsSendersGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>> = ({ signal }) => listAllSendersApiContactsSendersGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAllSendersApiContactsSendersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>>
export type ListAllSendersApiContactsSendersGetQueryError = HTTPValidationError


export function useListAllSendersApiContactsSendersGet<TData = Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError = HTTPValidationError>(
 params: undefined |  ListAllSendersApiContactsSendersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>,
          TError,
          Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllSendersApiContactsSendersGet<TData = Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError = HTTPValidationError>(
 params?: ListAllSendersApiContactsSendersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>,
          TError,
          Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllSendersApiContactsSendersGet<TData = Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError = HTTPValidationError>(
 params?: ListAllSendersApiContactsSendersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List All Senders
 */

export function useListAllSendersApiContactsSendersGet<TData = Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError = HTTPValidationError>(
 params?: ListAllSendersApiContactsSendersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllSendersApiContactsSendersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAllSendersApiContactsSendersGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Use AI to extract contact information from all emails by a sender.

Collects all email summaries for the given sender address and asks the
AI to extract structured contact data (name, phone, organization, title).
 * @summary Extract Contact From Sender
 */
export type extractContactFromSenderApiContactsExtractFromSenderPostResponse200 = {
  data: ContactExtractedData
  status: 200
}

export type extractContactFromSenderApiContactsExtractFromSenderPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type extractContactFromSenderApiContactsExtractFromSenderPostResponseSuccess = (extractContactFromSenderApiContactsExtractFromSenderPostResponse200) & {
  headers: Headers;
};
export type extractContactFromSenderApiContactsExtractFromSenderPostResponseError = (extractContactFromSenderApiContactsExtractFromSenderPostResponse422) & {
  headers: Headers;
};

export type extractContactFromSenderApiContactsExtractFromSenderPostResponse = (extractContactFromSenderApiContactsExtractFromSenderPostResponseSuccess | extractContactFromSenderApiContactsExtractFromSenderPostResponseError)

export const getExtractContactFromSenderApiContactsExtractFromSenderPostUrl = () => {




  return `/api/contacts/extract-from-sender`
}

export const extractContactFromSenderApiContactsExtractFromSenderPost = async (contactExtractRequest: ContactExtractRequest, options?: RequestInit): Promise<extractContactFromSenderApiContactsExtractFromSenderPostResponse> => {

  return customInstance<extractContactFromSenderApiContactsExtractFromSenderPostResponse>(getExtractContactFromSenderApiContactsExtractFromSenderPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactExtractRequest,)
  }
);}




export const getExtractContactFromSenderApiContactsExtractFromSenderPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof extractContactFromSenderApiContactsExtractFromSenderPost>>, TError,{data: ContactExtractRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof extractContactFromSenderApiContactsExtractFromSenderPost>>, TError,{data: ContactExtractRequest}, TContext> => {

const mutationKey = ['extractContactFromSenderApiContactsExtractFromSenderPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof extractContactFromSenderApiContactsExtractFromSenderPost>>, {data: ContactExtractRequest}> = (props) => {
          const {data} = props ?? {};

          return  extractContactFromSenderApiContactsExtractFromSenderPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExtractContactFromSenderApiContactsExtractFromSenderPostMutationResult = NonNullable<Awaited<ReturnType<typeof extractContactFromSenderApiContactsExtractFromSenderPost>>>
    export type ExtractContactFromSenderApiContactsExtractFromSenderPostMutationBody = ContactExtractRequest
    export type ExtractContactFromSenderApiContactsExtractFromSenderPostMutationError = HTTPValidationError

    /**
 * @summary Extract Contact From Sender
 */
export const useExtractContactFromSenderApiContactsExtractFromSenderPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof extractContactFromSenderApiContactsExtractFromSenderPost>>, TError,{data: ContactExtractRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof extractContactFromSenderApiContactsExtractFromSenderPost>>,
        TError,
        {data: ContactExtractRequest},
        TContext
      > => {
      return useMutation(getExtractContactFromSenderApiContactsExtractFromSenderPostMutationOptions(options), queryClient);
    }
    /**
 * Get the AI-assigned contact for a specific mail.

Returns ``None`` (HTTP 200 with ``null`` body) when no assignment exists.
 * @summary Get Mail Contact
 */
export type getMailContactApiContactsAssignmentAccountIdMailUidGetResponse200 = {
  data: ContactAssignmentResponse | null
  status: 200
}

export type getMailContactApiContactsAssignmentAccountIdMailUidGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getMailContactApiContactsAssignmentAccountIdMailUidGetResponseSuccess = (getMailContactApiContactsAssignmentAccountIdMailUidGetResponse200) & {
  headers: Headers;
};
export type getMailContactApiContactsAssignmentAccountIdMailUidGetResponseError = (getMailContactApiContactsAssignmentAccountIdMailUidGetResponse422) & {
  headers: Headers;
};

export type getMailContactApiContactsAssignmentAccountIdMailUidGetResponse = (getMailContactApiContactsAssignmentAccountIdMailUidGetResponseSuccess | getMailContactApiContactsAssignmentAccountIdMailUidGetResponseError)

export const getGetMailContactApiContactsAssignmentAccountIdMailUidGetUrl = (accountId: string,
    mailUid: string,) => {




  return `/api/contacts/assignment/${accountId}/${mailUid}`
}

export const getMailContactApiContactsAssignmentAccountIdMailUidGet = async (accountId: string,
    mailUid: string, options?: RequestInit): Promise<getMailContactApiContactsAssignmentAccountIdMailUidGetResponse> => {

  return customInstance<getMailContactApiContactsAssignmentAccountIdMailUidGetResponse>(getGetMailContactApiContactsAssignmentAccountIdMailUidGetUrl(accountId,mailUid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMailContactApiContactsAssignmentAccountIdMailUidGetQueryKey = (accountId: string,
    mailUid: string,) => {
    return [
    `/api/contacts/assignment/${accountId}/${mailUid}`
    ] as const;
    }


export const getGetMailContactApiContactsAssignmentAccountIdMailUidGetQueryOptions = <TData = Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError = HTTPValidationError>(accountId: string,
    mailUid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMailContactApiContactsAssignmentAccountIdMailUidGetQueryKey(accountId,mailUid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>> = ({ signal }) => getMailContactApiContactsAssignmentAccountIdMailUidGet(accountId,mailUid, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(accountId && mailUid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMailContactApiContactsAssignmentAccountIdMailUidGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>>
export type GetMailContactApiContactsAssignmentAccountIdMailUidGetQueryError = HTTPValidationError


export function useGetMailContactApiContactsAssignmentAccountIdMailUidGet<TData = Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError = HTTPValidationError>(
 accountId: string,
    mailUid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>,
          TError,
          Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMailContactApiContactsAssignmentAccountIdMailUidGet<TData = Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError = HTTPValidationError>(
 accountId: string,
    mailUid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>,
          TError,
          Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMailContactApiContactsAssignmentAccountIdMailUidGet<TData = Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError = HTTPValidationError>(
 accountId: string,
    mailUid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Mail Contact
 */

export function useGetMailContactApiContactsAssignmentAccountIdMailUidGet<TData = Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError = HTTPValidationError>(
 accountId: string,
    mailUid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMailContactApiContactsAssignmentAccountIdMailUidGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMailContactApiContactsAssignmentAccountIdMailUidGetQueryOptions(accountId,mailUid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get a single cached contact by ID.
 * @summary Get Contact
 */
export type getContactApiContactsContactIdGetResponse200 = {
  data: ContactResponse
  status: 200
}

export type getContactApiContactsContactIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getContactApiContactsContactIdGetResponseSuccess = (getContactApiContactsContactIdGetResponse200) & {
  headers: Headers;
};
export type getContactApiContactsContactIdGetResponseError = (getContactApiContactsContactIdGetResponse422) & {
  headers: Headers;
};

export type getContactApiContactsContactIdGetResponse = (getContactApiContactsContactIdGetResponseSuccess | getContactApiContactsContactIdGetResponseError)

export const getGetContactApiContactsContactIdGetUrl = (contactId: string,) => {




  return `/api/contacts/${contactId}`
}

export const getContactApiContactsContactIdGet = async (contactId: string, options?: RequestInit): Promise<getContactApiContactsContactIdGetResponse> => {

  return customInstance<getContactApiContactsContactIdGetResponse>(getGetContactApiContactsContactIdGetUrl(contactId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetContactApiContactsContactIdGetQueryKey = (contactId: string,) => {
    return [
    `/api/contacts/${contactId}`
    ] as const;
    }


export const getGetContactApiContactsContactIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError = HTTPValidationError>(contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactApiContactsContactIdGetQueryKey(contactId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>> = ({ signal }) => getContactApiContactsContactIdGet(contactId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(contactId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactApiContactsContactIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>>
export type GetContactApiContactsContactIdGetQueryError = HTTPValidationError


export function useGetContactApiContactsContactIdGet<TData = Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError = HTTPValidationError>(
 contactId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>,
          TError,
          Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactApiContactsContactIdGet<TData = Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError = HTTPValidationError>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>,
          TError,
          Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactApiContactsContactIdGet<TData = Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError = HTTPValidationError>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Contact
 */

export function useGetContactApiContactsContactIdGet<TData = Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError = HTTPValidationError>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactApiContactsContactIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactApiContactsContactIdGetQueryOptions(contactId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Delete a cached contact.
 * @summary Delete Contact
 */
export type deleteContactApiContactsContactIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteContactApiContactsContactIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteContactApiContactsContactIdDeleteResponseSuccess = (deleteContactApiContactsContactIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteContactApiContactsContactIdDeleteResponseError = (deleteContactApiContactsContactIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteContactApiContactsContactIdDeleteResponse = (deleteContactApiContactsContactIdDeleteResponseSuccess | deleteContactApiContactsContactIdDeleteResponseError)

export const getDeleteContactApiContactsContactIdDeleteUrl = (contactId: string,) => {




  return `/api/contacts/${contactId}`
}

export const deleteContactApiContactsContactIdDelete = async (contactId: string, options?: RequestInit): Promise<deleteContactApiContactsContactIdDeleteResponse> => {

  return customInstance<deleteContactApiContactsContactIdDeleteResponse>(getDeleteContactApiContactsContactIdDeleteUrl(contactId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteContactApiContactsContactIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactApiContactsContactIdDelete>>, TError,{contactId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContactApiContactsContactIdDelete>>, TError,{contactId: string}, TContext> => {

const mutationKey = ['deleteContactApiContactsContactIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContactApiContactsContactIdDelete>>, {contactId: string}> = (props) => {
          const {contactId} = props ?? {};

          return  deleteContactApiContactsContactIdDelete(contactId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactApiContactsContactIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContactApiContactsContactIdDelete>>>

    export type DeleteContactApiContactsContactIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Contact
 */
export const useDeleteContactApiContactsContactIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactApiContactsContactIdDelete>>, TError,{contactId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContactApiContactsContactIdDelete>>,
        TError,
        {contactId: string},
        TContext
      > => {
      return useMutation(getDeleteContactApiContactsContactIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * List mails associated with a contact via AI assignment (paginated).
 * @summary List Contact Mails
 */
export type listContactMailsApiContactsContactIdMailsGetResponse200 = {
  data: ContactMailsResponse
  status: 200
}

export type listContactMailsApiContactsContactIdMailsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listContactMailsApiContactsContactIdMailsGetResponseSuccess = (listContactMailsApiContactsContactIdMailsGetResponse200) & {
  headers: Headers;
};
export type listContactMailsApiContactsContactIdMailsGetResponseError = (listContactMailsApiContactsContactIdMailsGetResponse422) & {
  headers: Headers;
};

export type listContactMailsApiContactsContactIdMailsGetResponse = (listContactMailsApiContactsContactIdMailsGetResponseSuccess | listContactMailsApiContactsContactIdMailsGetResponseError)

export const getListContactMailsApiContactsContactIdMailsGetUrl = (contactId: string,
    params?: ListContactMailsApiContactsContactIdMailsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/contacts/${contactId}/mails?${stringifiedParams}` : `/api/contacts/${contactId}/mails`
}

export const listContactMailsApiContactsContactIdMailsGet = async (contactId: string,
    params?: ListContactMailsApiContactsContactIdMailsGetParams, options?: RequestInit): Promise<listContactMailsApiContactsContactIdMailsGetResponse> => {

  return customInstance<listContactMailsApiContactsContactIdMailsGetResponse>(getListContactMailsApiContactsContactIdMailsGetUrl(contactId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListContactMailsApiContactsContactIdMailsGetQueryKey = (contactId: string,
    params?: ListContactMailsApiContactsContactIdMailsGetParams,) => {
    return [
    `/api/contacts/${contactId}/mails`, ...(params ? [params] : [])
    ] as const;
    }


export const getListContactMailsApiContactsContactIdMailsGetQueryOptions = <TData = Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError = HTTPValidationError>(contactId: string,
    params?: ListContactMailsApiContactsContactIdMailsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListContactMailsApiContactsContactIdMailsGetQueryKey(contactId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>> = ({ signal }) => listContactMailsApiContactsContactIdMailsGet(contactId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(contactId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListContactMailsApiContactsContactIdMailsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>>
export type ListContactMailsApiContactsContactIdMailsGetQueryError = HTTPValidationError


export function useListContactMailsApiContactsContactIdMailsGet<TData = Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError = HTTPValidationError>(
 contactId: string,
    params: undefined |  ListContactMailsApiContactsContactIdMailsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>,
          TError,
          Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListContactMailsApiContactsContactIdMailsGet<TData = Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError = HTTPValidationError>(
 contactId: string,
    params?: ListContactMailsApiContactsContactIdMailsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>,
          TError,
          Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListContactMailsApiContactsContactIdMailsGet<TData = Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError = HTTPValidationError>(
 contactId: string,
    params?: ListContactMailsApiContactsContactIdMailsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Contact Mails
 */

export function useListContactMailsApiContactsContactIdMailsGet<TData = Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError = HTTPValidationError>(
 contactId: string,
    params?: ListContactMailsApiContactsContactIdMailsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listContactMailsApiContactsContactIdMailsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListContactMailsApiContactsContactIdMailsGetQueryOptions(contactId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Remove an AI-assigned mail from a contact (delete the ContactAssignment row).
 * @summary Unlink Contact Mail
 */
export type unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponse204 = {
  data: void
  status: 204
}

export type unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponseSuccess = (unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponse204) & {
  headers: Headers;
};
export type unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponseError = (unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponse422) & {
  headers: Headers;
};

export type unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponse = (unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponseSuccess | unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponseError)

export const getUnlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteUrl = (contactId: string,
    assignmentId: string,) => {




  return `/api/contacts/${contactId}/mails/${assignmentId}`
}

export const unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete = async (contactId: string,
    assignmentId: string, options?: RequestInit): Promise<unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponse> => {

  return customInstance<unlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteResponse>(getUnlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteUrl(contactId,assignmentId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getUnlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete>>, TError,{contactId: string;assignmentId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete>>, TError,{contactId: string;assignmentId: string}, TContext> => {

const mutationKey = ['unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete>>, {contactId: string;assignmentId: string}> = (props) => {
          const {contactId,assignmentId} = props ?? {};

          return  unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete(contactId,assignmentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete>>>

    export type UnlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Unlink Contact Mail
 */
export const useUnlinkContactMailApiContactsContactIdMailsAssignmentIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete>>, TError,{contactId: string;assignmentId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unlinkContactMailApiContactsContactIdMailsAssignmentIdDelete>>,
        TError,
        {contactId: string;assignmentId: string},
        TContext
      > => {
      return useMutation(getUnlinkContactMailApiContactsContactIdMailsAssignmentIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Assign an email address to a contact.

Adds the email to the contact's ``emails`` JSON array (if not already
present) and triggers a CardDAV write-back to persist the change
in the upstream address book.  Also updates the Valkey cache so
subsequent matching resolves immediately.
 * @summary Assign Email To Contact
 */
export type assignEmailToContactApiContactsContactIdEmailsPostResponse201 = {
  data: AssignEmailResponse
  status: 201
}

export type assignEmailToContactApiContactsContactIdEmailsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type assignEmailToContactApiContactsContactIdEmailsPostResponseSuccess = (assignEmailToContactApiContactsContactIdEmailsPostResponse201) & {
  headers: Headers;
};
export type assignEmailToContactApiContactsContactIdEmailsPostResponseError = (assignEmailToContactApiContactsContactIdEmailsPostResponse422) & {
  headers: Headers;
};

export type assignEmailToContactApiContactsContactIdEmailsPostResponse = (assignEmailToContactApiContactsContactIdEmailsPostResponseSuccess | assignEmailToContactApiContactsContactIdEmailsPostResponseError)

export const getAssignEmailToContactApiContactsContactIdEmailsPostUrl = (contactId: string,) => {




  return `/api/contacts/${contactId}/emails`
}

export const assignEmailToContactApiContactsContactIdEmailsPost = async (contactId: string,
    assignEmailRequest: AssignEmailRequest, options?: RequestInit): Promise<assignEmailToContactApiContactsContactIdEmailsPostResponse> => {

  return customInstance<assignEmailToContactApiContactsContactIdEmailsPostResponse>(getAssignEmailToContactApiContactsContactIdEmailsPostUrl(contactId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignEmailRequest,)
  }
);}




export const getAssignEmailToContactApiContactsContactIdEmailsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignEmailToContactApiContactsContactIdEmailsPost>>, TError,{contactId: string;data: AssignEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof assignEmailToContactApiContactsContactIdEmailsPost>>, TError,{contactId: string;data: AssignEmailRequest}, TContext> => {

const mutationKey = ['assignEmailToContactApiContactsContactIdEmailsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignEmailToContactApiContactsContactIdEmailsPost>>, {contactId: string;data: AssignEmailRequest}> = (props) => {
          const {contactId,data} = props ?? {};

          return  assignEmailToContactApiContactsContactIdEmailsPost(contactId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignEmailToContactApiContactsContactIdEmailsPostMutationResult = NonNullable<Awaited<ReturnType<typeof assignEmailToContactApiContactsContactIdEmailsPost>>>
    export type AssignEmailToContactApiContactsContactIdEmailsPostMutationBody = AssignEmailRequest
    export type AssignEmailToContactApiContactsContactIdEmailsPostMutationError = HTTPValidationError

    /**
 * @summary Assign Email To Contact
 */
export const useAssignEmailToContactApiContactsContactIdEmailsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignEmailToContactApiContactsContactIdEmailsPost>>, TError,{contactId: string;data: AssignEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignEmailToContactApiContactsContactIdEmailsPost>>,
        TError,
        {contactId: string;data: AssignEmailRequest},
        TContext
      > => {
      return useMutation(getAssignEmailToContactApiContactsContactIdEmailsPostMutationOptions(options), queryClient);
    }
    /**
 * Remove an email address from a contact.

Removes the email from the contact's ``emails`` JSON array and
triggers a CardDAV write-back to persist the change in the upstream
address book.  Also invalidates the Valkey cache entry.
 * @summary Remove Email From Contact Endpoint
 */
export type removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponse200 = {
  data: RemoveEmailResponse
  status: 200
}

export type removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponseSuccess = (removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponse200) & {
  headers: Headers;
};
export type removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponseError = (removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponse422) & {
  headers: Headers;
};

export type removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponse = (removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponseSuccess | removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponseError)

export const getRemoveEmailFromContactEndpointApiContactsContactIdEmailsDeleteUrl = (contactId: string,) => {




  return `/api/contacts/${contactId}/emails`
}

export const removeEmailFromContactEndpointApiContactsContactIdEmailsDelete = async (contactId: string,
    removeEmailRequest: RemoveEmailRequest, options?: RequestInit): Promise<removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponse> => {

  return customInstance<removeEmailFromContactEndpointApiContactsContactIdEmailsDeleteResponse>(getRemoveEmailFromContactEndpointApiContactsContactIdEmailsDeleteUrl(contactId),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      removeEmailRequest,)
  }
);}




export const getRemoveEmailFromContactEndpointApiContactsContactIdEmailsDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeEmailFromContactEndpointApiContactsContactIdEmailsDelete>>, TError,{contactId: string;data: RemoveEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeEmailFromContactEndpointApiContactsContactIdEmailsDelete>>, TError,{contactId: string;data: RemoveEmailRequest}, TContext> => {

const mutationKey = ['removeEmailFromContactEndpointApiContactsContactIdEmailsDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeEmailFromContactEndpointApiContactsContactIdEmailsDelete>>, {contactId: string;data: RemoveEmailRequest}> = (props) => {
          const {contactId,data} = props ?? {};

          return  removeEmailFromContactEndpointApiContactsContactIdEmailsDelete(contactId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveEmailFromContactEndpointApiContactsContactIdEmailsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeEmailFromContactEndpointApiContactsContactIdEmailsDelete>>>
    export type RemoveEmailFromContactEndpointApiContactsContactIdEmailsDeleteMutationBody = RemoveEmailRequest
    export type RemoveEmailFromContactEndpointApiContactsContactIdEmailsDeleteMutationError = HTTPValidationError

    /**
 * @summary Remove Email From Contact Endpoint
 */
export const useRemoveEmailFromContactEndpointApiContactsContactIdEmailsDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeEmailFromContactEndpointApiContactsContactIdEmailsDelete>>, TError,{contactId: string;data: RemoveEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeEmailFromContactEndpointApiContactsContactIdEmailsDelete>>,
        TError,
        {contactId: string;data: RemoveEmailRequest},
        TContext
      > => {
      return useMutation(getRemoveEmailFromContactEndpointApiContactsContactIdEmailsDeleteMutationOptions(options), queryClient);
    }
