/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListQueueApiQueueGetParams,
  TrackedEmailListResponse,
  TrackedEmailResponse
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List tracked emails in the processing queue for the current user.
 * @summary List Queue
 */
export type listQueueApiQueueGetResponse200 = {
  data: TrackedEmailListResponse
  status: 200
}

export type listQueueApiQueueGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listQueueApiQueueGetResponseSuccess = (listQueueApiQueueGetResponse200) & {
  headers: Headers;
};
export type listQueueApiQueueGetResponseError = (listQueueApiQueueGetResponse422) & {
  headers: Headers;
};

export type listQueueApiQueueGetResponse = (listQueueApiQueueGetResponseSuccess | listQueueApiQueueGetResponseError)

export const getListQueueApiQueueGetUrl = (params?: ListQueueApiQueueGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/queue?${stringifiedParams}` : `/api/queue`
}

export const listQueueApiQueueGet = async (params?: ListQueueApiQueueGetParams, options?: RequestInit): Promise<listQueueApiQueueGetResponse> => {

  return customInstance<listQueueApiQueueGetResponse>(getListQueueApiQueueGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListQueueApiQueueGetQueryKey = (params?: ListQueueApiQueueGetParams,) => {
    return [
    `/api/queue`, ...(params ? [params] : [])
    ] as const;
    }


export const getListQueueApiQueueGetQueryOptions = <TData = Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError = HTTPValidationError>(params?: ListQueueApiQueueGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListQueueApiQueueGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listQueueApiQueueGet>>> = ({ signal }) => listQueueApiQueueGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListQueueApiQueueGetQueryResult = NonNullable<Awaited<ReturnType<typeof listQueueApiQueueGet>>>
export type ListQueueApiQueueGetQueryError = HTTPValidationError


export function useListQueueApiQueueGet<TData = Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError = HTTPValidationError>(
 params: undefined |  ListQueueApiQueueGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQueueApiQueueGet>>,
          TError,
          Awaited<ReturnType<typeof listQueueApiQueueGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQueueApiQueueGet<TData = Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError = HTTPValidationError>(
 params?: ListQueueApiQueueGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQueueApiQueueGet>>,
          TError,
          Awaited<ReturnType<typeof listQueueApiQueueGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQueueApiQueueGet<TData = Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError = HTTPValidationError>(
 params?: ListQueueApiQueueGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Queue
 */

export function useListQueueApiQueueGet<TData = Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError = HTTPValidationError>(
 params?: ListQueueApiQueueGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueueApiQueueGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListQueueApiQueueGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Reset a failed tracked email to queued status for reprocessing.
 * @summary Retry Email
 */
export type retryEmailApiQueueEmailIdRetryPostResponse200 = {
  data: TrackedEmailResponse
  status: 200
}

export type retryEmailApiQueueEmailIdRetryPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type retryEmailApiQueueEmailIdRetryPostResponseSuccess = (retryEmailApiQueueEmailIdRetryPostResponse200) & {
  headers: Headers;
};
export type retryEmailApiQueueEmailIdRetryPostResponseError = (retryEmailApiQueueEmailIdRetryPostResponse422) & {
  headers: Headers;
};

export type retryEmailApiQueueEmailIdRetryPostResponse = (retryEmailApiQueueEmailIdRetryPostResponseSuccess | retryEmailApiQueueEmailIdRetryPostResponseError)

export const getRetryEmailApiQueueEmailIdRetryPostUrl = (emailId: string,) => {




  return `/api/queue/${emailId}/retry`
}

export const retryEmailApiQueueEmailIdRetryPost = async (emailId: string, options?: RequestInit): Promise<retryEmailApiQueueEmailIdRetryPostResponse> => {

  return customInstance<retryEmailApiQueueEmailIdRetryPostResponse>(getRetryEmailApiQueueEmailIdRetryPostUrl(emailId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getRetryEmailApiQueueEmailIdRetryPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retryEmailApiQueueEmailIdRetryPost>>, TError,{emailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof retryEmailApiQueueEmailIdRetryPost>>, TError,{emailId: string}, TContext> => {

const mutationKey = ['retryEmailApiQueueEmailIdRetryPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof retryEmailApiQueueEmailIdRetryPost>>, {emailId: string}> = (props) => {
          const {emailId} = props ?? {};

          return  retryEmailApiQueueEmailIdRetryPost(emailId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RetryEmailApiQueueEmailIdRetryPostMutationResult = NonNullable<Awaited<ReturnType<typeof retryEmailApiQueueEmailIdRetryPost>>>

    export type RetryEmailApiQueueEmailIdRetryPostMutationError = HTTPValidationError

    /**
 * @summary Retry Email
 */
export const useRetryEmailApiQueueEmailIdRetryPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof retryEmailApiQueueEmailIdRetryPost>>, TError,{emailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof retryEmailApiQueueEmailIdRetryPost>>,
        TError,
        {emailId: string},
        TContext
      > => {
      return useMutation(getRetryEmailApiQueueEmailIdRetryPostMutationOptions(options), queryClient);
    }


/**
 * Re-queue any tracked email for reprocessing.
 * @summary Reprocess Email
 */
export type reprocessEmailApiQueueEmailIdReprocessPostResponse = {
  data: TrackedEmailResponse;
  status: number;
  headers: Headers;
};

export const getReprocessEmailApiQueueEmailIdReprocessPostUrl = (emailId: string,) => {
  return `/api/queue/${emailId}/reprocess`;
};

export const reprocessEmailApiQueueEmailIdReprocessPost = async (emailId: string, options?: RequestInit): Promise<reprocessEmailApiQueueEmailIdReprocessPostResponse> => {
  return customInstance<reprocessEmailApiQueueEmailIdReprocessPostResponse>(getReprocessEmailApiQueueEmailIdReprocessPostUrl(emailId),
  {
    ...options,
    method: 'POST'
  });
};

export const getReprocessEmailApiQueueEmailIdReprocessPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof reprocessEmailApiQueueEmailIdReprocessPost>>, TError, {emailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof reprocessEmailApiQueueEmailIdReprocessPost>>, TError, {emailId: string}, TContext> => {
  const mutationKey = ['reprocessEmailApiQueueEmailIdReprocessPost'];
  const {mutation: mutationOptions, request: requestOptions} = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
        options
        : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: { mutationKey }, request: undefined};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof reprocessEmailApiQueueEmailIdReprocessPost>>, {emailId: string}> = (props) => {
    const {emailId} = props ?? {};
    return reprocessEmailApiQueueEmailIdReprocessPost(emailId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReprocessEmailApiQueueEmailIdReprocessPostMutationResult = NonNullable<Awaited<ReturnType<typeof reprocessEmailApiQueueEmailIdReprocessPost>>>;
export type ReprocessEmailApiQueueEmailIdReprocessPostMutationError = HTTPValidationError;

/**
 * @summary Reprocess Email
 */
export const useReprocessEmailApiQueueEmailIdReprocessPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof reprocessEmailApiQueueEmailIdReprocessPost>>, TError, {emailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reprocessEmailApiQueueEmailIdReprocessPost>>,
        TError,
        {emailId: string},
        TContext
      > => {
      return useMutation(getReprocessEmailApiQueueEmailIdReprocessPostMutationOptions(options), queryClient);
    }


/**
 * Request cancellation of a processing email.
 * @summary Cancel Email
 */
export type cancelEmailApiQueueEmailIdCancelPostResponse = {
  data: TrackedEmailResponse;
  status: number;
  headers: Headers;
};

export const getCancelEmailApiQueueEmailIdCancelPostUrl = (emailId: string,) => {
  return `/api/queue/${emailId}/cancel`;
};

export const cancelEmailApiQueueEmailIdCancelPost = async (emailId: string, options?: RequestInit): Promise<cancelEmailApiQueueEmailIdCancelPostResponse> => {
  return customInstance<cancelEmailApiQueueEmailIdCancelPostResponse>(getCancelEmailApiQueueEmailIdCancelPostUrl(emailId),
  {
    ...options,
    method: 'POST'
  });
};

export const getCancelEmailApiQueueEmailIdCancelPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof cancelEmailApiQueueEmailIdCancelPost>>, TError, {emailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelEmailApiQueueEmailIdCancelPost>>, TError, {emailId: string}, TContext> => {
  const mutationKey = ['cancelEmailApiQueueEmailIdCancelPost'];
  const {mutation: mutationOptions, request: requestOptions} = options ?
        options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
        options
        : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: { mutationKey }, request: undefined};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelEmailApiQueueEmailIdCancelPost>>, {emailId: string}> = (props) => {
    const {emailId} = props ?? {};
    return cancelEmailApiQueueEmailIdCancelPost(emailId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelEmailApiQueueEmailIdCancelPostMutationResult = NonNullable<Awaited<ReturnType<typeof cancelEmailApiQueueEmailIdCancelPost>>>;
export type CancelEmailApiQueueEmailIdCancelPostMutationError = HTTPValidationError;

/**
 * @summary Cancel Email
 */
export const useCancelEmailApiQueueEmailIdCancelPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof cancelEmailApiQueueEmailIdCancelPost>>, TError, {emailId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelEmailApiQueueEmailIdCancelPost>>,
        TError,
        {emailId: string},
        TContext
      > => {
      return useMutation(getCancelEmailApiQueueEmailIdCancelPostMutationOptions(options), queryClient);
    }
