/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignedFolderListResponse,
  FolderSummaryListResponse,
  HTTPValidationError,
  ListAssignedFoldersApiFoldersGetParams,
  SmartFolderReprocessResponse,
  SmartFolderResetResponse
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List assigned folders with pagination and optional folder filter.
 * @summary List Assigned Folders
 */
export type listAssignedFoldersApiFoldersGetResponse200 = {
  data: AssignedFolderListResponse
  status: 200
}

export type listAssignedFoldersApiFoldersGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listAssignedFoldersApiFoldersGetResponseSuccess = (listAssignedFoldersApiFoldersGetResponse200) & {
  headers: Headers;
};
export type listAssignedFoldersApiFoldersGetResponseError = (listAssignedFoldersApiFoldersGetResponse422) & {
  headers: Headers;
};

export type listAssignedFoldersApiFoldersGetResponse = (listAssignedFoldersApiFoldersGetResponseSuccess | listAssignedFoldersApiFoldersGetResponseError)

export const getListAssignedFoldersApiFoldersGetUrl = (params?: ListAssignedFoldersApiFoldersGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/folders?${stringifiedParams}` : `/api/folders`
}

export const listAssignedFoldersApiFoldersGet = async (params?: ListAssignedFoldersApiFoldersGetParams, options?: RequestInit): Promise<listAssignedFoldersApiFoldersGetResponse> => {

  return customInstance<listAssignedFoldersApiFoldersGetResponse>(getListAssignedFoldersApiFoldersGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAssignedFoldersApiFoldersGetQueryKey = (params?: ListAssignedFoldersApiFoldersGetParams,) => {
    return [
    `/api/folders`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAssignedFoldersApiFoldersGetQueryOptions = <TData = Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError = HTTPValidationError>(params?: ListAssignedFoldersApiFoldersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAssignedFoldersApiFoldersGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>> = ({ signal }) => listAssignedFoldersApiFoldersGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAssignedFoldersApiFoldersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>>
export type ListAssignedFoldersApiFoldersGetQueryError = HTTPValidationError


export function useListAssignedFoldersApiFoldersGet<TData = Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError = HTTPValidationError>(
 params: undefined |  ListAssignedFoldersApiFoldersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>,
          TError,
          Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAssignedFoldersApiFoldersGet<TData = Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError = HTTPValidationError>(
 params?: ListAssignedFoldersApiFoldersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>,
          TError,
          Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAssignedFoldersApiFoldersGet<TData = Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError = HTTPValidationError>(
 params?: ListAssignedFoldersApiFoldersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Assigned Folders
 */

export function useListAssignedFoldersApiFoldersGet<TData = Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError = HTTPValidationError>(
 params?: ListAssignedFoldersApiFoldersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignedFoldersApiFoldersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAssignedFoldersApiFoldersGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get a summary of unique folders with usage counts.
 * @summary Get Folder Summary
 */
export type getFolderSummaryApiFoldersSummaryGetResponse200 = {
  data: FolderSummaryListResponse
  status: 200
}

export type getFolderSummaryApiFoldersSummaryGetResponseSuccess = (getFolderSummaryApiFoldersSummaryGetResponse200) & {
  headers: Headers;
};
;

export type getFolderSummaryApiFoldersSummaryGetResponse = (getFolderSummaryApiFoldersSummaryGetResponseSuccess)

export const getGetFolderSummaryApiFoldersSummaryGetUrl = () => {




  return `/api/folders/summary`
}

export const getFolderSummaryApiFoldersSummaryGet = async ( options?: RequestInit): Promise<getFolderSummaryApiFoldersSummaryGetResponse> => {

  return customInstance<getFolderSummaryApiFoldersSummaryGetResponse>(getGetFolderSummaryApiFoldersSummaryGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFolderSummaryApiFoldersSummaryGetQueryKey = () => {
    return [
    `/api/folders/summary`
    ] as const;
    }


export const getGetFolderSummaryApiFoldersSummaryGetQueryOptions = <TData = Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFolderSummaryApiFoldersSummaryGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>> = ({ signal }) => getFolderSummaryApiFoldersSummaryGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFolderSummaryApiFoldersSummaryGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>>
export type GetFolderSummaryApiFoldersSummaryGetQueryError = unknown


export function useGetFolderSummaryApiFoldersSummaryGet<TData = Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFolderSummaryApiFoldersSummaryGet<TData = Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>,
          TError,
          Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFolderSummaryApiFoldersSummaryGet<TData = Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Folder Summary
 */

export function useGetFolderSummaryApiFoldersSummaryGet<TData = Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFolderSummaryApiFoldersSummaryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFolderSummaryApiFoldersSummaryGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Fully reset a smart folder.

1. For each mail account the user owns, connect via IMAP, move all
   messages in *folder_name* back to INBOX, then delete the folder.
2. Delete all ``assigned_folders`` records for this folder name.
3. Delete all ``folder_change_logs`` records for this folder name.
4. Reset ``tracked_emails`` entries for the affected mail UIDs back to
   ``pending`` so the next scheduler cycle re-processes them through the
   AI pipeline.

Returns a summary of what happened per account.
 * @summary Reset Smart Folder
 */
export type resetSmartFolderApiFoldersByNameFolderNameDeleteResponse200 = {
  data: SmartFolderResetResponse
  status: 200
}

export type resetSmartFolderApiFoldersByNameFolderNameDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type resetSmartFolderApiFoldersByNameFolderNameDeleteResponseSuccess = (resetSmartFolderApiFoldersByNameFolderNameDeleteResponse200) & {
  headers: Headers;
};
export type resetSmartFolderApiFoldersByNameFolderNameDeleteResponseError = (resetSmartFolderApiFoldersByNameFolderNameDeleteResponse422) & {
  headers: Headers;
};

export type resetSmartFolderApiFoldersByNameFolderNameDeleteResponse = (resetSmartFolderApiFoldersByNameFolderNameDeleteResponseSuccess | resetSmartFolderApiFoldersByNameFolderNameDeleteResponseError)

export const getResetSmartFolderApiFoldersByNameFolderNameDeleteUrl = (folderName: string,) => {




  return `/api/folders/by-name/${folderName}`
}

export const resetSmartFolderApiFoldersByNameFolderNameDelete = async (folderName: string, options?: RequestInit): Promise<resetSmartFolderApiFoldersByNameFolderNameDeleteResponse> => {

  return customInstance<resetSmartFolderApiFoldersByNameFolderNameDeleteResponse>(getResetSmartFolderApiFoldersByNameFolderNameDeleteUrl(folderName),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getResetSmartFolderApiFoldersByNameFolderNameDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetSmartFolderApiFoldersByNameFolderNameDelete>>, TError,{folderName: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resetSmartFolderApiFoldersByNameFolderNameDelete>>, TError,{folderName: string}, TContext> => {

const mutationKey = ['resetSmartFolderApiFoldersByNameFolderNameDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetSmartFolderApiFoldersByNameFolderNameDelete>>, {folderName: string}> = (props) => {
          const {folderName} = props ?? {};

          return  resetSmartFolderApiFoldersByNameFolderNameDelete(folderName,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResetSmartFolderApiFoldersByNameFolderNameDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof resetSmartFolderApiFoldersByNameFolderNameDelete>>>

    export type ResetSmartFolderApiFoldersByNameFolderNameDeleteMutationError = HTTPValidationError

    /**
 * @summary Reset Smart Folder
 */
export const useResetSmartFolderApiFoldersByNameFolderNameDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetSmartFolderApiFoldersByNameFolderNameDelete>>, TError,{folderName: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetSmartFolderApiFoldersByNameFolderNameDelete>>,
        TError,
        {folderName: string},
        TContext
      > => {
      return useMutation(getResetSmartFolderApiFoldersByNameFolderNameDeleteMutationOptions(options), queryClient);
    }
    /**
 * Re-queue all emails in a folder for AI reprocessing.

Unlike ``reset_smart_folder``, this keeps the IMAP folder intact and
does **not** delete ``AssignedFolder`` or ``FolderChangeLog`` records.
Emails stay where they are; only their ``TrackedEmail`` status is set
back to ``QUEUED`` so the AI pipeline re-analyses them.

Works for both smart folders (looks up via ``AssignedFolder`` records)
and regular IMAP folders (falls back to ``TrackedEmail.current_folder``).

Useful when AI prompts or smart folder rules have changed and the
user wants to re-evaluate existing folder assignments without losing the
current folder structure.
 * @summary Reprocess Smart Folder
 */
export type reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponse200 = {
  data: SmartFolderReprocessResponse
  status: 200
}

export type reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponseSuccess = (reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponse200) & {
  headers: Headers;
};
export type reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponseError = (reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponse422) & {
  headers: Headers;
};

export type reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponse = (reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponseSuccess | reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponseError)

export const getReprocessSmartFolderApiFoldersByNameFolderNameReprocessPostUrl = (folderName: string,) => {




  return `/api/folders/by-name/${folderName}/reprocess`
}

export const reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost = async (folderName: string, options?: RequestInit): Promise<reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponse> => {

  return customInstance<reprocessSmartFolderApiFoldersByNameFolderNameReprocessPostResponse>(getReprocessSmartFolderApiFoldersByNameFolderNameReprocessPostUrl(folderName),
  {
    ...options,
    method: 'POST'


  }
);}




export const getReprocessSmartFolderApiFoldersByNameFolderNameReprocessPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost>>, TError,{folderName: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost>>, TError,{folderName: string}, TContext> => {

const mutationKey = ['reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost>>, {folderName: string}> = (props) => {
          const {folderName} = props ?? {};

          return  reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost(folderName,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReprocessSmartFolderApiFoldersByNameFolderNameReprocessPostMutationResult = NonNullable<Awaited<ReturnType<typeof reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost>>>

    export type ReprocessSmartFolderApiFoldersByNameFolderNameReprocessPostMutationError = HTTPValidationError

    /**
 * @summary Reprocess Smart Folder
 */
export const useReprocessSmartFolderApiFoldersByNameFolderNameReprocessPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost>>, TError,{folderName: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reprocessSmartFolderApiFoldersByNameFolderNameReprocessPost>>,
        TError,
        {folderName: string},
        TContext
      > => {
      return useMutation(getReprocessSmartFolderApiFoldersByNameFolderNameReprocessPostMutationOptions(options), queryClient);
    }
    /**
 * Delete an assigned folder record.
 * @summary Delete Assigned Folder
 */
export type deleteAssignedFolderApiFoldersFolderIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteAssignedFolderApiFoldersFolderIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteAssignedFolderApiFoldersFolderIdDeleteResponseSuccess = (deleteAssignedFolderApiFoldersFolderIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteAssignedFolderApiFoldersFolderIdDeleteResponseError = (deleteAssignedFolderApiFoldersFolderIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteAssignedFolderApiFoldersFolderIdDeleteResponse = (deleteAssignedFolderApiFoldersFolderIdDeleteResponseSuccess | deleteAssignedFolderApiFoldersFolderIdDeleteResponseError)

export const getDeleteAssignedFolderApiFoldersFolderIdDeleteUrl = (folderId: string,) => {




  return `/api/folders/${folderId}`
}

export const deleteAssignedFolderApiFoldersFolderIdDelete = async (folderId: string, options?: RequestInit): Promise<deleteAssignedFolderApiFoldersFolderIdDeleteResponse> => {

  return customInstance<deleteAssignedFolderApiFoldersFolderIdDeleteResponse>(getDeleteAssignedFolderApiFoldersFolderIdDeleteUrl(folderId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAssignedFolderApiFoldersFolderIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssignedFolderApiFoldersFolderIdDelete>>, TError,{folderId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAssignedFolderApiFoldersFolderIdDelete>>, TError,{folderId: string}, TContext> => {

const mutationKey = ['deleteAssignedFolderApiFoldersFolderIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAssignedFolderApiFoldersFolderIdDelete>>, {folderId: string}> = (props) => {
          const {folderId} = props ?? {};

          return  deleteAssignedFolderApiFoldersFolderIdDelete(folderId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAssignedFolderApiFoldersFolderIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAssignedFolderApiFoldersFolderIdDelete>>>

    export type DeleteAssignedFolderApiFoldersFolderIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Assigned Folder
 */
export const useDeleteAssignedFolderApiFoldersFolderIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssignedFolderApiFoldersFolderIdDelete>>, TError,{folderId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAssignedFolderApiFoldersFolderIdDelete>>,
        TError,
        {folderId: string},
        TContext
      > => {
      return useMutation(getDeleteAssignedFolderApiFoldersFolderIdDeleteMutationOptions(options), queryClient);
    }
