/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CalDAVConfigResponse,
  CalDAVConfigUpdate,
  CalDAVTestRequest,
  CalDAVTestResponse,
  HTTPValidationError
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get CalDAV configuration (credentials excluded).

Returns ``None`` (HTTP 200 with ``null`` body) when no config exists.
This is intentional: ``null`` tells the frontend "not configured yet"
and renders the setup form, whereas a 404 would trigger an error state.
 * @summary Get Config
 */
export type getConfigApiCalendarConfigGetResponse200 = {
  data: CalDAVConfigResponse | null
  status: 200
}

export type getConfigApiCalendarConfigGetResponseSuccess = (getConfigApiCalendarConfigGetResponse200) & {
  headers: Headers;
};
;

export type getConfigApiCalendarConfigGetResponse = (getConfigApiCalendarConfigGetResponseSuccess)

export const getGetConfigApiCalendarConfigGetUrl = () => {




  return `/api/calendar/config`
}

export const getConfigApiCalendarConfigGet = async ( options?: RequestInit): Promise<getConfigApiCalendarConfigGetResponse> => {

  return customInstance<getConfigApiCalendarConfigGetResponse>(getGetConfigApiCalendarConfigGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConfigApiCalendarConfigGetQueryKey = () => {
    return [
    `/api/calendar/config`
    ] as const;
    }


export const getGetConfigApiCalendarConfigGetQueryOptions = <TData = Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConfigApiCalendarConfigGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>> = ({ signal }) => getConfigApiCalendarConfigGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConfigApiCalendarConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>>
export type GetConfigApiCalendarConfigGetQueryError = unknown


export function useGetConfigApiCalendarConfigGet<TData = Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>,
          TError,
          Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigApiCalendarConfigGet<TData = Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>,
          TError,
          Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigApiCalendarConfigGet<TData = Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Config
 */

export function useGetConfigApiCalendarConfigGet<TData = Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigApiCalendarConfigGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConfigApiCalendarConfigGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Create or update CalDAV configuration.

Credentials are encrypted before storage.
 * @summary Update Config
 */
export type updateConfigApiCalendarConfigPutResponse200 = {
  data: CalDAVConfigResponse
  status: 200
}

export type updateConfigApiCalendarConfigPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateConfigApiCalendarConfigPutResponseSuccess = (updateConfigApiCalendarConfigPutResponse200) & {
  headers: Headers;
};
export type updateConfigApiCalendarConfigPutResponseError = (updateConfigApiCalendarConfigPutResponse422) & {
  headers: Headers;
};

export type updateConfigApiCalendarConfigPutResponse = (updateConfigApiCalendarConfigPutResponseSuccess | updateConfigApiCalendarConfigPutResponseError)

export const getUpdateConfigApiCalendarConfigPutUrl = () => {




  return `/api/calendar/config`
}

export const updateConfigApiCalendarConfigPut = async (calDAVConfigUpdate: CalDAVConfigUpdate, options?: RequestInit): Promise<updateConfigApiCalendarConfigPutResponse> => {

  return customInstance<updateConfigApiCalendarConfigPutResponse>(getUpdateConfigApiCalendarConfigPutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      calDAVConfigUpdate,)
  }
);}




export const getUpdateConfigApiCalendarConfigPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConfigApiCalendarConfigPut>>, TError,{data: CalDAVConfigUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateConfigApiCalendarConfigPut>>, TError,{data: CalDAVConfigUpdate}, TContext> => {

const mutationKey = ['updateConfigApiCalendarConfigPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateConfigApiCalendarConfigPut>>, {data: CalDAVConfigUpdate}> = (props) => {
          const {data} = props ?? {};

          return  updateConfigApiCalendarConfigPut(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateConfigApiCalendarConfigPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateConfigApiCalendarConfigPut>>>
    export type UpdateConfigApiCalendarConfigPutMutationBody = CalDAVConfigUpdate
    export type UpdateConfigApiCalendarConfigPutMutationError = HTTPValidationError

    /**
 * @summary Update Config
 */
export const useUpdateConfigApiCalendarConfigPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateConfigApiCalendarConfigPut>>, TError,{data: CalDAVConfigUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateConfigApiCalendarConfigPut>>,
        TError,
        {data: CalDAVConfigUpdate},
        TContext
      > => {
      return useMutation(getUpdateConfigApiCalendarConfigPutMutationOptions(options), queryClient);
    }
    /**
 * Test CalDAV connectivity.

Accepts credentials directly for pre-save testing.  Falls back to
stored configuration when no credentials are provided in the body.
 * @summary Test Config
 */
export type testConfigApiCalendarConfigTestPostResponse200 = {
  data: CalDAVTestResponse
  status: 200
}

export type testConfigApiCalendarConfigTestPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type testConfigApiCalendarConfigTestPostResponseSuccess = (testConfigApiCalendarConfigTestPostResponse200) & {
  headers: Headers;
};
export type testConfigApiCalendarConfigTestPostResponseError = (testConfigApiCalendarConfigTestPostResponse422) & {
  headers: Headers;
};

export type testConfigApiCalendarConfigTestPostResponse = (testConfigApiCalendarConfigTestPostResponseSuccess | testConfigApiCalendarConfigTestPostResponseError)

export const getTestConfigApiCalendarConfigTestPostUrl = () => {




  return `/api/calendar/config/test`
}

export const testConfigApiCalendarConfigTestPost = async (calDAVTestRequestNull?: CalDAVTestRequest | null, options?: RequestInit): Promise<testConfigApiCalendarConfigTestPostResponse> => {

  return customInstance<testConfigApiCalendarConfigTestPostResponse>(getTestConfigApiCalendarConfigTestPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      calDAVTestRequestNull,)
  }
);}




export const getTestConfigApiCalendarConfigTestPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testConfigApiCalendarConfigTestPost>>, TError,{data?: CalDAVTestRequest | null}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof testConfigApiCalendarConfigTestPost>>, TError,{data?: CalDAVTestRequest | null}, TContext> => {

const mutationKey = ['testConfigApiCalendarConfigTestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testConfigApiCalendarConfigTestPost>>, {data?: CalDAVTestRequest | null}> = (props) => {
          const {data} = props ?? {};

          return  testConfigApiCalendarConfigTestPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestConfigApiCalendarConfigTestPostMutationResult = NonNullable<Awaited<ReturnType<typeof testConfigApiCalendarConfigTestPost>>>
    export type TestConfigApiCalendarConfigTestPostMutationBody = CalDAVTestRequest | null | undefined
    export type TestConfigApiCalendarConfigTestPostMutationError = HTTPValidationError

    /**
 * @summary Test Config
 */
export const useTestConfigApiCalendarConfigTestPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testConfigApiCalendarConfigTestPost>>, TError,{data?: CalDAVTestRequest | null}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testConfigApiCalendarConfigTestPost>>,
        TError,
        {data?: CalDAVTestRequest | null},
        TContext
      > => {
      return useMutation(getTestConfigApiCalendarConfigTestPostMutationOptions(options), queryClient);
    }
