{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailassist.fullname" . }}
  labels:
    {{- include "mailassist.labels" . | nindent 4 }}
type: Opaque
data:
  APP_SECRET_KEY: {{ .Values.secrets.appSecretKey | b64enc | quote }}
  {{- if .Values.secrets.appSecretKeyOld }}
  APP_SECRET_KEY_OLD: {{ .Values.secrets.appSecretKeyOld | b64enc | quote }}
  {{- end }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  VALKEY_PASSWORD: {{ .Values.secrets.valkeyPassword | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | b64enc | quote }}
{{- end }}
