/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  PromptPreviewRequest,
  PromptPreviewResponse,
  PromptResponse,
  PromptUpdate,
  TemplateVariable
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List all prompts with defaults for each registered plugin.

Returns user-customized prompts where they exist, and default
prompts from the template files for the rest.
 * @summary List Prompts
 */
export type listPromptsApiPromptsGetResponse200 = {
  data: PromptResponse[]
  status: 200
}

export type listPromptsApiPromptsGetResponseSuccess = (listPromptsApiPromptsGetResponse200) & {
  headers: Headers;
};
;

export type listPromptsApiPromptsGetResponse = (listPromptsApiPromptsGetResponseSuccess)

export const getListPromptsApiPromptsGetUrl = () => {




  return `/api/prompts`
}

export const listPromptsApiPromptsGet = async ( options?: RequestInit): Promise<listPromptsApiPromptsGetResponse> => {

  return customInstance<listPromptsApiPromptsGetResponse>(getListPromptsApiPromptsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPromptsApiPromptsGetQueryKey = () => {
    return [
    `/api/prompts`
    ] as const;
    }


export const getListPromptsApiPromptsGetQueryOptions = <TData = Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPromptsApiPromptsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPromptsApiPromptsGet>>> = ({ signal }) => listPromptsApiPromptsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPromptsApiPromptsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPromptsApiPromptsGet>>>
export type ListPromptsApiPromptsGetQueryError = unknown


export function useListPromptsApiPromptsGet<TData = Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPromptsApiPromptsGet>>,
          TError,
          Awaited<ReturnType<typeof listPromptsApiPromptsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPromptsApiPromptsGet<TData = Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPromptsApiPromptsGet>>,
          TError,
          Awaited<ReturnType<typeof listPromptsApiPromptsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPromptsApiPromptsGet<TData = Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Prompts
 */

export function useListPromptsApiPromptsGet<TData = Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPromptsApiPromptsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPromptsApiPromptsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * List all available template variables with metadata.
 * @summary List Variables
 */
export type listVariablesApiPromptsVariablesGetResponse200 = {
  data: TemplateVariable[]
  status: 200
}

export type listVariablesApiPromptsVariablesGetResponseSuccess = (listVariablesApiPromptsVariablesGetResponse200) & {
  headers: Headers;
};
;

export type listVariablesApiPromptsVariablesGetResponse = (listVariablesApiPromptsVariablesGetResponseSuccess)

export const getListVariablesApiPromptsVariablesGetUrl = () => {




  return `/api/prompts/variables`
}

export const listVariablesApiPromptsVariablesGet = async ( options?: RequestInit): Promise<listVariablesApiPromptsVariablesGetResponse> => {

  return customInstance<listVariablesApiPromptsVariablesGetResponse>(getListVariablesApiPromptsVariablesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListVariablesApiPromptsVariablesGetQueryKey = () => {
    return [
    `/api/prompts/variables`
    ] as const;
    }


export const getListVariablesApiPromptsVariablesGetQueryOptions = <TData = Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVariablesApiPromptsVariablesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>> = ({ signal }) => listVariablesApiPromptsVariablesGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVariablesApiPromptsVariablesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>>
export type ListVariablesApiPromptsVariablesGetQueryError = unknown


export function useListVariablesApiPromptsVariablesGet<TData = Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>,
          TError,
          Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVariablesApiPromptsVariablesGet<TData = Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>,
          TError,
          Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVariablesApiPromptsVariablesGet<TData = Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Variables
 */

export function useListVariablesApiPromptsVariablesGet<TData = Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVariablesApiPromptsVariablesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVariablesApiPromptsVariablesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get the prompt for a specific AI function.

Returns the user-customized version if it exists, otherwise the default.
 * @summary Get Prompt
 */
export type getPromptApiPromptsFunctionTypeGetResponse200 = {
  data: PromptResponse
  status: 200
}

export type getPromptApiPromptsFunctionTypeGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getPromptApiPromptsFunctionTypeGetResponseSuccess = (getPromptApiPromptsFunctionTypeGetResponse200) & {
  headers: Headers;
};
export type getPromptApiPromptsFunctionTypeGetResponseError = (getPromptApiPromptsFunctionTypeGetResponse422) & {
  headers: Headers;
};

export type getPromptApiPromptsFunctionTypeGetResponse = (getPromptApiPromptsFunctionTypeGetResponseSuccess | getPromptApiPromptsFunctionTypeGetResponseError)

export const getGetPromptApiPromptsFunctionTypeGetUrl = (functionType: string,) => {




  return `/api/prompts/${functionType}`
}

export const getPromptApiPromptsFunctionTypeGet = async (functionType: string, options?: RequestInit): Promise<getPromptApiPromptsFunctionTypeGetResponse> => {

  return customInstance<getPromptApiPromptsFunctionTypeGetResponse>(getGetPromptApiPromptsFunctionTypeGetUrl(functionType),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPromptApiPromptsFunctionTypeGetQueryKey = (functionType: string,) => {
    return [
    `/api/prompts/${functionType}`
    ] as const;
    }


export const getGetPromptApiPromptsFunctionTypeGetQueryOptions = <TData = Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError = HTTPValidationError>(functionType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPromptApiPromptsFunctionTypeGetQueryKey(functionType);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>> = ({ signal }) => getPromptApiPromptsFunctionTypeGet(functionType, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(functionType), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPromptApiPromptsFunctionTypeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>>
export type GetPromptApiPromptsFunctionTypeGetQueryError = HTTPValidationError


export function useGetPromptApiPromptsFunctionTypeGet<TData = Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError = HTTPValidationError>(
 functionType: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>,
          TError,
          Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPromptApiPromptsFunctionTypeGet<TData = Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError = HTTPValidationError>(
 functionType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>,
          TError,
          Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPromptApiPromptsFunctionTypeGet<TData = Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError = HTTPValidationError>(
 functionType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Prompt
 */

export function useGetPromptApiPromptsFunctionTypeGet<TData = Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError = HTTPValidationError>(
 functionType: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPromptApiPromptsFunctionTypeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPromptApiPromptsFunctionTypeGetQueryOptions(functionType,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Create or update a custom prompt for an AI function.
 * @summary Update Prompt
 */
export type updatePromptApiPromptsFunctionTypePutResponse200 = {
  data: PromptResponse
  status: 200
}

export type updatePromptApiPromptsFunctionTypePutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updatePromptApiPromptsFunctionTypePutResponseSuccess = (updatePromptApiPromptsFunctionTypePutResponse200) & {
  headers: Headers;
};
export type updatePromptApiPromptsFunctionTypePutResponseError = (updatePromptApiPromptsFunctionTypePutResponse422) & {
  headers: Headers;
};

export type updatePromptApiPromptsFunctionTypePutResponse = (updatePromptApiPromptsFunctionTypePutResponseSuccess | updatePromptApiPromptsFunctionTypePutResponseError)

export const getUpdatePromptApiPromptsFunctionTypePutUrl = (functionType: string,) => {




  return `/api/prompts/${functionType}`
}

export const updatePromptApiPromptsFunctionTypePut = async (functionType: string,
    promptUpdate: PromptUpdate, options?: RequestInit): Promise<updatePromptApiPromptsFunctionTypePutResponse> => {

  return customInstance<updatePromptApiPromptsFunctionTypePutResponse>(getUpdatePromptApiPromptsFunctionTypePutUrl(functionType),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      promptUpdate,)
  }
);}




export const getUpdatePromptApiPromptsFunctionTypePutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePromptApiPromptsFunctionTypePut>>, TError,{functionType: string;data: PromptUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePromptApiPromptsFunctionTypePut>>, TError,{functionType: string;data: PromptUpdate}, TContext> => {

const mutationKey = ['updatePromptApiPromptsFunctionTypePut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePromptApiPromptsFunctionTypePut>>, {functionType: string;data: PromptUpdate}> = (props) => {
          const {functionType,data} = props ?? {};

          return  updatePromptApiPromptsFunctionTypePut(functionType,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePromptApiPromptsFunctionTypePutMutationResult = NonNullable<Awaited<ReturnType<typeof updatePromptApiPromptsFunctionTypePut>>>
    export type UpdatePromptApiPromptsFunctionTypePutMutationBody = PromptUpdate
    export type UpdatePromptApiPromptsFunctionTypePutMutationError = HTTPValidationError

    /**
 * @summary Update Prompt
 */
export const useUpdatePromptApiPromptsFunctionTypePut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePromptApiPromptsFunctionTypePut>>, TError,{functionType: string;data: PromptUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePromptApiPromptsFunctionTypePut>>,
        TError,
        {functionType: string;data: PromptUpdate},
        TContext
      > => {
      return useMutation(getUpdatePromptApiPromptsFunctionTypePutMutationOptions(options), queryClient);
    }
    /**
 * Reset a prompt to its default template by deleting the custom version.
 * @summary Reset Prompt
 */
export type resetPromptApiPromptsFunctionTypeResetPostResponse200 = {
  data: PromptResponse
  status: 200
}

export type resetPromptApiPromptsFunctionTypeResetPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type resetPromptApiPromptsFunctionTypeResetPostResponseSuccess = (resetPromptApiPromptsFunctionTypeResetPostResponse200) & {
  headers: Headers;
};
export type resetPromptApiPromptsFunctionTypeResetPostResponseError = (resetPromptApiPromptsFunctionTypeResetPostResponse422) & {
  headers: Headers;
};

export type resetPromptApiPromptsFunctionTypeResetPostResponse = (resetPromptApiPromptsFunctionTypeResetPostResponseSuccess | resetPromptApiPromptsFunctionTypeResetPostResponseError)

export const getResetPromptApiPromptsFunctionTypeResetPostUrl = (functionType: string,) => {




  return `/api/prompts/${functionType}/reset`
}

export const resetPromptApiPromptsFunctionTypeResetPost = async (functionType: string, options?: RequestInit): Promise<resetPromptApiPromptsFunctionTypeResetPostResponse> => {

  return customInstance<resetPromptApiPromptsFunctionTypeResetPostResponse>(getResetPromptApiPromptsFunctionTypeResetPostUrl(functionType),
  {
    ...options,
    method: 'POST'


  }
);}




export const getResetPromptApiPromptsFunctionTypeResetPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPromptApiPromptsFunctionTypeResetPost>>, TError,{functionType: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resetPromptApiPromptsFunctionTypeResetPost>>, TError,{functionType: string}, TContext> => {

const mutationKey = ['resetPromptApiPromptsFunctionTypeResetPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPromptApiPromptsFunctionTypeResetPost>>, {functionType: string}> = (props) => {
          const {functionType} = props ?? {};

          return  resetPromptApiPromptsFunctionTypeResetPost(functionType,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResetPromptApiPromptsFunctionTypeResetPostMutationResult = NonNullable<Awaited<ReturnType<typeof resetPromptApiPromptsFunctionTypeResetPost>>>

    export type ResetPromptApiPromptsFunctionTypeResetPostMutationError = HTTPValidationError

    /**
 * @summary Reset Prompt
 */
export const useResetPromptApiPromptsFunctionTypeResetPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPromptApiPromptsFunctionTypeResetPost>>, TError,{functionType: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetPromptApiPromptsFunctionTypeResetPost>>,
        TError,
        {functionType: string},
        TContext
      > => {
      return useMutation(getResetPromptApiPromptsFunctionTypeResetPostMutationOptions(options), queryClient);
    }
    /**
 * Render a prompt template with sample data for preview.

Uses realistic sample data enriched with the user's actual language
and timezone settings so the preview matches real pipeline output.
 * @summary Preview Prompt
 */
export type previewPromptApiPromptsFunctionTypePreviewPostResponse200 = {
  data: PromptPreviewResponse
  status: 200
}

export type previewPromptApiPromptsFunctionTypePreviewPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type previewPromptApiPromptsFunctionTypePreviewPostResponseSuccess = (previewPromptApiPromptsFunctionTypePreviewPostResponse200) & {
  headers: Headers;
};
export type previewPromptApiPromptsFunctionTypePreviewPostResponseError = (previewPromptApiPromptsFunctionTypePreviewPostResponse422) & {
  headers: Headers;
};

export type previewPromptApiPromptsFunctionTypePreviewPostResponse = (previewPromptApiPromptsFunctionTypePreviewPostResponseSuccess | previewPromptApiPromptsFunctionTypePreviewPostResponseError)

export const getPreviewPromptApiPromptsFunctionTypePreviewPostUrl = (functionType: string,) => {




  return `/api/prompts/${functionType}/preview`
}

export const previewPromptApiPromptsFunctionTypePreviewPost = async (functionType: string,
    promptPreviewRequest: PromptPreviewRequest, options?: RequestInit): Promise<previewPromptApiPromptsFunctionTypePreviewPostResponse> => {

  return customInstance<previewPromptApiPromptsFunctionTypePreviewPostResponse>(getPreviewPromptApiPromptsFunctionTypePreviewPostUrl(functionType),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      promptPreviewRequest,)
  }
);}




export const getPreviewPromptApiPromptsFunctionTypePreviewPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewPromptApiPromptsFunctionTypePreviewPost>>, TError,{functionType: string;data: PromptPreviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof previewPromptApiPromptsFunctionTypePreviewPost>>, TError,{functionType: string;data: PromptPreviewRequest}, TContext> => {

const mutationKey = ['previewPromptApiPromptsFunctionTypePreviewPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof previewPromptApiPromptsFunctionTypePreviewPost>>, {functionType: string;data: PromptPreviewRequest}> = (props) => {
          const {functionType,data} = props ?? {};

          return  previewPromptApiPromptsFunctionTypePreviewPost(functionType,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PreviewPromptApiPromptsFunctionTypePreviewPostMutationResult = NonNullable<Awaited<ReturnType<typeof previewPromptApiPromptsFunctionTypePreviewPost>>>
    export type PreviewPromptApiPromptsFunctionTypePreviewPostMutationBody = PromptPreviewRequest
    export type PreviewPromptApiPromptsFunctionTypePreviewPostMutationError = HTTPValidationError

    /**
 * @summary Preview Prompt
 */
export const usePreviewPromptApiPromptsFunctionTypePreviewPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewPromptApiPromptsFunctionTypePreviewPost>>, TError,{functionType: string;data: PromptPreviewRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof previewPromptApiPromptsFunctionTypePreviewPost>>,
        TError,
        {functionType: string;data: PromptPreviewRequest},
        TContext
      > => {
      return useMutation(getPreviewPromptApiPromptsFunctionTypePreviewPostMutationOptions(options), queryClient);
    }
