"""Auto-reply record API endpoints.

Provides listing, update, and delete views for auto-reply drafts
generated by the AI auto-reply plugin.
"""

from typing import Literal
from uuid import UUID

import structlog
from fastapi import APIRouter, Query
from sqlalchemy import select

from app.api.deps import CurrentUserId, DbSession, build_paginated_response, get_or_404, paginate, sanitize_like
from app.models import AutoReplyRecord
from app.schemas.auto_reply import (
    AutoReplyRecordListResponse,
    AutoReplyRecordResponse,
    AutoReplyRecordUpdate,
)

logger = structlog.get_logger()

router = APIRouter(prefix="/api/auto-replies", tags=["auto-replies"])


@router.get("")
async def list_auto_replies(
    db: DbSession,
    user_id: CurrentUserId,
    page: int = Query(default=1, ge=1),
    per_page: int = Query(default=20, ge=1, le=100),
    search: str | None = None,
    sort: Literal["newest", "oldest"] = Query(default="newest", description="Sort order"),
) -> AutoReplyRecordListResponse:
    """List auto-reply records with pagination and optional search filter."""
    uid = user_id

    base_stmt = select(AutoReplyRecord).where(AutoReplyRecord.user_id == uid)

    if search:
        base_stmt = base_stmt.where(AutoReplyRecord.mail_subject.ilike(f"%{sanitize_like(search)}%"))

    order_col = AutoReplyRecord.created_at.asc() if sort == "oldest" else AutoReplyRecord.created_at.desc()

    base_stmt = base_stmt.order_by(order_col)
    result = await paginate(db, base_stmt, page, per_page)

    return build_paginated_response(result, AutoReplyRecordResponse, AutoReplyRecordListResponse)


@router.get("/{reply_id}")
async def get_auto_reply(
    reply_id: UUID,
    db: DbSession,
    user_id: CurrentUserId,
) -> AutoReplyRecordResponse:
    """Get a single auto-reply record."""
    record = await get_or_404(db, AutoReplyRecord, reply_id, user_id, "Auto-reply not found")
    return AutoReplyRecordResponse.model_validate(record)


@router.patch("/{reply_id}")
async def update_auto_reply(
    reply_id: UUID,
    data: AutoReplyRecordUpdate,
    db: DbSession,
    user_id: CurrentUserId,
) -> AutoReplyRecordResponse:
    """Update an auto-reply draft."""
    record = await get_or_404(db, AutoReplyRecord, reply_id, user_id, "Auto-reply not found")

    update_data = data.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(record, field, value)

    await db.flush()
    logger.info("auto_reply_updated", reply_id=str(reply_id))
    return AutoReplyRecordResponse.model_validate(record)


@router.delete("/{reply_id}", status_code=204)
async def delete_auto_reply(
    reply_id: UUID,
    db: DbSession,
    user_id: CurrentUserId,
) -> None:
    """Delete an auto-reply record."""
    record = await get_or_404(db, AutoReplyRecord, reply_id, user_id, "Auto-reply not found")
    await db.delete(record)
    await db.flush()
    logger.info("auto_reply_deleted", reply_id=str(reply_id))
