/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CallbackAuthCallbackGetParams,
  HTTPValidationError
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Initiate OIDC login by redirecting to the identity provider.
 * @summary Login
 */
export type loginAuthLoginGetResponse200 = {
  data: unknown
  status: 200
}

export type loginAuthLoginGetResponseSuccess = (loginAuthLoginGetResponse200) & {
  headers: Headers;
};
;

export type loginAuthLoginGetResponse = (loginAuthLoginGetResponseSuccess)

export const getLoginAuthLoginGetUrl = () => {




  return `/auth/login`
}

export const loginAuthLoginGet = async ( options?: RequestInit): Promise<loginAuthLoginGetResponse> => {

  return customInstance<loginAuthLoginGetResponse>(getLoginAuthLoginGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getLoginAuthLoginGetQueryKey = () => {
    return [
    `/auth/login`
    ] as const;
    }


export const getLoginAuthLoginGetQueryOptions = <TData = Awaited<ReturnType<typeof loginAuthLoginGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginAuthLoginGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginAuthLoginGet>>> = ({ signal }) => loginAuthLoginGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LoginAuthLoginGetQueryResult = NonNullable<Awaited<ReturnType<typeof loginAuthLoginGet>>>
export type LoginAuthLoginGetQueryError = unknown


export function useLoginAuthLoginGet<TData = Awaited<ReturnType<typeof loginAuthLoginGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginAuthLoginGet>>,
          TError,
          Awaited<ReturnType<typeof loginAuthLoginGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoginAuthLoginGet<TData = Awaited<ReturnType<typeof loginAuthLoginGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginAuthLoginGet>>,
          TError,
          Awaited<ReturnType<typeof loginAuthLoginGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoginAuthLoginGet<TData = Awaited<ReturnType<typeof loginAuthLoginGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Login
 */

export function useLoginAuthLoginGet<TData = Awaited<ReturnType<typeof loginAuthLoginGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLoginAuthLoginGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Handle OIDC callback after user authenticates with the identity provider.
 * @summary Callback
 */
export type callbackAuthCallbackGetResponse200 = {
  data: unknown
  status: 200
}

export type callbackAuthCallbackGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type callbackAuthCallbackGetResponseSuccess = (callbackAuthCallbackGetResponse200) & {
  headers: Headers;
};
export type callbackAuthCallbackGetResponseError = (callbackAuthCallbackGetResponse422) & {
  headers: Headers;
};

export type callbackAuthCallbackGetResponse = (callbackAuthCallbackGetResponseSuccess | callbackAuthCallbackGetResponseError)

export const getCallbackAuthCallbackGetUrl = (params: CallbackAuthCallbackGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/callback?${stringifiedParams}` : `/auth/callback`
}

export const callbackAuthCallbackGet = async (params: CallbackAuthCallbackGetParams, options?: RequestInit): Promise<callbackAuthCallbackGetResponse> => {

  return customInstance<callbackAuthCallbackGetResponse>(getCallbackAuthCallbackGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCallbackAuthCallbackGetQueryKey = (params?: CallbackAuthCallbackGetParams,) => {
    return [
    `/auth/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const getCallbackAuthCallbackGetQueryOptions = <TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = HTTPValidationError>(params: CallbackAuthCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCallbackAuthCallbackGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof callbackAuthCallbackGet>>> = ({ signal }) => callbackAuthCallbackGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CallbackAuthCallbackGetQueryResult = NonNullable<Awaited<ReturnType<typeof callbackAuthCallbackGet>>>
export type CallbackAuthCallbackGetQueryError = HTTPValidationError


export function useCallbackAuthCallbackGet<TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = HTTPValidationError>(
 params: CallbackAuthCallbackGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof callbackAuthCallbackGet>>,
          TError,
          Awaited<ReturnType<typeof callbackAuthCallbackGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCallbackAuthCallbackGet<TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = HTTPValidationError>(
 params: CallbackAuthCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof callbackAuthCallbackGet>>,
          TError,
          Awaited<ReturnType<typeof callbackAuthCallbackGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCallbackAuthCallbackGet<TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = HTTPValidationError>(
 params: CallbackAuthCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Callback
 */

export function useCallbackAuthCallbackGet<TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = HTTPValidationError>(
 params: CallbackAuthCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCallbackAuthCallbackGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Clear session and optionally trigger OIDC end_session.
 * @summary Logout
 */
export type logoutAuthLogoutPostResponse200 = {
  data: unknown
  status: 200
}

export type logoutAuthLogoutPostResponseSuccess = (logoutAuthLogoutPostResponse200) & {
  headers: Headers;
};
;

export type logoutAuthLogoutPostResponse = (logoutAuthLogoutPostResponseSuccess)

export const getLogoutAuthLogoutPostUrl = () => {




  return `/auth/logout`
}

export const logoutAuthLogoutPost = async ( options?: RequestInit): Promise<logoutAuthLogoutPostResponse> => {

  return customInstance<logoutAuthLogoutPostResponse>(getLogoutAuthLogoutPostUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLogoutAuthLogoutPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutAuthLogoutPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logoutAuthLogoutPost>>, TError,void, TContext> => {

const mutationKey = ['logoutAuthLogoutPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutAuthLogoutPost>>, void> = () => {


          return  logoutAuthLogoutPost(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutAuthLogoutPostMutationResult = NonNullable<Awaited<ReturnType<typeof logoutAuthLogoutPost>>>

    export type LogoutAuthLogoutPostMutationError = unknown

    /**
 * @summary Logout
 */
export const useLogoutAuthLogoutPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutAuthLogoutPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutAuthLogoutPostMutationOptions(options), queryClient);
    }
    /**
 * Return current authenticated user info.
 * @summary Get Current User
 */
export type getCurrentUserAuthMeGetResponse200 = {
  data: unknown
  status: 200
}

export type getCurrentUserAuthMeGetResponseSuccess = (getCurrentUserAuthMeGetResponse200) & {
  headers: Headers;
};
;

export type getCurrentUserAuthMeGetResponse = (getCurrentUserAuthMeGetResponseSuccess)

export const getGetCurrentUserAuthMeGetUrl = () => {




  return `/auth/me`
}

export const getCurrentUserAuthMeGet = async ( options?: RequestInit): Promise<getCurrentUserAuthMeGetResponse> => {

  return customInstance<getCurrentUserAuthMeGetResponse>(getGetCurrentUserAuthMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCurrentUserAuthMeGetQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }


export const getGetCurrentUserAuthMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserAuthMeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>> = ({ signal }) => getCurrentUserAuthMeGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserAuthMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>>
export type GetCurrentUserAuthMeGetQueryError = unknown


export function useGetCurrentUserAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Current User
 */

export function useGetCurrentUserAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




