/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * mailassist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CouponUpdate,
  ExtractedCouponListResponse,
  ExtractedCouponResponse,
  HTTPValidationError,
  ListCouponsApiCouponsGetParams
} from '../../../types/api';

import { customInstance } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List extracted coupons with pagination and optional filters.
 * @summary List Coupons
 */
export type listCouponsApiCouponsGetResponse200 = {
  data: ExtractedCouponListResponse
  status: 200
}

export type listCouponsApiCouponsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listCouponsApiCouponsGetResponseSuccess = (listCouponsApiCouponsGetResponse200) & {
  headers: Headers;
};
export type listCouponsApiCouponsGetResponseError = (listCouponsApiCouponsGetResponse422) & {
  headers: Headers;
};

export type listCouponsApiCouponsGetResponse = (listCouponsApiCouponsGetResponseSuccess | listCouponsApiCouponsGetResponseError)

export const getListCouponsApiCouponsGetUrl = (params?: ListCouponsApiCouponsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/coupons?${stringifiedParams}` : `/api/coupons`
}

export const listCouponsApiCouponsGet = async (params?: ListCouponsApiCouponsGetParams, options?: RequestInit): Promise<listCouponsApiCouponsGetResponse> => {

  return customInstance<listCouponsApiCouponsGetResponse>(getListCouponsApiCouponsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCouponsApiCouponsGetQueryKey = (params?: ListCouponsApiCouponsGetParams,) => {
    return [
    `/api/coupons`, ...(params ? [params] : [])
    ] as const;
    }


export const getListCouponsApiCouponsGetQueryOptions = <TData = Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError = HTTPValidationError>(params?: ListCouponsApiCouponsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCouponsApiCouponsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCouponsApiCouponsGet>>> = ({ signal }) => listCouponsApiCouponsGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCouponsApiCouponsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listCouponsApiCouponsGet>>>
export type ListCouponsApiCouponsGetQueryError = HTTPValidationError


export function useListCouponsApiCouponsGet<TData = Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListCouponsApiCouponsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCouponsApiCouponsGet>>,
          TError,
          Awaited<ReturnType<typeof listCouponsApiCouponsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCouponsApiCouponsGet<TData = Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError = HTTPValidationError>(
 params?: ListCouponsApiCouponsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCouponsApiCouponsGet>>,
          TError,
          Awaited<ReturnType<typeof listCouponsApiCouponsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCouponsApiCouponsGet<TData = Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError = HTTPValidationError>(
 params?: ListCouponsApiCouponsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Coupons
 */

export function useListCouponsApiCouponsGet<TData = Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError = HTTPValidationError>(
 params?: ListCouponsApiCouponsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCouponsApiCouponsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCouponsApiCouponsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get a single extracted coupon with full details.
 * @summary Get Coupon
 */
export type getCouponApiCouponsCouponIdGetResponse200 = {
  data: ExtractedCouponResponse
  status: 200
}

export type getCouponApiCouponsCouponIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getCouponApiCouponsCouponIdGetResponseSuccess = (getCouponApiCouponsCouponIdGetResponse200) & {
  headers: Headers;
};
export type getCouponApiCouponsCouponIdGetResponseError = (getCouponApiCouponsCouponIdGetResponse422) & {
  headers: Headers;
};

export type getCouponApiCouponsCouponIdGetResponse = (getCouponApiCouponsCouponIdGetResponseSuccess | getCouponApiCouponsCouponIdGetResponseError)

export const getGetCouponApiCouponsCouponIdGetUrl = (couponId: string,) => {




  return `/api/coupons/${couponId}`
}

export const getCouponApiCouponsCouponIdGet = async (couponId: string, options?: RequestInit): Promise<getCouponApiCouponsCouponIdGetResponse> => {

  return customInstance<getCouponApiCouponsCouponIdGetResponse>(getGetCouponApiCouponsCouponIdGetUrl(couponId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCouponApiCouponsCouponIdGetQueryKey = (couponId: string,) => {
    return [
    `/api/coupons/${couponId}`
    ] as const;
    }


export const getGetCouponApiCouponsCouponIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError = HTTPValidationError>(couponId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCouponApiCouponsCouponIdGetQueryKey(couponId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>> = ({ signal }) => getCouponApiCouponsCouponIdGet(couponId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(couponId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCouponApiCouponsCouponIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>>
export type GetCouponApiCouponsCouponIdGetQueryError = HTTPValidationError


export function useGetCouponApiCouponsCouponIdGet<TData = Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError = HTTPValidationError>(
 couponId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>,
          TError,
          Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCouponApiCouponsCouponIdGet<TData = Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError = HTTPValidationError>(
 couponId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>,
          TError,
          Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCouponApiCouponsCouponIdGet<TData = Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError = HTTPValidationError>(
 couponId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Coupon
 */

export function useGetCouponApiCouponsCouponIdGet<TData = Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError = HTTPValidationError>(
 couponId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCouponApiCouponsCouponIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCouponApiCouponsCouponIdGetQueryOptions(couponId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Update a coupon (e.g. mark as used).
 * @summary Update Coupon
 */
export type updateCouponApiCouponsCouponIdPatchResponse200 = {
  data: ExtractedCouponResponse
  status: 200
}

export type updateCouponApiCouponsCouponIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateCouponApiCouponsCouponIdPatchResponseSuccess = (updateCouponApiCouponsCouponIdPatchResponse200) & {
  headers: Headers;
};
export type updateCouponApiCouponsCouponIdPatchResponseError = (updateCouponApiCouponsCouponIdPatchResponse422) & {
  headers: Headers;
};

export type updateCouponApiCouponsCouponIdPatchResponse = (updateCouponApiCouponsCouponIdPatchResponseSuccess | updateCouponApiCouponsCouponIdPatchResponseError)

export const getUpdateCouponApiCouponsCouponIdPatchUrl = (couponId: string,) => {




  return `/api/coupons/${couponId}`
}

export const updateCouponApiCouponsCouponIdPatch = async (couponId: string,
    couponUpdate: CouponUpdate, options?: RequestInit): Promise<updateCouponApiCouponsCouponIdPatchResponse> => {

  return customInstance<updateCouponApiCouponsCouponIdPatchResponse>(getUpdateCouponApiCouponsCouponIdPatchUrl(couponId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      couponUpdate,)
  }
);}




export const getUpdateCouponApiCouponsCouponIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCouponApiCouponsCouponIdPatch>>, TError,{couponId: string;data: CouponUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCouponApiCouponsCouponIdPatch>>, TError,{couponId: string;data: CouponUpdate}, TContext> => {

const mutationKey = ['updateCouponApiCouponsCouponIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCouponApiCouponsCouponIdPatch>>, {couponId: string;data: CouponUpdate}> = (props) => {
          const {couponId,data} = props ?? {};

          return  updateCouponApiCouponsCouponIdPatch(couponId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCouponApiCouponsCouponIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateCouponApiCouponsCouponIdPatch>>>
    export type UpdateCouponApiCouponsCouponIdPatchMutationBody = CouponUpdate
    export type UpdateCouponApiCouponsCouponIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Coupon
 */
export const useUpdateCouponApiCouponsCouponIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCouponApiCouponsCouponIdPatch>>, TError,{couponId: string;data: CouponUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCouponApiCouponsCouponIdPatch>>,
        TError,
        {couponId: string;data: CouponUpdate},
        TContext
      > => {
      return useMutation(getUpdateCouponApiCouponsCouponIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete an extracted coupon record.
 * @summary Delete Coupon
 */
export type deleteCouponApiCouponsCouponIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteCouponApiCouponsCouponIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteCouponApiCouponsCouponIdDeleteResponseSuccess = (deleteCouponApiCouponsCouponIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteCouponApiCouponsCouponIdDeleteResponseError = (deleteCouponApiCouponsCouponIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteCouponApiCouponsCouponIdDeleteResponse = (deleteCouponApiCouponsCouponIdDeleteResponseSuccess | deleteCouponApiCouponsCouponIdDeleteResponseError)

export const getDeleteCouponApiCouponsCouponIdDeleteUrl = (couponId: string,) => {




  return `/api/coupons/${couponId}`
}

export const deleteCouponApiCouponsCouponIdDelete = async (couponId: string, options?: RequestInit): Promise<deleteCouponApiCouponsCouponIdDeleteResponse> => {

  return customInstance<deleteCouponApiCouponsCouponIdDeleteResponse>(getDeleteCouponApiCouponsCouponIdDeleteUrl(couponId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteCouponApiCouponsCouponIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouponApiCouponsCouponIdDelete>>, TError,{couponId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCouponApiCouponsCouponIdDelete>>, TError,{couponId: string}, TContext> => {

const mutationKey = ['deleteCouponApiCouponsCouponIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCouponApiCouponsCouponIdDelete>>, {couponId: string}> = (props) => {
          const {couponId} = props ?? {};

          return  deleteCouponApiCouponsCouponIdDelete(couponId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCouponApiCouponsCouponIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCouponApiCouponsCouponIdDelete>>>

    export type DeleteCouponApiCouponsCouponIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Coupon
 */
export const useDeleteCouponApiCouponsCouponIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCouponApiCouponsCouponIdDelete>>, TError,{couponId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCouponApiCouponsCouponIdDelete>>,
        TError,
        {couponId: string},
        TContext
      > => {
      return useMutation(getDeleteCouponApiCouponsCouponIdDeleteMutationOptions(options), queryClient);
    }
